import { ThemeTokens } from './themeTypes';

export const lightTheme: ThemeTokens = {
  background: '#FFFFFF',
  backgroundSecondary: '#FAFAFC',
  foreground: '#1D2B64',
  surface: '#FFFFFF',
  surfaceElevated: '#FAFAFC',
  surfaceHover: '#E6F2F8',
  card: '#FFFFFF',
  cardForeground: '#1D2B64',
  popover: '#FFFFFF',
  popoverForeground: '#1D2B64',
  primary: '#3B6CE7',
  primaryHover: '#2554C7',
  primaryActive: '#1D45A5',
  primaryForeground: '#FFFFFF',
  secondary: '#8CC8E8',
  secondaryForeground: '#1D2B64',
  accent: '#E6F2F8',
  accentForeground: '#1D2B64',
  muted: '#F1F5F9',
  mutedForeground: '#64748B',
  border: '#E2E8F0',
  borderStrong: '#CBD5E1',
  input: '#E2E8F0',
  ring: '#3B6CE7',
  brandNavy: '#1D2B64',
  brandBlue: '#3B6CE7',
  brandSky: '#8CC8E8',
  brandIce: '#E6F2F8',
  
  // Veytrix specific
  backgroundPrimary: '#FFFFFF',
  royalBlue: '#1D2B64',
  primaryBlue: '#3B6CE7',
  iceBlue: '#8CC8E8',
  white: '#FFFFFF',
  mutedWhite: '#1D2B64',
  subtleWhite: '#1D2B64',
  activeBorder: '#3B6CE7',
};
