import { EffectItem } from '../components/EffectGrid';

export const RETRO_VHS_EFFECTS: EffectItem[] = [
  { id: 'analog-memories', name: 'Analog Memories', description: 'Warm nostalgic low contrast grade with soft focus and frame jitter.', icon: '🧠', isNew: true },
  { id: 'analog-noise', name: 'Analog Noise', description: 'Simulates low-signal static snow with soft analog buzz noise.', icon: '📻' },
  { id: 'analog-studio', name: 'Analog Studio', description: 'Master tape resolution emulation with warm chroma levels.', icon: '🎙️', isNew: true },
  { id: 'analog-tv', name: 'Analog TV', description: 'CRT retro monitor grid scan lines with slight horizontal drift.', icon: '📺' },
  { id: 'archive-footage', name: 'Archive Footage', description: 'Historical newsreel profile with low framerate and high contrast.', icon: '📽️', isNew: true },
  { id: 'betacam-style', name: 'Betacam Style', description: 'Analog professional broadcast look with rich color detail and light tape hiss.', icon: '📺', isNew: true },
  { id: 'camcorder-classic', name: 'Camcorder Classic', description: 'Recreates the standard 1990s home camcorder dynamic range and focus.', icon: '📹', isNew: true },
  { id: 'cinema-archive', name: 'Cinema Archive', description: 'Recreates historic silent-film project texture and frame jitter.', icon: '🎞️' },
  { id: 'color-bleed', name: 'Color Bleed', description: 'Chromatic alignment offsets causing red/cyan fringing bleed.', icon: '🎨' },
  { id: 'color-drift', name: 'Color Drift', description: 'Continuous slight shifts in red and blue channel alignments.', icon: '🌈', isNew: true },
  { id: 'crt-deluxe', name: 'CRT Deluxe', description: 'High-end phosphorus grid replication with curved corner vignettes.', icon: '🖥️', isNew: true },
  { id: 'crt-flicker-pro', name: 'CRT Flicker Pro', description: 'Simulates video capture of a computer monitor with sweep lines.', icon: '📺', isNew: true },
  { id: 'crt-monitor', name: 'CRT Monitor', description: 'Simulates curved phosphor screen lines and retro tube glow.', icon: '🖥️' },
  { id: 'dust-scratches', name: 'Dust & Scratches', description: 'Random black dust specks and vertical scratches overlay.', icon: '📽️' },
  { id: 'dust-film-pro', name: 'Dust Film Pro', description: 'Dense high-fidelity organic dust specs scrolling dynamically.', icon: '🌫️', isNew: true },
  { id: 'film-burn', name: 'Film Burn', description: 'Warm organic light leaks bleeding in from the edges of the frame.', icon: '🔥' },
  { id: 'film-grain-pro', name: 'Film Grain Pro', description: 'Fine-grained chemical film simulation for high texture look.', icon: '🌫️' },
  { id: 'film-leader', name: 'Film Leader', description: 'Classic countdown frame numbers with heavy dust and scratches.', icon: '🎞️', isNew: true },
  { id: 'film-projector-pro', name: 'Film Projector Pro', description: 'Vertical frame jitter with mechanical shutter light flickers.', icon: '📽️', isNew: true },
  { id: 'hi8-camera', name: 'Hi8 Camera', description: 'Warm home-video tape profile with mild edge blur details.', icon: '📼', isNew: true },
  { id: 'minidv-look', name: 'MiniDV Look', description: 'Early 2000s digital tape styling with subtle compression noise.', icon: '📹', isNew: true },
  { id: 'old-movie', name: 'Old Movie', description: 'Sepia tone grading with frame rate stutter and heavy dust.', icon: '🎥' },
  { id: 'retro-broadcast', name: 'Retro Broadcast', description: 'Analog network feed grading with soft color bleed edges.', icon: '📻', isNew: true },
  { id: 'retro-cinema-pro', name: 'Retro Cinema Pro', description: 'Technicolor look with rich organic saturation.', icon: '🎬', isNew: true },
  { id: 'retro-fade', name: 'Retro Fade', description: 'Fades black points into dark grey for a vintage matte wash.', icon: '🕯️' },
  { id: 'retro-glow', name: 'Retro Glow', description: 'Dreamy low-contrast highlight bloom mimicking vintage optics.', icon: '🌟' },
  { id: 'rgb-vintage', name: 'RGB Vintage', description: 'Three-channel split aberration with retro warm color tint.', icon: '🌈' },
  { id: 'sepia-classic', name: 'Sepia Classic', description: 'Monochrome brown photo-grade for historic representations.', icon: '🟤' },
  { id: 'static-broadcast', name: 'Static Broadcast', description: 'Heavy screen noise with vertical signal bar sweeps.', icon: '🌫️', isNew: true },
  { id: 'super-8-film', name: 'Super 8 Film', description: 'Organic vintage frame jitter and warm saturated color profile.', icon: '📼' },
  { id: 'tape-damage', name: 'Tape Damage', description: 'VHS tracking tear error lines with temporary vertical sync drops.', icon: '✂️' },
  { id: 'tape-hiss', name: 'Tape Hiss', description: 'Intermittent signal white noise bands crossing horizontally.', icon: '📻', isNew: true },
  { id: 'vhs-archive', name: 'VHS Archive', description: 'Highly degraded archival tape look with horizontal tear lines.', icon: '📼', isNew: true },
  { id: 'vhs-broadcast', name: 'VHS Broadcast', description: 'Late 80s television feed emulation with mild tracking jitter.', icon: '📻', isNew: true },
  { id: 'vhs-classic', name: 'VHS Classic', description: 'Authentic 90s tape look with soft resolution and tracking drift.', icon: '📼' },
  { id: 'vhs-clean', name: 'VHS Clean', description: 'Mild retro tape profile with clean saturation and subtle scanlines.', icon: '📟' },
  { id: 'vhs-deluxe', name: 'VHS Deluxe', description: 'Rich deep color grading with high-end VHS tape saturation.', icon: '📼', isNew: true },
  { id: 'vhs-home-video', name: 'VHS Home Video', description: 'Personal camcorder look with date/time stamps on screen.', icon: '📹', isNew: true },
  { id: 'vhs-premium', name: 'VHS Premium', description: 'Enhanced classic tape style with subtle chroma bleed.', icon: '📼', isNew: true },
  { id: 'vhs-pro-tape', name: 'VHS Pro Tape', description: 'Pro-grade analog tape mastering filter.', icon: '📼', isNew: true },
  { id: 'vhs-recording', name: 'VHS Recording', description: 'Renders red "REC" indicators and blinking dots on preview.', icon: '🔴', isNew: true },
  { id: 'vhs-static', name: 'VHS Static', description: 'Heavy VHS static white noise screen with tape distortion.', icon: '🌪️' },
  { id: 'vhs-tracking', name: 'VHS Tracking', description: 'Intermittent tracking bar sweeps across the bottom viewport.', icon: '📊' },
  { id: 'vintage-camera', name: 'Vintage Camera', description: 'Lomography style lens vignette with high saturation focus.', icon: '📷' },
  { id: 'vintage-reel', name: 'Vintage Reel', description: 'Celluloid print look with vertical scratches and dust specks.', icon: '🎞️', isNew: true }
];
