import { EffectItem } from '../components/EffectGrid';

export const BLUR_EFFECTS: EffectItem[] = [
  { id: 'background-blur', name: 'Background Blur', description: 'Blurs everything except the key foreground subject.', icon: '👤' },
  { id: 'blur-bloom', name: 'Blur Bloom', description: 'Gently diffuses bright light sources with a soft highlight glow.', icon: '🌸', isNew: true },
  { id: 'blur-burst', name: 'Blur Burst', description: 'Radial explosion style blur expanding dynamically from center screen.', icon: '🔎', isNew: true },
  { id: 'blur-distort', name: 'Blur Distort', description: 'Refractive wet glass distortion blending pixels into wavy shapes.', icon: '🌀', isNew: true },
  { id: 'blur-drift', name: 'Blur Drift', description: 'Gradual linear drift shifting directional smearing over time.', icon: '🏃', isNew: true },
  { id: 'blur-echo', name: 'Blur Echo', description: 'Overlays ghost frames of past movement with soft delay values.', icon: '🕯️', isNew: true },
  { id: 'blur-fade', name: 'Blur Fade', description: 'Soft crossfade transition moving from blur to clear.', icon: '🕯️' },
  { id: 'blur-fade-pro', name: 'Blur Fade Pro', description: 'Premium cinematic fade transition with custom threshold curves.', icon: '🕯️', isNew: true },
  { id: 'blur-flash', name: 'Blur Flash', description: 'Sudden high exposure blur pulse mimicking intense lens flare.', icon: '⚡', isNew: true },
  { id: 'blur-melt', name: 'Blur Melt', description: 'Liquid vertical melt bleed mixing colors down the screen.', icon: '🛁', isNew: true },
  { id: 'blur-orbit', name: 'Blur Orbit', description: 'Orbital rotational camera smearing around central subjects.', icon: '🔄', isNew: true },
  { id: 'blur-pulse', name: 'Blur Pulse', description: 'Dynamic focus breathing that rhythmically blurs and sharpens.', icon: '💓', isNew: true },
  { id: 'blur-ripple', name: 'Blur Ripple', description: 'Circular water drop ripples displacing and smearing layout lines.', icon: '🌊', isNew: true },
  { id: 'blur-shockwave', name: 'Blur Shockwave', description: 'Explosive ring of extreme refraction moving outward.', icon: '💥', isNew: true },
  { id: 'blur-spin', name: 'Blur Spin', description: 'Fast camera rotational spin blur around Z-axis coordinates.', icon: '💫', isNew: true },
  { id: 'blur-stretch', name: 'Blur Stretch', description: 'Elongated directional smear widening screen subjects.', icon: '↗️', isNew: true },
  { id: 'blur-swirl', name: 'Blur Swirl', description: 'Vortex swirl twisting coordinates around central pivot points.', icon: '🌀', isNew: true },
  { id: 'blur-trail', name: 'Blur Trail', description: 'Leaves a dreamy trailing smudge behind moving subjects.', icon: '🏃', isNew: true },
  { id: 'blur-tunnel', name: 'Blur Tunnel', description: 'Linear zoom perspective blur focusing viewer attention inward.', icon: '🔎', isNew: true },
  { id: 'bokeh-blur', name: 'Bokeh Blur', description: 'Renders circle-of-confusion light shapes on dark areas.', icon: '⭐' },
  { id: 'cinematic-defocus', name: 'Cinematic Defocus', description: 'Classic prime lens defocus simulating high-end cinema optics.', icon: '👓', isNew: true },
  { id: 'crystal-blur', name: 'Crystal Blur', description: 'Refracts light through crystal prism geometry shapes.', icon: '💎', isNew: true },
  { id: 'directional-blur', name: 'Directional Blur', description: 'Smears details along specific angle boundaries.', icon: '↗️' },
  { id: 'dream-blur', name: 'Dream Blur', description: 'Diffused bright glow layers overlaid on blurry scenes.', icon: '💭' },
  { id: 'dynamic-focus', name: 'Dynamic Focus', description: 'Intelligent focus shift tracking main horizontal subjects.', icon: '🎯', isNew: true },
  { id: 'edge-blur', name: 'Edge Blur', description: 'Blurs only the outer borders of the frame.', icon: '🖼️' },
  { id: 'focus-blur', name: 'Focus Blur', description: 'Fades from fully blurry to sharp focus coordinates.', icon: '🎯' },
  { id: 'gaussian-blur', name: 'Gaussian Blur', description: 'Standard mathematical blur spreading pixel values evenly.', icon: '🌫️' },
  { id: 'glass-blur', name: 'Glass Blur', description: 'Frosted window glass texture overlaying the clip.', icon: '🖼️', isNew: true },
  { id: 'glow-blur', name: 'Glow Blur', description: 'Luminous highlights smeared with high-radius gaussian blends.', icon: '✨' },
  { id: 'iris-blur', name: 'Iris Blur', description: 'Radial focus blur masking oval shapes.', icon: '👁️' },
  { id: 'lens-blur', name: 'Lens Blur', description: 'Defocused camera lens simulation with custom iris shapes.', icon: '👓' },
  { id: 'mirror-blur', name: 'Mirror Blur', description: 'Symmetrical mirrored blurs splitting layout coordinates.', icon: '🪞', isNew: true },
  { id: 'mist-blur', name: 'Mist Blur', description: 'Fine atmospheric mist dampening contrast and details.', icon: '🌸', isNew: true },
  { id: 'motion-blur', name: 'Motion Blur', description: 'Directional smearing matching camera travel travel speed.', icon: '🏃' },
  { id: 'pixel-blur', name: 'Pixel Blur', description: 'Mosaic-like pixelated blur dividing clips into blocks.', icon: '👾' },
  { id: 'radial-blur', name: 'Radial Blur', description: 'Circular rotational blur spinning from pivot centers.', icon: '🌀' },
  { id: 'smart-blur', name: 'Smart Blur', description: 'Blur that actively preserves outline borders and faces.', icon: '🧠' },
  { id: 'smooth-blur', name: 'Smooth Blur', description: 'Bilateral texture blur reducing video noise.', icon: '🛁' },
  { id: 'soft-blur', name: 'Soft Blur', description: 'Subtle dreaming blur preserving edge values.', icon: '🌸' },
  { id: 'speed-blur', name: 'Speed Blur', description: 'Dynamic directional travel smear for chase sequences.', icon: '⚡' },
  { id: 'tilt-shift', name: 'Tilt Shift', description: 'Linear selective focus blur giving miniature landscape scales.', icon: '🚃' },
  { id: 'velvet-blur', name: 'Velvet Blur', description: 'Ultra-smooth high-radius blur giving a velvety cinematic dreamscape.', icon: '🌸', isNew: true },
  { id: 'water-blur', name: 'Water Blur', description: 'Refractive fluid ripple blur mimicking underwater views.', icon: '🌊', isNew: true },
  { id: 'zoom-blur', name: 'Zoom Blur', description: 'Burst blur expanding outward from center screen coordinates.', icon: '🔎' }
];
