import { TransitionItem } from './Transitions.types';

export const SAMPLE_TRANSITIONS_NEW: TransitionItem[] = [
  // ==========================================
  // BASIC TRANSITIONS (25)
  // ==========================================
  {
    id: 'cross-dissolve-premium',
    name: 'Cross Dissolve',
    category: 'basic',
    description: 'Blends Clip A into Clip B smoothly using a standard linear opacity curve.',
    defaultDuration: 0.8,
    icon: '🌫️',
    keywords: ['fade', 'dissolve', 'blend', 'cross', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'fade-to-black-premium',
    name: 'Fade to Black',
    category: 'basic',
    description: 'smoothly dips to black before fading up to Clip B.',
    defaultDuration: 0.6,
    icon: '🌑',
    keywords: ['dip', 'black', 'dark', 'fade', 'basic'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 70,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'fade-to-white-premium',
    name: 'Fade to White',
    category: 'basic',
    description: 'smoothly dips to white before fading up to Clip B.',
    defaultDuration: 0.6,
    icon: '☀️',
    keywords: ['dip', 'white', 'bright', 'fade', 'basic'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 70,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dip-to-color-premium',
    name: 'Dip to Color',
    category: 'basic',
    description: 'Smooth fade to a selected custom solid color background.',
    defaultDuration: 0.7,
    icon: '🎨',
    keywords: ['color', 'fade', 'dip', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'instant-cut-premium',
    name: 'Instant Cut',
    category: 'basic',
    description: 'A clean immediate frame change between Clip A and Clip B.',
    defaultDuration: 0.2,
    icon: '✂️',
    keywords: ['cut', 'jump', 'instant', 'hard', 'basic'],
    direction: 'none',
    easing: 'linear',
    intensity: 0,
    speed: 2.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'smooth-fade-premium',
    name: 'Smooth Fade',
    category: 'basic',
    description: 'Ultra-smooth opacity curve transition blending details.',
    defaultDuration: 1.0,
    icon: '🧼',
    keywords: ['smooth', 'fade', 'opacity', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 40,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'flash-cut-premium',
    name: 'Flash Cut',
    category: 'basic',
    description: 'Flashes white for a split frame at the point of change.',
    defaultDuration: 0.3,
    icon: '⚡',
    keywords: ['flash', 'white', 'bright', 'cut', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.5,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'soft-dissolve-premium',
    name: 'Soft Dissolve',
    category: 'basic',
    description: 'Gently blends frames using a sinusoidal transition shape.',
    defaultDuration: 0.9,
    icon: '🌸',
    keywords: ['soft', 'dissolve', 'crossfade', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 30,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-dissolve-premium',
    name: 'Blur Dissolve',
    category: 'basic',
    description: 'Blurs Clip A out while blurring Clip B in simultaneously.',
    defaultDuration: 0.7,
    icon: '🌫️',
    keywords: ['blur', 'dissolve', 'soft', 'fade', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'bright-flash-premium',
    name: 'Bright Flash',
    category: 'basic',
    description: 'A sudden cinematic flash of bright highlight glow.',
    defaultDuration: 0.4,
    icon: '☀️',
    keywords: ['bright', 'glow', 'flash', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 90,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dark-fade-premium',
    name: 'Dark Fade',
    category: 'basic',
    description: 'Slow fade down into deep darkness, returning up in Clip B.',
    defaultDuration: 0.8,
    icon: '⬛',
    keywords: ['dark', 'fade', 'black', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'exposure-flash-premium',
    name: 'Exposure Flash',
    category: 'basic',
    description: 'Overexposes clip details briefly to cover the jump point.',
    defaultDuration: 0.5,
    icon: '📸',
    keywords: ['exposure', 'flash', 'bright', 'camera', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 85,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'light-wash-premium',
    name: 'Light Wash',
    category: 'basic',
    description: 'Washes out contrast and highlights with ambient white light.',
    defaultDuration: 0.6,
    icon: '💡',
    keywords: ['wash', 'light', 'white', 'contrast', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'color-fade-premium',
    name: 'Color Fade',
    category: 'basic',
    description: 'Crossfades after temporarily desaturating color channels.',
    defaultDuration: 0.8,
    icon: '🎨',
    keywords: ['color', 'fade', 'grayscale', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'opacity-blend-premium',
    name: 'Opacity Blend',
    category: 'basic',
    description: 'Direct multi-step linear opacity blend over duration.',
    defaultDuration: 0.7,
    icon: '⚪',
    keywords: ['opacity', 'blend', 'cross', 'basic'],
    direction: 'none',
    easing: 'linear',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'film-dissolve-premium',
    name: 'Film Dissolve',
    category: 'basic',
    description: 'Emulates organic physical film stock emulsion crossfades.',
    defaultDuration: 0.9,
    icon: '🎞️',
    keywords: ['film', 'dissolve', 'analog', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'luma-fade-premium',
    name: 'Luma Fade',
    category: 'basic',
    description: 'Fades based on pixel brightness values (brights fade first).',
    defaultDuration: 0.8,
    icon: '💡',
    keywords: ['luma', 'luminance', 'fade', 'reveal', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'soft-reveal-premium',
    name: 'Soft Reveal',
    category: 'basic',
    description: 'A smooth reveal transition starting from center coordinates.',
    defaultDuration: 0.7,
    icon: '👁️',
    keywords: ['reveal', 'soft', 'center', 'basic'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'slow-crossfade-premium',
    name: 'Slow Crossfade',
    category: 'basic',
    description: 'Extended duration fade transition for atmospheric timing.',
    defaultDuration: 1.5,
    icon: '⏳',
    keywords: ['slow', 'crossfade', 'long', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 40,
    speed: 0.5,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'flash-reveal-premium',
    name: 'Flash Reveal',
    category: 'basic',
    description: 'Reveals Clip B from behind a high exposure white flash.',
    defaultDuration: 0.4,
    icon: '⚡',
    keywords: ['flash', 'reveal', 'bright', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 85,
    speed: 1.3,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'ghost-fade-premium',
    name: 'Ghost Fade',
    category: 'basic',
    description: 'Overlays a desaturated copy of Clip B before fading fully.',
    defaultDuration: 0.8,
    icon: '👻',
    keywords: ['ghost', 'fade', 'dream', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'glow-transition-premium',
    name: 'Glow Transition',
    category: 'basic',
    description: 'Increases brightness threshold to bloom highlights into Clip B.',
    defaultDuration: 0.6,
    icon: '🌟',
    keywords: ['glow', 'bloom', 'highlights', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 75,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dream-fade-premium',
    name: 'Dream Fade',
    category: 'basic',
    description: 'Soft pastel-glow blend transition for dream sequences.',
    defaultDuration: 1.0,
    icon: '💭',
    keywords: ['dream', 'fade', 'glow', 'soft', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 45,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'film-flash-premium',
    name: 'Film Flash',
    category: 'basic',
    description: 'Orange film-burn light leak flash transition.',
    defaultDuration: 0.5,
    icon: '🔥',
    keywords: ['film', 'flash', 'burn', 'orange', 'basic'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'seamless-blend-premium',
    name: 'Seamless Blend',
    category: 'basic',
    description: 'Blends background hues smoothly to minimize cut perception.',
    defaultDuration: 0.7,
    icon: '🔗',
    keywords: ['seamless', 'blend', 'smooth', 'cut', 'basic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // CAMERA TRANSITIONS (25)
  // ==========================================
  {
    id: 'handheld-transition',
    name: 'Handheld Transition',
    category: 'camera',
    description: 'Simulates camera operator physical sway to cover the cut.',
    defaultDuration: 0.8,
    icon: '🤳',
    keywords: ['handheld', 'sway', 'drift', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 40,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'camera-shake-transition',
    name: 'Camera Shake',
    category: 'camera',
    description: 'High-frequency micro coordinate shakes on frame junction.',
    defaultDuration: 0.5,
    icon: '📳',
    keywords: ['shake', 'jitter', 'rumble', 'camera'],
    direction: 'none',
    easing: 'elastic',
    intensity: 75,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'crash-zoom-transition',
    name: 'Crash Zoom',
    category: 'camera',
    description: 'Ultra fast zoom forward punch-in centered on screen.',
    defaultDuration: 0.4,
    icon: '💥',
    keywords: ['zoom', 'crash', 'punch', 'camera'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.8,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'snap-zoom-transition',
    name: 'Snap Zoom',
    category: 'camera',
    description: 'Rapid two-step camera zoom punch centered.',
    defaultDuration: 0.3,
    icon: '🔎',
    keywords: ['snap', 'zoom', 'step', 'camera'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.6,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dolly-zoom-transition',
    name: 'Dolly Zoom',
    category: 'camera',
    description: 'Simulates vertigo zoom warping background depth.',
    defaultDuration: 0.9,
    icon: '🌀',
    keywords: ['dolly', 'zoom', 'vertigo', 'depth', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 85,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'push-in-transition',
    name: 'Push In',
    category: 'camera',
    description: 'Steady camera translate zoom forward into Clip B.',
    defaultDuration: 0.7,
    icon: '🔎',
    keywords: ['push', 'zoom', 'forward', 'camera'],
    direction: 'up',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'pull-out-transition',
    name: 'Pull Out',
    category: 'camera',
    description: 'Steady camera translation pulling back out of viewport.',
    defaultDuration: 0.7,
    icon: '🔍',
    keywords: ['pull', 'zoom', 'back', 'camera'],
    direction: 'down',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'orbit-camera-transition',
    name: 'Orbit Camera',
    category: 'camera',
    description: 'Orbital rotation sweep around center viewport points.',
    defaultDuration: 0.8,
    icon: '🔄',
    keywords: ['orbit', 'circular', 'sweep', 'camera'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'follow-camera-transition',
    name: 'Follow Camera',
    category: 'camera',
    description: 'Simulates tracking shots locking movement relative to subjects.',
    defaultDuration: 0.8,
    icon: '🏃',
    keywords: ['follow', 'tracking', 'lock', 'camera'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'lens-pull-transition',
    name: 'Lens Pull',
    category: 'camera',
    description: 'Fast optical focal length shift blurring backgrounds.',
    defaultDuration: 0.6,
    icon: '👓',
    keywords: ['lens', 'pull', 'focus', 'blur', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'rack-focus-transition',
    name: 'Rack Focus',
    category: 'camera',
    description: 'Depth of field shift moving focus plane background to foreground.',
    defaultDuration: 0.7,
    icon: '👓',
    keywords: ['focus', 'rack', 'dof', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'whip-pan-left-transition',
    name: 'Whip Pan Left',
    category: 'camera',
    description: 'High-speed camera horizontal pan sweep left.',
    defaultDuration: 0.5,
    icon: '⬅️',
    keywords: ['whip', 'pan', 'left', 'whip-pan', 'camera'],
    direction: 'left',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'whip-pan-right-transition',
    name: 'Whip Pan Right',
    category: 'camera',
    description: 'High-speed camera horizontal pan sweep right.',
    defaultDuration: 0.5,
    icon: '➡️',
    keywords: ['whip', 'pan', 'right', 'whip-pan', 'camera'],
    direction: 'right',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'whip-pan-up-transition',
    name: 'Whip Pan Up',
    category: 'camera',
    description: 'High-speed camera vertical pan sweep up.',
    defaultDuration: 0.5,
    icon: '⬆️',
    keywords: ['whip', 'pan', 'up', 'whip-pan', 'camera'],
    direction: 'up',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'whip-pan-down-transition',
    name: 'Whip Pan Down',
    category: 'camera',
    description: 'High-speed camera vertical pan sweep down.',
    defaultDuration: 0.5,
    icon: '⬇️',
    keywords: ['whip', 'pan', 'down', 'whip-pan', 'camera'],
    direction: 'down',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'tilt-up-transition',
    name: 'Tilt Up',
    category: 'camera',
    description: 'Steady vertical pivot rotation upward.',
    defaultDuration: 0.6,
    icon: '⬆️',
    keywords: ['tilt', 'up', 'vertical', 'camera'],
    direction: 'up',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'tilt-down-transition',
    name: 'Tilt Down',
    category: 'camera',
    description: 'Steady vertical pivot rotation downward.',
    defaultDuration: 0.6,
    icon: '⬇️',
    keywords: ['tilt', 'down', 'vertical', 'camera'],
    direction: 'down',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'camera-roll-transition',
    name: 'Camera Roll',
    category: 'camera',
    description: 'Dynamic Dutch angle roll rotation tilting landscape angles.',
    defaultDuration: 0.7,
    icon: '📐',
    keywords: ['roll', 'dutch', 'angle', 'camera'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dynamic-follow-transition',
    name: 'Dynamic Follow',
    category: 'camera',
    description: 'Combines hand movements and zooms automatically.',
    defaultDuration: 0.9,
    icon: '🎢',
    keywords: ['dynamic', 'follow', 'zoom', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'action-cam-transition',
    name: 'Action Cam',
    category: 'camera',
    description: 'Aggressive tracking whip pans following action sequences.',
    defaultDuration: 0.6,
    icon: '🏃',
    keywords: ['action', 'sports', 'whip', 'pan', 'camera'],
    direction: 'right',
    easing: 'ease-in',
    intensity: 80,
    speed: 1.4,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'steady-cam-transition',
    name: 'Steady Cam',
    category: 'camera',
    description: 'Highly damped gimbal follow path.',
    defaultDuration: 0.8,
    icon: '🚶',
    keywords: ['steady', 'gimbal', 'damped', 'smooth', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 30,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'fpv-dive-transition',
    name: 'FPV Dive',
    category: 'camera',
    description: 'Recreates high-speed FPV drone vertical dive paths.',
    defaultDuration: 0.6,
    icon: '🪂',
    keywords: ['fpv', 'dive', 'drone', 'camera'],
    direction: 'down',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.6,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'drone-flyover-transition',
    name: 'Drone Flyover',
    category: 'camera',
    description: 'Simulates aerial flyby sweeps looking downward.',
    defaultDuration: 1.0,
    icon: '✈️',
    keywords: ['drone', 'aerial', 'flyover', 'sky', 'camera'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'crane-lift-transition',
    name: 'Crane Lift',
    category: 'camera',
    description: 'Elevates camera vertically as if on a mechanical crane.',
    defaultDuration: 0.8,
    icon: '🏗️',
    keywords: ['crane', 'lift', 'jib', 'up', 'camera'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'crane-drop-transition',
    name: 'Crane Drop',
    category: 'camera',
    description: 'Drops camera vertically down for ground perspective shifts.',
    defaultDuration: 0.8,
    icon: '🪝',
    keywords: ['crane', 'drop', 'down', 'camera'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // ZOOM TRANSITIONS (25)
  // ==========================================
  {
    id: 'zoom-in-transition',
    name: 'Zoom In',
    category: 'zoom',
    description: 'Classic camera zoom forward punch.',
    defaultDuration: 0.5,
    icon: '🔍',
    keywords: ['zoom', 'in', 'forward'],
    direction: 'up',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'zoom-out-transition',
    name: 'Zoom Out',
    category: 'zoom',
    description: 'Classic camera zoom pull backward.',
    defaultDuration: 0.5,
    icon: '🔎',
    keywords: ['zoom', 'out', 'backward'],
    direction: 'down',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'hyper-zoom-transition',
    name: 'Hyper Zoom',
    category: 'zoom',
    description: 'Extremely fast multi-step zoom magnification.',
    defaultDuration: 0.3,
    icon: '💥',
    keywords: ['hyper', 'zoom', 'crash', 'fast'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.8,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'elastic-zoom-transition',
    name: 'Elastic Zoom',
    category: 'zoom',
    description: 'Zooms with dynamic elastic bounce curves.',
    defaultDuration: 0.7,
    icon: '🪀',
    keywords: ['elastic', 'bounce', 'spring', 'zoom'],
    direction: 'center',
    easing: 'elastic',
    intensity: 70,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'bounce-zoom-transition',
    name: 'Bounce Zoom',
    category: 'zoom',
    description: 'Bounces viewport scale back and forth on junction.',
    defaultDuration: 0.6,
    icon: '🏀',
    keywords: ['bounce', 'hit', 'zoom'],
    direction: 'center',
    easing: 'bounce',
    intensity: 75,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'pulse-zoom-transition',
    name: 'Pulse Zoom',
    category: 'zoom',
    description: 'Pulsates frame coordinates in/out rhythmically.',
    defaultDuration: 0.6,
    icon: '💓',
    keywords: ['pulse', 'zoom', 'rhythm'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'center-zoom-transition',
    name: 'Center Zoom',
    category: 'zoom',
    description: 'Symmetric zoom centered precisely on screen coordinates.',
    defaultDuration: 0.5,
    icon: '🎯',
    keywords: ['center', 'zoom', 'symmetric'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'corner-zoom-transition',
    name: 'Corner Zoom',
    category: 'zoom',
    description: 'Asymmetric zoom focusing from top-left border angles.',
    defaultDuration: 0.6,
    icon: '📐',
    keywords: ['corner', 'zoom', 'asymmetric'],
    direction: 'left',
    easing: 'ease-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'smooth-zoom-transition',
    name: 'Smooth Zoom',
    category: 'zoom',
    description: 'Perfect linear scale progression zoom curves.',
    defaultDuration: 0.8,
    icon: '🧼',
    keywords: ['smooth', 'zoom', 'linear'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'radial-zoom-transition',
    name: 'Radial Zoom',
    category: 'zoom',
    description: 'Circular swirling scale expansion paths.',
    defaultDuration: 0.7,
    icon: '🌀',
    keywords: ['radial', 'zoom', 'spin', 'circular'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'infinity-zoom-transition',
    name: 'Infinity Zoom',
    category: 'zoom',
    description: 'Looping zoom scaling that pulls viewer infinitely into Clip B.',
    defaultDuration: 1.0,
    icon: '♾️',
    keywords: ['infinity', 'zoom', 'loop', 'tunnel'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'velocity-zoom-transition',
    name: 'Velocity Zoom',
    category: 'zoom',
    description: 'Speed-ramped scale shift accelerating then braking.',
    defaultDuration: 0.6,
    icon: '⚡',
    keywords: ['velocity', 'ramp', 'zoom', 'speed'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 70,
    speed: 1.4,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'quick-zoom-transition',
    name: 'Quick Zoom',
    category: 'zoom',
    description: 'Short dynamic scale shifts for rapid-fire edit beats.',
    defaultDuration: 0.3,
    icon: '⏱️',
    keywords: ['quick', 'fast', 'zoom', 'short'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.6,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'reverse-zoom-transition',
    name: 'Reverse Zoom',
    category: 'zoom',
    description: 'Zooms in then rapidly pulls back out to reveal Clip B.',
    defaultDuration: 0.6,
    icon: '⏪',
    keywords: ['reverse', 'zoom', 'pull'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'snap-back-zoom-transition',
    name: 'Snap Back Zoom',
    category: 'zoom',
    description: 'Punches scale forward then snaps back to standard limits.',
    defaultDuration: 0.5,
    icon: '↩️',
    keywords: ['snap', 'back', 'zoom'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 70,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'perspective-zoom-transition',
    name: 'Perspective Zoom',
    category: 'zoom',
    description: 'Scales with 3D Z-axis translation angles.',
    defaultDuration: 0.7,
    icon: '📐',
    keywords: ['perspective', 'zoom', '3d'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'warp-zoom-transition',
    name: 'Warp Zoom',
    category: 'zoom',
    description: 'Distorts pixels on radial curves during scale sweeps.',
    defaultDuration: 0.6,
    icon: '🌀',
    keywords: ['warp', 'distortion', 'zoom'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'tunnel-zoom-transition',
    name: 'Tunnel Zoom',
    category: 'zoom',
    description: 'Concentric frame scaling drawing the viewer down a track tunnel.',
    defaultDuration: 0.8,
    icon: '🚇',
    keywords: ['tunnel', 'zoom', 'track'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'lens-zoom-transition',
    name: 'Lens Zoom',
    category: 'zoom',
    description: 'Focal length shift with custom spherical lens aberrations.',
    defaultDuration: 0.6,
    icon: '👓',
    keywords: ['lens', 'zoom', 'aberration'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'focus-zoom-transition',
    name: 'Focus Zoom',
    category: 'zoom',
    description: 'Blurs and scales simultaneously targeting active subjects.',
    defaultDuration: 0.6,
    icon: '🎯',
    keywords: ['focus', 'zoom', 'blur'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 65,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'soft-zoom-transition',
    name: 'Soft Zoom',
    category: 'zoom',
    description: 'Gentle low-intensity zoom curve for romantic settings.',
    defaultDuration: 0.9,
    icon: '🌸',
    keywords: ['soft', 'zoom', 'gentle'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 40,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'hard-zoom-transition',
    name: 'Hard Zoom',
    category: 'zoom',
    description: 'Instant scale magnification jump without easing.',
    defaultDuration: 0.4,
    icon: '🧱',
    keywords: ['hard', 'zoom', 'jump'],
    direction: 'center',
    easing: 'linear',
    intensity: 80,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'mirror-zoom-transition',
    name: 'Mirror Zoom',
    category: 'zoom',
    description: 'Four-way mirrored tiles scaling inward/outward.',
    defaultDuration: 0.7,
    icon: '🪞',
    keywords: ['mirror', 'tile', 'zoom'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cinematic-zoom-transition',
    name: 'Cinematic Zoom',
    category: 'zoom',
    description: 'Dramatic slow widescreen zoom-in.',
    defaultDuration: 1.0,
    icon: '🎞️',
    keywords: ['cinematic', 'zoom', 'slow'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 0.7,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'ultra-zoom-transition',
    name: 'Ultra Zoom',
    category: 'zoom',
    description: 'Extreme dynamic scale punch-in with high-intensity motion blur.',
    defaultDuration: 0.5,
    icon: '🚀',
    keywords: ['ultra', 'zoom', 'blur', 'intense'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 95,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // SLIDE & PUSH TRANSITIONS (25)
  // ==========================================
  {
    id: 'slide-left-transition',
    name: 'Slide Left',
    category: 'slide',
    description: 'Slide A moves left, revealing Slide B underneath.',
    defaultDuration: 0.6,
    icon: '⬅️',
    keywords: ['slide', 'left', 'basic'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'slide-right-transition',
    name: 'Slide Right',
    category: 'slide',
    description: 'Slide A moves right, revealing Slide B underneath.',
    defaultDuration: 0.6,
    icon: '➡️',
    keywords: ['slide', 'right', 'basic'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'slide-up-transition',
    name: 'Slide Up',
    category: 'slide',
    description: 'Slide A moves up, revealing Slide B underneath.',
    defaultDuration: 0.6,
    icon: '⬆️',
    keywords: ['slide', 'up', 'basic'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'slide-down-transition',
    name: 'Slide Down',
    category: 'slide',
    description: 'Slide A moves down, revealing Slide B underneath.',
    defaultDuration: 0.6,
    icon: '⬇️',
    keywords: ['slide', 'down', 'basic'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'push-left-transition',
    name: 'Push Left',
    category: 'slide',
    description: 'Slide A pushes Slide B into view from the right.',
    defaultDuration: 0.6,
    icon: '⬅️',
    keywords: ['push', 'left', 'classic'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'push-right-transition',
    name: 'Push Right',
    category: 'slide',
    description: 'Slide A pushes Slide B into view from the left.',
    defaultDuration: 0.6,
    icon: '➡️',
    keywords: ['push', 'right', 'classic'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'push-up-transition',
    name: 'Push Up',
    category: 'slide',
    description: 'Slide A pushes Slide B up into view from the bottom.',
    defaultDuration: 0.6,
    icon: '⬆️',
    keywords: ['push', 'up', 'classic'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'push-down-transition',
    name: 'Push Down',
    category: 'slide',
    description: 'Slide A pushes Slide B down into view from the top.',
    defaultDuration: 0.6,
    icon: '⬇️',
    keywords: ['push', 'down', 'classic'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'elastic-slide-transition',
    name: 'Elastic Slide',
    category: 'slide',
    description: 'Horizontal slide transition with spring bounce easing curves.',
    defaultDuration: 0.8,
    icon: '🪀',
    keywords: ['elastic', 'slide', 'bounce', 'spring'],
    direction: 'right',
    easing: 'elastic',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'smooth-push-transition',
    name: 'Smooth Push',
    category: 'slide',
    description: 'Push transition using custom slow-in slow-out speed paths.',
    defaultDuration: 0.7,
    icon: '🧼',
    keywords: ['smooth', 'push', 'slow-in'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 45,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'split-push-transition',
    name: 'Split Push',
    category: 'slide',
    description: 'Splits Clip A horizontally pushing halves in opposite directions.',
    defaultDuration: 0.8,
    icon: '✂️',
    keywords: ['split', 'push', 'horizontal'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dual-slide-transition',
    name: 'Dual Slide',
    category: 'slide',
    description: 'Slide A moves left while Slide B slides in from top.',
    defaultDuration: 0.7,
    icon: '🔗',
    keywords: ['dual', 'slide', 'horizontal', 'vertical'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'diagonal-slide-transition',
    name: 'Diagonal Slide',
    category: 'slide',
    description: 'Slides Clip A diagonally toward top-right coordinates.',
    defaultDuration: 0.7,
    icon: '↗️',
    keywords: ['diagonal', 'slide', 'angle'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cross-push-transition',
    name: 'Cross Push',
    category: 'slide',
    description: 'Pushes Clip B diagonally while sliding Clip A opposite.',
    defaultDuration: 0.7,
    icon: '✖️',
    keywords: ['cross', 'push', 'diagonal'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'swipe-left-transition',
    name: 'Swipe Left',
    category: 'slide',
    description: 'Clean swipe reveal moving left like a mobile page.',
    defaultDuration: 0.5,
    icon: '👈',
    keywords: ['swipe', 'left', 'reveal'],
    direction: 'left',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'swipe-right-transition',
    name: 'Swipe Right',
    category: 'slide',
    description: 'Clean swipe reveal moving right.',
    defaultDuration: 0.5,
    icon: '👉',
    keywords: ['swipe', 'right', 'reveal'],
    direction: 'right',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'swipe-up-transition',
    name: 'Swipe Up',
    category: 'slide',
    description: 'Clean swipe reveal moving up.',
    defaultDuration: 0.5,
    icon: '👆',
    keywords: ['swipe', 'up', 'reveal'],
    direction: 'up',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'swipe-down-transition',
    name: 'Swipe Down',
    category: 'slide',
    description: 'Clean swipe reveal moving down.',
    defaultDuration: 0.5,
    icon: '👇',
    keywords: ['swipe', 'down', 'reveal'],
    direction: 'down',
    easing: 'ease-out',
    intensity: 50,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'card-slide-transition',
    name: 'Card Slide',
    category: 'slide',
    description: 'Clip A scales down like a card, sliding out left.',
    defaultDuration: 0.7,
    icon: '🃏',
    keywords: ['card', 'slide', 'scale', 'deck'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'stack-slide-transition',
    name: 'Stack Slide',
    category: 'slide',
    description: 'Clip B slides in over Clip A like stacking deck cards.',
    defaultDuration: 0.7,
    icon: '🥞',
    keywords: ['stack', 'slide', 'deck'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'edge-push-transition',
    name: 'Edge Push',
    category: 'slide',
    description: 'Push transition restricted to border frames.',
    defaultDuration: 0.6,
    icon: '➖',
    keywords: ['edge', 'push', 'border'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'infinite-slide-transition',
    name: 'Infinite Slide',
    category: 'slide',
    description: 'Seamless horizontal loops sliding Clip A/B continuously.',
    defaultDuration: 1.0,
    icon: '♾️',
    keywords: ['infinite', 'slide', 'loop'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'ribbon-slide-transition',
    name: 'Ribbon Slide',
    category: 'slide',
    description: 'Splits viewport into three vertical ribbons sliding offsets.',
    defaultDuration: 0.8,
    icon: '🎀',
    keywords: ['ribbon', 'slide', 'stripes', 'split'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'perspective-push-transition',
    name: 'Perspective Push',
    category: 'slide',
    description: 'Pushes Clip B into place rotating along 3D Y-axis.',
    defaultDuration: 0.8,
    icon: '📐',
    keywords: ['perspective', 'push', '3d', 'rotate'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'gallery-slide-transition',
    name: 'Gallery Slide',
    category: 'slide',
    description: 'Zooms back scaling frames, sliding horizontally like a museum gallery.',
    defaultDuration: 0.9,
    icon: '🖼️',
    keywords: ['gallery', 'slide', 'museum', 'multi'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // SPIN & ROTATE TRANSITIONS (25)
  // ==========================================
  {
    id: 'spin-left-transition',
    name: 'Spin Left',
    category: 'spin',
    description: 'Rotates Clip A rapidly counter-clockwise fading into Clip B.',
    defaultDuration: 0.6,
    icon: '🔄',
    keywords: ['spin', 'left', 'rotate', 'ccw'],
    direction: 'ccw',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'spin-right-transition',
    name: 'Spin Right',
    category: 'spin',
    description: 'Rotates Clip A rapidly clockwise fading into Clip B.',
    defaultDuration: 0.6,
    icon: '🔄',
    keywords: ['spin', 'right', 'rotate', 'cw'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: '360-rotate-transition',
    name: '360 Rotate',
    category: 'spin',
    description: 'Full 360 degree Z-axis roll spin transition.',
    defaultDuration: 0.8,
    icon: '💫',
    keywords: ['360', 'rotate', 'spin', 'roll'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: '720-spin-transition',
    name: '720 Spin',
    category: 'spin',
    description: 'Double rotation spin for extreme speed transitions.',
    defaultDuration: 0.9,
    icon: '🌀',
    keywords: ['720', 'spin', 'double', 'fast'],
    direction: 'cw',
    easing: 'ease-in',
    intensity: 95,
    speed: 1.4,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cube-rotate-transition',
    name: 'Cube Rotate',
    category: 'spin',
    description: 'Rotates panels like a 3D geometry cube model.',
    defaultDuration: 0.8,
    icon: '📦',
    keywords: ['cube', '3d', 'rotate', 'box'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: '3d-flip-transition',
    name: '3D Flip',
    category: 'spin',
    description: 'Flips frames 180 degrees over along 3D space axes.',
    defaultDuration: 0.7,
    icon: '🔄',
    keywords: ['flip', '3d', 'axis', 'rotate'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'vertical-flip-transition',
    name: 'Vertical Flip',
    category: 'spin',
    description: '180 degree vertical rotation flip.',
    defaultDuration: 0.6,
    icon: '↕️',
    keywords: ['vertical', 'flip', 'rotate'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'horizontal-flip-transition',
    name: 'Horizontal Flip',
    category: 'spin',
    description: '180 degree horizontal rotation flip.',
    defaultDuration: 0.6,
    icon: '↔️',
    keywords: ['horizontal', 'flip', 'rotate'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'card-flip-transition',
    name: 'Card Flip',
    category: 'spin',
    description: 'Scales down and flips over like a game card asset.',
    defaultDuration: 0.7,
    icon: '🃏',
    keywords: ['card', 'flip', 'deck', '3d'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'page-flip-transition',
    name: 'Page Flip',
    category: 'spin',
    description: 'Simulates folding over a book page to reveal Clip B.',
    defaultDuration: 0.8,
    icon: '📖',
    keywords: ['page', 'flip', 'book', 'curl'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'roll-left-transition',
    name: 'Roll Left',
    category: 'spin',
    description: 'Translates left while rolling counter-clockwise.',
    defaultDuration: 0.7,
    icon: '🌀',
    keywords: ['roll', 'left', 'spin'],
    direction: 'ccw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'roll-right-transition',
    name: 'Roll Right',
    category: 'spin',
    description: 'Translates right while rolling clockwise.',
    defaultDuration: 0.7,
    icon: '🌀',
    keywords: ['roll', 'right', 'spin'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'clock-rotate-transition',
    name: 'Clock Rotate',
    category: 'spin',
    description: 'Segment sweep reveal mimicking clock hands.',
    defaultDuration: 0.8,
    icon: '🕒',
    keywords: ['clock', 'rotate', 'sweep', 'reveal'],
    direction: 'cw',
    easing: 'linear',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'counter-clock-rotate-transition',
    name: 'Counter Clock Rotate',
    category: 'spin',
    description: 'Counter-clockwise clock hand sweep reveal.',
    defaultDuration: 0.8,
    icon: '🕒',
    keywords: ['clock', 'rotate', 'sweep', 'ccw'],
    direction: 'ccw',
    easing: 'linear',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'barrel-roll-transition',
    name: 'Barrel Roll',
    category: 'spin',
    description: 'Full camera roll spin during forward zoom pushes.',
    defaultDuration: 0.9,
    icon: '💫',
    keywords: ['barrel', 'roll', 'zoom', 'spin'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 85,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'twist-rotate-transition',
    name: 'Twist Rotate',
    category: 'spin',
    description: 'Vortex twist distortion of pixels merging tracks.',
    defaultDuration: 0.7,
    icon: '🌀',
    keywords: ['twist', 'rotate', 'distortion'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'helix-spin-transition',
    name: 'Helix Spin',
    category: 'spin',
    description: 'Three-dimensional spiral spin scaling coordinates.',
    defaultDuration: 0.8,
    icon: '🧬',
    keywords: ['helix', 'spin', '3d', 'spiral'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'mirror-rotate-transition',
    name: 'Mirror Rotate',
    category: 'spin',
    description: 'Symmetrical mirrored rotates splitting quadrants.',
    defaultDuration: 0.7,
    icon: '🪞',
    keywords: ['mirror', 'rotate', 'quadrant'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'fold-rotate-transition',
    name: 'Fold Rotate',
    category: 'spin',
    description: 'Folds Clip A back in 3D perspective to reveal Clip B.',
    defaultDuration: 0.8,
    icon: '📁',
    keywords: ['fold', 'rotate', '3d', 'perspective'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'book-flip-transition',
    name: 'Book Flip',
    category: 'spin',
    description: 'Book style page turn flipping from center binding Y-axis.',
    defaultDuration: 0.8,
    icon: '📖',
    keywords: ['book', 'flip', 'page', '3d'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cylinder-rotate-transition',
    name: 'Cylinder Rotate',
    category: 'spin',
    description: 'Wraps clips around a 3D cylindrical shape rotating.',
    defaultDuration: 0.9,
    icon: '🛢️',
    keywords: ['cylinder', 'rotate', '3d'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'wheel-spin-transition',
    name: 'Wheel Spin',
    category: 'spin',
    description: 'Rotates coordinate frames like a spinning wheel.',
    defaultDuration: 0.7,
    icon: '🎡',
    keywords: ['wheel', 'spin', 'rotate'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'orbit-rotate-transition',
    name: 'Orbit Rotate',
    category: 'spin',
    description: 'Combines coordinate panning sweep with Z-axis tilt rolls.',
    defaultDuration: 0.8,
    icon: '🔄',
    keywords: ['orbit', 'rotate', 'pan', 'roll'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'portal-spin-transition',
    name: 'Portal Spin',
    category: 'spin',
    description: 'Swirling zoom-in spin vortex transition.',
    defaultDuration: 0.8,
    icon: '🌀',
    keywords: ['portal', 'spin', 'vortex', 'zoom'],
    direction: 'cw',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'infinity-spin-transition',
    name: 'Infinity Spin',
    category: 'spin',
    description: 'Continuous rolling rotation looping seamlessly.',
    defaultDuration: 1.0,
    icon: '♾️',
    keywords: ['infinity', 'spin', 'loop', 'roll'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // BLUR & MOTION TRANSITIONS (25)
  // ==========================================
  {
    id: 'motion-blur-transition',
    name: 'Motion Blur',
    category: 'blur',
    description: 'Applies directional velocity smearing matching movement angles.',
    defaultDuration: 0.6,
    icon: '🏃',
    keywords: ['motion', 'blur', 'smear', 'velocity'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'gaussian-blur-transition',
    name: 'Gaussian Blur',
    category: 'blur',
    description: 'Standard mathematical blur spreading pixel values evenly.',
    defaultDuration: 0.7,
    icon: '🌫️',
    keywords: ['gaussian', 'blur', 'soft'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'directional-blur-transition',
    name: 'Directional Blur',
    category: 'blur',
    description: 'Linear blur smearing details along specific angle boundaries.',
    defaultDuration: 0.6,
    icon: '↗️',
    keywords: ['directional', 'blur', 'angle', 'smear'],
    direction: 'up',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'radial-blur-transition',
    name: 'Radial Blur',
    category: 'blur',
    description: 'Circular rotational blur spinning from pivot centers.',
    defaultDuration: 0.7,
    icon: '🌀',
    keywords: ['radial', 'blur', 'circular', 'spin'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'lens-blur-transition',
    name: 'Lens Blur',
    category: 'blur',
    description: 'Defocused lens simulation rendering iris shapes on highlights.',
    defaultDuration: 0.8,
    icon: '👓',
    keywords: ['lens', 'blur', 'bokeh', 'camera'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'speed-blur-transition',
    name: 'Speed Blur',
    category: 'blur',
    description: 'Intense directional smear matched with fast position jumps.',
    defaultDuration: 0.5,
    icon: '⚡',
    keywords: ['speed', 'blur', 'fast', 'smear'],
    direction: 'right',
    easing: 'ease-in',
    intensity: 80,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dream-blur-transition',
    name: 'Dream Blur',
    category: 'blur',
    description: 'Soft glow overlay blended with high-radius gaussian blur.',
    defaultDuration: 0.9,
    icon: '💭',
    keywords: ['dream', 'blur', 'glow', 'soft'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 45,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'background-blur-transition',
    name: 'Background Blur',
    category: 'blur',
    description: 'Blurs everything except the key foreground subject.',
    defaultDuration: 0.7,
    icon: '👤',
    keywords: ['background', 'blur', 'portrait'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'bokeh-blur-transition',
    name: 'Bokeh Blur',
    category: 'blur',
    description: 'Renders circle-of-confusion light shapes on dark areas.',
    defaultDuration: 0.8,
    icon: '⭐',
    keywords: ['bokeh', 'blur', 'lights', 'glow'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'focus-blur-transition',
    name: 'Focus Blur',
    category: 'blur',
    description: 'Fades from fully blurry to sharp focus coordinates.',
    defaultDuration: 0.7,
    icon: '🎯',
    keywords: ['focus', 'blur', 'sharp'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-flash-transition',
    name: 'Blur Flash',
    category: 'blur',
    description: 'Sudden high exposure blur pulse mimicking intense light flashes.',
    defaultDuration: 0.4,
    icon: '⚡',
    keywords: ['flash', 'blur', 'white', 'bright'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 85,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-fade-transition',
    name: 'Blur Fade',
    category: 'blur',
    description: 'Soft crossfade transition moving from blur to clear.',
    defaultDuration: 0.8,
    icon: '🕯️',
    keywords: ['fade', 'blur', 'soft', 'clear'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 40,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-stretch-transition',
    name: 'Blur Stretch',
    category: 'blur',
    description: 'Elongated directional smear stretching coordinates.',
    defaultDuration: 0.6,
    icon: '↗️',
    keywords: ['stretch', 'blur', 'direction', 'smear'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-burst-transition',
    name: 'Blur Burst',
    category: 'blur',
    description: 'Radial explosion style blur expanding dynamically.',
    defaultDuration: 0.5,
    icon: '🔎',
    keywords: ['burst', 'blur', 'radial', 'explosion'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.4,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-ripple-transition',
    name: 'Blur Ripple',
    category: 'blur',
    description: 'Circular ripple waves displacing and smearing pixel lines.',
    defaultDuration: 0.7,
    icon: '🌊',
    keywords: ['ripple', 'blur', 'water', 'wave'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-wave-transition',
    name: 'Blur Wave',
    category: 'blur',
    description: 'Wavy air distortion refracting background pixels.',
    defaultDuration: 0.8,
    icon: '💨',
    keywords: ['wave', 'distortion', 'heat', 'blur'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-orbit-transition',
    name: 'Blur Orbit',
    category: 'blur',
    description: 'Circular orbital smearing rotating around subjects.',
    defaultDuration: 0.8,
    icon: '🔄',
    keywords: ['orbit', 'blur', 'spin', 'circular'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-tunnel-transition',
    name: 'Blur Tunnel',
    category: 'blur',
    description: 'Zoom perspective blur drawing viewer focus inward.',
    defaultDuration: 0.8,
    icon: '🔎',
    keywords: ['tunnel', 'blur', 'zoom', 'inward'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-spin-transition',
    name: 'Blur Spin',
    category: 'blur',
    description: 'Quick rotational spin blurs on the Z-axis.',
    defaultDuration: 0.6,
    icon: '💫',
    keywords: ['spin', 'blur', 'rotate', 'roll'],
    direction: 'cw',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'blur-drift-transition',
    name: 'Blur Drift',
    category: 'blur',
    description: 'Gradual linear shifts in directional smearing.',
    defaultDuration: 0.9,
    icon: '🏃',
    keywords: ['drift', 'blur', 'smear'],
    direction: 'left',
    easing: 'ease-in-out',
    intensity: 45,
    speed: 0.8,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'velocity-blur-transition',
    name: 'Velocity Blur',
    category: 'blur',
    description: 'Speed-ramped smearing that accelerates to max at cut point.',
    defaultDuration: 0.6,
    icon: '⚡',
    keywords: ['velocity', 'blur', 'speed', 'ramp'],
    direction: 'right',
    easing: 'ease-in',
    intensity: 75,
    speed: 1.4,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'optical-blur-transition',
    name: 'Optical Blur',
    category: 'blur',
    description: 'Simulates high-end optical glass lens defocus changes.',
    defaultDuration: 0.7,
    icon: '👓',
    keywords: ['optical', 'lens', 'blur', 'glass'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'glass-blur-transition',
    name: 'Glass Blur',
    category: 'blur',
    description: 'Frosted window pane glass refraction smearing pixels.',
    defaultDuration: 0.7,
    icon: '🖼️',
    keywords: ['glass', 'frosted', 'blur'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'crystal-blur-transition',
    name: 'Crystal Blur',
    category: 'blur',
    description: 'Refracts details through crystal geometry blocks.',
    defaultDuration: 0.7,
    icon: '💎',
    keywords: ['crystal', 'prism', 'refraction', 'blur'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cinematic-blur-transition',
    name: 'Cinematic Blur',
    category: 'blur',
    description: 'Premium anamorphic lens blur styling with oval bokeh shapes.',
    defaultDuration: 0.9,
    icon: '🎬',
    keywords: ['cinematic', 'anamorphic', 'blur', 'oval'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // GLITCH & DIGITAL TRANSITIONS (25)
  // ==========================================
  {
    id: 'rgb-split-transition',
    name: 'RGB Split',
    category: 'glitch',
    description: 'Chromatic aberration offsets splitting color channels.',
    defaultDuration: 0.5,
    icon: '🌈',
    keywords: ['rgb', 'split', 'aberration', 'color'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.3,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'digital-glitch-transition',
    name: 'Digital Glitch',
    category: 'glitch',
    description: 'Blocky digital compression noise and sorting artifacts.',
    defaultDuration: 0.5,
    icon: '🖥️',
    keywords: ['digital', 'glitch', 'compression', 'blocks'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 80,
    speed: 1.4,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'pixel-glitch-transition',
    name: 'Pixel Glitch',
    category: 'glitch',
    description: 'Mosaic block pixelations shuffling spatial coordinates.',
    defaultDuration: 0.5,
    icon: '👾',
    keywords: ['pixel', 'glitch', 'mosaic', 'squares'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 75,
    speed: 1.4,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'tv-static-transition',
    name: 'TV Static',
    category: 'glitch',
    description: 'Salt-and-pepper analog static overlay blocking out details.',
    defaultDuration: 0.6,
    icon: '🌫️',
    keywords: ['static', 'noise', 'tv', 'analog'],
    direction: 'none',
    easing: 'linear',
    intensity: 85,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'signal-loss-transition',
    name: 'Signal Loss',
    category: 'glitch',
    description: 'Flashes system color bars indicating loss of signal feed.',
    defaultDuration: 0.5,
    icon: '📳',
    keywords: ['signal', 'loss', 'colorbar', 'offline'],
    direction: 'none',
    easing: 'linear',
    intensity: 90,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'vhs-glitch-transition',
    name: 'VHS Glitch',
    category: 'glitch',
    description: 'Analog tape tracking tear lines and horizontal sync drops.',
    defaultDuration: 0.6,
    icon: '📼',
    keywords: ['vhs', 'tape', 'tracking', 'analog'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'analog-glitch-transition',
    name: 'Analog Glitch',
    category: 'glitch',
    description: 'Continuous wavy lines representing antenna signal drift.',
    defaultDuration: 0.6,
    icon: '📻',
    keywords: ['analog', 'glitch', 'antenna', 'wavy'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'data-corruption-transition',
    name: 'Data Corruption',
    category: 'glitch',
    description: 'Raw binary byte blocks flashing randomly on frame junctions.',
    defaultDuration: 0.5,
    icon: '💾',
    keywords: ['data', 'corruption', 'bytes', 'warning'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'frame-skip-transition',
    name: 'Frame Skip',
    category: 'glitch',
    description: 'Simulates dropped rendering cycles causing stutters.',
    defaultDuration: 0.4,
    icon: '⏳',
    keywords: ['skip', 'frame', 'drop', 'stutter'],
    direction: 'none',
    easing: 'linear',
    intensity: 60,
    speed: 1.6,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'screen-tear-transition',
    name: 'Screen Tear',
    category: 'glitch',
    description: 'Horizontal line splits representing buffer mismatches.',
    defaultDuration: 0.5,
    icon: '✂️',
    keywords: ['tear', 'screen', 'buffer', 'split'],
    direction: 'none',
    easing: 'linear',
    intensity: 75,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'broken-screen-transition',
    name: 'Broken Screen',
    category: 'glitch',
    description: 'Overlay grid of cracked glass patterns refracting backgrounds.',
    defaultDuration: 0.7,
    icon: '⚠️',
    keywords: ['broken', 'screen', 'crack', 'glass'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 80,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'neural-glitch-transition',
    name: 'Neural Glitch',
    category: 'glitch',
    description: 'Deepdream styling and hallucinatory pattern shifts.',
    defaultDuration: 0.8,
    icon: '🧠',
    keywords: ['neural', 'ai', 'hallucination', 'dream'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'ai-corruption-transition',
    name: 'AI Corruption',
    category: 'glitch',
    description: 'Abstract visual feedback artifacts from deep models.',
    defaultDuration: 0.8,
    icon: '🦾',
    keywords: ['ai', 'corruption', 'errors'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cyber-error-transition',
    name: 'Cyber Error',
    category: 'glitch',
    description: 'Red alert screen overlay flashing with terminal panels.',
    defaultDuration: 0.6,
    icon: '🚨',
    keywords: ['cyber', 'error', 'terminal', 'warning'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'system-failure-transition',
    name: 'System Failure',
    category: 'glitch',
    description: 'Flashes OS crash layouts before bringing Clip B online.',
    defaultDuration: 0.6,
    icon: '🔌',
    keywords: ['system', 'failure', 'bsod', 'crash'],
    direction: 'none',
    easing: 'linear',
    intensity: 85,
    speed: 1.3,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'gpu-crash-transition',
    name: 'GPU Crash',
    category: 'glitch',
    description: 'Extreme vector rendering errors bending geometry paths.',
    defaultDuration: 0.5,
    icon: '🔌',
    keywords: ['gpu', 'crash', 'rendering', 'vector'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'hologram-glitch-transition',
    name: 'Hologram Glitch',
    category: 'glitch',
    description: 'Glowing sci-fi HUD scanlines flickering.',
    defaultDuration: 0.7,
    icon: '🤖',
    keywords: ['hologram', 'hud', 'scan', 'sci-fi'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'code-collapse-transition',
    name: 'Code Collapse',
    category: 'glitch',
    description: 'Vertical matrix style command line scrolls.',
    defaultDuration: 0.8,
    icon: '💻',
    keywords: ['code', 'collapse', 'matrix', 'terminal'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'pixel-storm-transition',
    name: 'Pixel Storm',
    category: 'glitch',
    description: 'Dense cloud of shifting coordinate block noises.',
    defaultDuration: 0.6,
    icon: '👾',
    keywords: ['pixel', 'storm', 'noise', 'blocks'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 80,
    speed: 1.4,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'digital-pulse-transition',
    name: 'Digital Pulse',
    category: 'glitch',
    description: 'Pulsates horizontal offset lines synced with transitions.',
    defaultDuration: 0.6,
    icon: '💓',
    keywords: ['digital', 'pulse', 'offset'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'error-wave-transition',
    name: 'Error Wave',
    category: 'glitch',
    description: 'Wave displacement sweeps scrolling down the viewport.',
    defaultDuration: 0.6,
    icon: '🌊',
    keywords: ['error', 'wave', 'ripple', 'displace'],
    direction: 'none',
    easing: 'linear',
    intensity: 75,
    speed: 1.2,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'rgb-storm-transition',
    name: 'RGB Storm',
    category: 'glitch',
    description: 'Heavy chromatic shifts switching directions rapidly.',
    defaultDuration: 0.5,
    icon: '⛈️',
    keywords: ['rgb', 'storm', 'chromatic', 'split'],
    direction: 'right',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'memory-error-transition',
    name: 'Memory Error',
    category: 'glitch',
    description: 'Temporary memory buffer overlays showing ghost frames.',
    defaultDuration: 0.8,
    icon: '💾',
    keywords: ['memory', 'buffer', 'leak', 'ghost'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'future-glitch-transition',
    name: 'Future Glitch',
    category: 'glitch',
    description: 'High-tech grid scans and vector displacements.',
    defaultDuration: 0.7,
    icon: '🤖',
    keywords: ['future', 'glitch', 'sci-fi', 'hud'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.1,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'quantum-glitch-transition',
    name: 'Quantum Glitch',
    category: 'glitch',
    description: 'Atomic scale noise splits separating light values.',
    defaultDuration: 0.5,
    icon: '⚛️',
    keywords: ['quantum', 'glitch', 'atomic', 'split'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.5,
    motionBlur: true,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },

  // ==========================================
  // CINEMATIC & LIGHT TRANSITIONS (25)
  // ==========================================
  {
    id: 'light-leak-transition',
    name: 'Light Leak',
    category: 'light',
    description: 'Simulates analog film stock exposure to stray light rays.',
    defaultDuration: 0.8,
    icon: '🕯️',
    keywords: ['light', 'leak', 'film', 'analog'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'lens-flare-transition',
    name: 'Lens Flare',
    category: 'light',
    description: 'Classic multi-element ring flare sweep from bright sources.',
    defaultDuration: 0.7,
    icon: '✨',
    keywords: ['lens', 'flare', 'bokeh', 'camera'],
    direction: 'right',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'film-burn-transition',
    name: 'Film Burn',
    category: 'light',
    description: 'Warm organic light burns melting frames at junction.',
    defaultDuration: 0.6,
    icon: '🔥',
    keywords: ['film', 'burn', 'analog', 'melt'],
    direction: 'none',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'glow-flash-transition',
    name: 'Glow Flash',
    category: 'light',
    description: 'Sudden high exposure flash blending clips in ambient glows.',
    defaultDuration: 0.5,
    icon: '🌟',
    keywords: ['glow', 'flash', 'bright', 'fade'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 75,
    speed: 1.3,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'bloom-reveal-transition',
    name: 'Bloom Reveal',
    category: 'light',
    description: 'Feathers bright highlights to bleed over darker areas.',
    defaultDuration: 0.8,
    icon: '🌸',
    keywords: ['bloom', 'reveal', 'glow', 'soft'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'golden-flash-transition',
    name: 'Golden Flash',
    category: 'light',
    description: 'Warm amber-gold exposure sweep covering change points.',
    defaultDuration: 0.5,
    icon: '🪙',
    keywords: ['golden', 'flash', 'warm', 'glow'],
    direction: 'none',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'sun-rays-transition',
    name: 'Sun Rays',
    category: 'light',
    description: 'Beams of golden light streaming down across viewport.',
    defaultDuration: 0.8,
    icon: '☀️',
    keywords: ['sun', 'rays', 'golden', 'shafts'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'spotlight-transition',
    name: 'Spotlight',
    category: 'light',
    description: 'Circular cone of bright spotlight focus lighting.',
    defaultDuration: 0.7,
    icon: '🔦',
    keywords: ['spotlight', 'light', 'cone', 'focus'],
    direction: 'center',
    easing: 'ease-in-out',
    intensity: 70,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'god-rays-transition',
    name: 'God Rays',
    category: 'light',
    description: 'Epic crepuscular shafts of light drawing drama.',
    defaultDuration: 0.9,
    icon: '⛪',
    keywords: ['god', 'rays', 'shafts', 'sky'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 75,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'aurora-glow-transition',
    name: 'Aurora Glow',
    category: 'light',
    description: 'Wavy green and purple northern light glows.',
    defaultDuration: 1.0,
    icon: '🌌',
    keywords: ['aurora', 'glow', 'northern', 'lights'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'neon-glow-transition',
    name: 'Neon Glow',
    category: 'light',
    description: 'Vibrant electric cyber glow outlines scaling up.',
    defaultDuration: 0.7,
    icon: '🚨',
    keywords: ['neon', 'glow', 'cyber', 'electric'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 70,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'rainbow-light-transition',
    name: 'Rainbow Light',
    category: 'light',
    description: 'Prismatic spectral refraction stripes crossing the frame.',
    defaultDuration: 0.8,
    icon: '🌈',
    keywords: ['rainbow', 'spectral', 'refraction', 'stripes'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'reflection-flash-transition',
    name: 'Reflection Flash',
    category: 'light',
    description: 'Water-like specular light bounces flashing upwards.',
    defaultDuration: 0.6,
    icon: '🌊',
    keywords: ['reflection', 'flash', 'water', 'specular'],
    direction: 'up',
    easing: 'ease-out',
    intensity: 70,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'prism-light-transition',
    name: 'Prism Light',
    category: 'light',
    description: 'Rainbow chromatic dispersion bands surrounding details.',
    defaultDuration: 0.7,
    icon: '💎',
    keywords: ['prism', 'light', 'dispersion', 'chromatic'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 1.1,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'volumetric-light-transition',
    name: 'Volumetric Light',
    category: 'light',
    description: 'Gives the feel of light rays catching floating dust particles.',
    defaultDuration: 0.8,
    icon: '🌫️',
    keywords: ['volumetric', 'light', 'rays', 'particles'],
    direction: 'down',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'halo-glow-transition',
    name: 'Halo Glow',
    category: 'light',
    description: 'Concentric halo light rings expanding outwards.',
    defaultDuration: 0.7,
    icon: '😇',
    keywords: ['halo', 'glow', 'rings', 'circular'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 65,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'energy-burst-transition',
    name: 'Energy Burst',
    category: 'light',
    description: 'Rapid explosive flash of electric blue energy levels.',
    defaultDuration: 0.5,
    icon: '⚡',
    keywords: ['energy', 'burst', 'electric', 'flash'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 85,
    speed: 1.4,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'magic-glow-transition',
    name: 'Magic Glow',
    category: 'light',
    description: 'Stylized sparkles and pink highlight blooms.',
    defaultDuration: 0.8,
    icon: '🪄',
    keywords: ['magic', 'glow', 'sparkles', 'pink'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 55,
    speed: 1.0,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'luxury-reveal-transition',
    name: 'Luxury Reveal',
    category: 'light',
    description: 'Smooth gradient wipes combined with golden highlight levels.',
    defaultDuration: 0.9,
    icon: '👑',
    keywords: ['luxury', 'reveal', 'gold', 'smooth'],
    direction: 'right',
    easing: 'ease-in-out',
    intensity: 60,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'cinema-bloom-transition',
    name: 'Cinema Bloom',
    category: 'light',
    description: 'Anamorphic highlight lens flares blending tracks.',
    defaultDuration: 0.9,
    icon: '🎬',
    keywords: ['cinema', 'bloom', 'anamorphic', 'lens'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 65,
    speed: 0.9,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'light-explosion-transition',
    name: 'Light Explosion',
    category: 'light',
    description: 'Concentric shockwaves of blinding light blending frames.',
    defaultDuration: 0.5,
    icon: '💥',
    keywords: ['light', 'explosion', 'shockwave', 'blinding'],
    direction: 'center',
    easing: 'ease-in',
    intensity: 90,
    speed: 1.5,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'soft-glow-transition',
    name: 'Soft Glow',
    category: 'light',
    description: 'Low intensity exposure bloom curve.',
    defaultDuration: 0.8,
    icon: '🌸',
    keywords: ['soft', 'glow', 'exposure'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 45,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'white-burst-transition',
    name: 'White Burst',
    category: 'light',
    description: 'High-speed exposure flash scaling Clip B forward.',
    defaultDuration: 0.4,
    icon: '⚪',
    keywords: ['white', 'burst', 'exposure', 'zoom'],
    direction: 'center',
    easing: 'ease-out',
    intensity: 80,
    speed: 1.3,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'dream-light-transition',
    name: 'Dream Light',
    category: 'light',
    description: 'Soft mist-light filter with golden glow warmness.',
    defaultDuration: 1.0,
    icon: '💭',
    keywords: ['dream', 'light', 'mist', 'golden'],
    direction: 'none',
    easing: 'ease-in-out',
    intensity: 50,
    speed: 0.8,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  },
  {
    id: 'hollywood-flash-transition',
    name: 'Hollywood Flash',
    category: 'light',
    description: 'Cinema lens flare sweeps combined with highlight whiteouts.',
    defaultDuration: 0.6,
    icon: '🌟',
    keywords: ['hollywood', 'flash', 'flare', 'lens'],
    direction: 'right',
    easing: 'ease-out',
    intensity: 85,
    speed: 1.2,
    motionBlur: false,
    gpuOptimized: true,
    realtimePreview: true,
    timelineCompatible: true,
    exportCompatible: true
  }
];
