import { EffectItem } from '../components/EffectGrid';

export const SMOKE_EFFECTS: EffectItem[] = [
  { id: 'atmospheric-smoke', name: 'Atmospheric Smoke', description: 'Low intensity general smoke volume to catch spotlight beams.', icon: '🌌' },
  { id: 'black-smoke', name: 'Black Smoke', description: 'Dense dark carbon clouds representing burning synthetic fuel.', icon: '⚫' },
  { id: 'blue-smoke', name: 'Blue Smoke', description: 'Electric blue desaturated smoke clouds scrolling across.', icon: '🔵', isNew: true },
  { id: 'cinematic-atmosphere', name: 'Cinematic Atmosphere', description: 'Subtle ambient haze overlay mapping soft light ranges.', icon: '🌫️', isNew: true },
  { id: 'cinematic-fog', name: 'Cinematic Fog', description: 'Evenly distributed soft fog layers adding depth to outdoor scenes.', icon: '🌫️' },
  { id: 'cloud-smoke', name: 'Cloud Smoke', description: 'Puffy cotton-like smoke shapes floating across the screen.', icon: '☁️' },
  { id: 'colored-vapor', name: 'Colored Vapor', description: 'Dynamic shifting multi-color vapor clouds.', icon: '🌈', isNew: true },
  { id: 'dense-atmosphere', name: 'Dense Atmosphere', description: 'Thick heavy mist layering overall details heavily.', icon: '🌫️', isNew: true },
  { id: 'dream-fog', name: 'Dream Fog', description: 'Dreamy low contrast white fog with soft highlight glow leaks.', icon: '💭', isNew: true },
  { id: 'dry-ice-fog', name: 'Dry Ice Fog', description: 'Thick heavy white fog rolling low across viewport ground.', icon: '🧊' },
  { id: 'dust-cloud', name: 'Dust Cloud', description: 'Brown dry soil dust storm gusting horizontally.', icon: '🏜️' },
  { id: 'electric-smoke', name: 'Electric Smoke', description: 'Flickering sparks discharge inside thin white smoke drifts.', icon: '⚡', isNew: true },
  { id: 'explosion-smoke', name: 'Explosion Smoke', description: 'Sudden high-velocity puff of grey-black expansion smoke.', icon: '💥' },
  { id: 'fire-smoke-pro', name: 'Fire Smoke Pro', description: 'Carbon black smoke with embedded rising spark overlays.', icon: '🔥', isNew: true },
  { id: 'ghost-smoke', name: 'Ghost Smoke', description: 'Wispy translucent green smoke drifting like spectres.', icon: '👻', isNew: true },
  { id: 'ground-mist', name: 'Ground Mist', description: 'Soft thin fog crawling low across screen borders.', icon: '🌫️', isNew: true },
  { id: 'haunted-smoke', name: 'Haunted Smoke', description: 'Moody dark smoke whisps framing the viewport edges.', icon: '🐈', isNew: true },
  { id: 'horror-fog', name: 'Horror Fog', description: 'Dense cold grey mist reducing contrast and details for spooky look.', icon: '💀', isNew: true },
  { id: 'ice-smoke', name: 'Ice Smoke', description: 'Freezing blue vapor sweeps condensing in frozen lines.', icon: '❄️', isNew: true },
  { id: 'infinity-smoke', name: 'Infinity Smoke', description: 'Seamless looping continuous drifting thick smoke clouds.', icon: '♾️', isNew: true },
  { id: 'magic-smoke', name: 'Magic Smoke', description: 'Stylized colorful purple/pink smoke trails.', icon: '🔮' },
  { id: 'magic-vapor', name: 'Magic Vapor', description: 'Vibrant color-grading gas trails following movement pathways.', icon: '🪄', isNew: true },
  { id: 'mist-effect', name: 'Mist Effect', description: 'Subtle damp air particle volume reducing contrast soft.', icon: '🌸' },
  { id: 'mystic-mist', name: 'Mystic Mist', description: 'Prismatic shifting light rays breaking through light fog overlays.', icon: '🔮', isNew: true },
  { id: 'neon-smoke', name: 'Neon Smoke', description: 'Self-illuminated neon gas clouds scrolling vertically.', icon: '🚨', isNew: true },
  { id: 'phantom-fog', name: 'Phantom Fog', description: 'Dynamic shifting outline shapes appearing inside gray fog.', icon: '👻', isNew: true },
  { id: 'purple-smoke', name: 'Purple Smoke', description: 'Rich magenta/violet stylized smoke streams.', icon: '🟣', isNew: true },
  { id: 'rainbow-smoke', name: 'Rainbow Smoke', description: 'Continuous spectrum shifts coloring vertical smoke jets.', icon: '🌈', isNew: true },
  { id: 'red-smoke', name: 'Red Smoke', description: 'Stylized ruby-red warning smoke sweeps.', icon: '🔴', isNew: true },
  { id: 'shadow-smoke', name: 'Shadow Smoke', description: 'Moody dark black vignette wisps.', icon: '⚫', isNew: true },
  { id: 'sky-fog', name: 'Sky Fog', description: 'Fades top viewport borders out into clean white mist.', icon: '☁️', isNew: true },
  { id: 'smoke-burst', name: 'Smoke Burst', description: 'Quick puff of white smoke from the center screen.', icon: '💨' },
  { id: 'smoke-drift', name: 'Smoke Drift', description: 'Gentle horizontal wind sweep of thin white smoke.', icon: '💨' },
  { id: 'smoke-fade', name: 'Smoke Fade', description: 'Slow fading whiteout transition blending tracks.', icon: '🕯️' },
  { id: 'smoke-overlay', name: 'Smoke Overlay', description: 'Continuous floating overlay of thin atmospheric fog.', icon: '🌫️' },
  { id: 'smoke-ring', name: 'Smoke Ring', description: 'Renders circular smoke puffs expanding outwards from coordinates.', icon: '⭕', isNew: true },
  { id: 'smoke-swirl', name: 'Smoke Swirl', description: 'Soft spiral vortices rotating slowly around center screen.', icon: '🌀', isNew: true },
  { id: 'smoke-tornado', name: 'Smoke Tornado', description: 'Aggressive vertical smoke vortex swirling up.', icon: '🌪️', isNew: true },
  { id: 'smoke-trail', name: 'Smoke Trail', description: 'Smeared white smoke trace behind tracking speed objects.', icon: '🏃' },
  { id: 'steam-effect', name: 'Steam Effect', description: 'Hot water vapor shooting upwards from bottom vents.', icon: '♨️' },
  { id: 'thick-smoke', name: 'Thick Smoke', description: 'Highly opaque gray volume blocking viewport details.', icon: '🎛️' },
  { id: 'thin-smoke', name: 'Thin Smoke', description: 'Semi-transparent soft whisps drifting randomly.', icon: '💨' },
  { id: 'toxic-smoke', name: 'Toxic Smoke', description: 'Luminous green/yellow chemical fog warning.', icon: '☣️' },
  { id: 'vapor-effect', name: 'Vapor Effect', description: 'Dry aerosol mist spray spreading out.', icon: '💨' },
  { id: 'white-smoke', name: 'White Smoke', description: 'Standard high-brightness steam/condensation puffs.', icon: '⚪' }
];
