import { EffectItem } from '../components/EffectGrid';

export const CAMERA_EFFECTS: EffectItem[] = [
  { id: 'action-stabilizer', name: 'Action Stabilizer', description: 'Smooths out erratic movement while preserving dynamic tracking velocity.', icon: '🏃', isNew: true },
  { id: 'action-tracking', name: 'Action Tracking', description: 'Keeps rapid movements locked and centered in frame.', icon: '🚶', isNew: true },
  { id: 'camera-drift-pro', name: 'Camera Drift Pro', description: 'High-end organic landscape drift with multi-axis sway coefficients.', icon: 'Sw', isNew: true },
  { id: 'camera-jitter', name: 'Camera Jitter', description: 'Irregular position jumps for fast action sequences.', icon: '🗯️' },
  { id: 'camera-pan-left', name: 'Camera Pan Left', description: 'Rotational panning sweep moving viewport focus left.', icon: '⬅️' },
  { id: 'camera-pan-right', name: 'Camera Pan Right', description: 'Rotational panning sweep moving viewport focus right.', icon: '➡️' },
  { id: 'camera-roll', name: 'Camera Roll', description: 'Tilts the camera landscape angle left/right.', icon: '📐' },
  { id: 'camera-shake', name: 'Camera Shake', description: 'High frequency shake representing impacts, steps, or rumble.', icon: '📳' },
  { id: 'camera-spin', name: 'Camera Spin', description: 'Quick rotational spin transitions on the Z-axis.', icon: '💫' },
  { id: 'camera-tilt-down', name: 'Camera Tilt Down', description: 'Vertical pivot rotation looking downward.', icon: '⬇️' },
  { id: 'camera-tilt-up', name: 'Camera Tilt Up', description: 'Vertical pivot rotation looking upward.', icon: '⬆️' },
  { id: 'cinematic-handheld-pro', name: 'Cinematic Handheld Pro', description: 'Simulates heavy professional cinema camera physics and sway.', icon: '📽️', isNew: true },
  { id: 'cinematic-roll-new', name: 'Cinematic Roll', description: 'Continuous Dutch angle roll for high-drama scenes.', icon: '📐', isNew: true },
  { id: 'cinematic-zoom', name: 'Cinematic Zoom', description: 'Slow dramatic zoom in matching widescreen films.', icon: '📽️' },
  { id: 'crane-drop', name: 'Crane Drop', description: 'Vertical boom down camera movement revealing subjects from high angles.', icon: '🪝', isNew: true },
  { id: 'crane-lift', name: 'Crane Lift', description: 'Vertical boom up camera movement elevating viewport over settings.', icon: '🏗️', isNew: true },
  { id: 'crash-zoom', name: 'Crash Zoom', description: 'Rapid focal length magnification for quick visual punch-ins.', icon: '💥' },
  { id: 'dolly-zoom', name: 'Dolly Zoom', description: 'Vertigo effect warping focal length while tracking reverse coordinates.', icon: '🌀' },
  { id: 'drone-flyover', name: 'Drone Flyover', description: 'Simulates clean high-altitude aerial forward camera travel.', icon: '✈️', isNew: true },
  { id: 'drone-orbit', name: 'Drone Orbit', description: 'Circular orbital flyby tracing subjects with smooth bank rotation.', icon: '🔄', isNew: true },
  { id: 'dynamic-camera', name: 'Dynamic Camera', description: 'Combines hand movements and zooms automatically.', icon: '🎢' },
  { id: 'dynamic-framing', name: 'Dynamic Framing', description: 'Intelligent viewport scaling that adjusts framing based on subject bounds.', icon: '🖼️', isNew: true },
  { id: 'dynamic-push', name: 'Dynamic Push', description: 'Slow forward translation that speeds up on hits.', icon: '🔎', isNew: true },
  { id: 'follow-camera', name: 'Follow Camera', description: 'Locks viewport movement offsets relative to subjects.', icon: '🏃' },
  { id: 'focus-breathing', name: 'Focus Breathing', description: 'Recreates optical elements shifting during heavy rack focus sweeps.', icon: '👁️', isNew: true },
  { id: 'fpv-dive', name: 'FPV Dive', description: 'Recreates a high-speed vertical nose dive path using FPV drones.', icon: '🪂', isNew: true },
  { id: 'fpv-spin', name: 'FPV Spin', description: '360 degree rotational drone flip transition.', icon: '💫', isNew: true },
  { id: 'gimbal-follow', name: 'Gimbal Follow', description: 'Highly damped tracking camera following subjects smoothly.', icon: '🎠', isNew: true },
  { id: 'handheld-camera', name: 'Handheld Camera', description: 'Simulates organic human hand tremors and soft drift sway.', icon: '🤳' },
  { id: 'horizon-lock', name: 'Horizon Lock', description: 'Staggering camera shakes while keeping horizon perfectly level.', icon: '➖', isNew: true },
  { id: 'hyper-zoom', name: 'Hyper Zoom', description: 'Super fast visual punch-in exceeding standard crash zooms.', icon: '💥', isNew: true },
  { id: 'lens-compression', name: 'Lens Compression', description: 'Simulates telephoto lens compression narrowing background depth.', icon: '🔍', isNew: true },
  { id: 'lens-focus', name: 'Lens Focus', description: 'Simulates lens autofocus hunting and correction.', icon: '👁️' },
  { id: 'micro-camera-shake', name: 'Micro Camera Shake', description: 'High frequency tiny vibrations mimicking engine rumble.', icon: '📳', isNew: true },
  { id: 'orbit-camera', name: 'Orbit Camera', description: 'Circular orbital track path around center focus points.', icon: '🔄' },
  { id: 'precision-dolly', name: 'Precision Dolly', description: 'Dolly tracking moving parallel to subjects on a smooth track.', icon: '🚶', isNew: true },
  { id: 'pull-out', name: 'Pull Out', description: 'Steady slow backward zoom pulling focus back from subjects.', icon: '🔍' },
  { id: 'push-in', name: 'Push In', description: 'Steady slow forward push movement toward active subjects.', icon: '🔎' },
  { id: 'rack-focus', name: 'Rack Focus', description: 'Focal depth shift from foreground to background.', icon: '👓' },
  { id: 'shoulder-rig', name: 'Shoulder Rig', description: 'Medium handheld shake with subtle vertical step steps.', icon: '🤳', isNew: true },
  { id: 'snap-rotation', name: 'Snap Rotation', description: 'Sudden 90 degree tilt rotation matching speed cut keys.', icon: '📐', isNew: true },
  { id: 'snap-zoom', name: 'Snap Zoom', description: 'Instant multi-step jump cut zoom magnification.', icon: '🔎', isNew: true },
  { id: 'sports-cam', name: 'Sports Cam', description: 'Aggressive tracking whip pans following action sequences.', icon: '🏃', isNew: true },
  { id: 'tracking-camera', name: 'Tracking Camera', description: 'Smooth sideways trucking pans to follow action.', icon: '🚶' },
  { id: 'vertical-reveal', name: 'Vertical Reveal', description: 'Pan up movement beginning from ground details up to subjects.', icon: '⬆️', isNew: true }
];
