import { EffectItem } from '../components/EffectGrid';

export const FIRE_EFFECTS: EffectItem[] = [
  { id: 'ash-particles', name: 'Ash Particles', description: 'Simulates floating dark ash flakes rising against dark background.', icon: '🌪️' },
  { id: 'blue-flame', name: 'Blue Flame', description: 'Stylized hot chemical blue flames flickering from layout borders.', icon: '💙', isNew: true },
  { id: 'burning-aura', name: 'Burning Aura', description: 'Surrounds centered subjects with a soft orange heat shimmer.', icon: '🔥', isNew: true },
  { id: 'burning-edge', name: 'Burning Edge', description: 'Gives the video frame border a flickering burning coal orange texture.', icon: '🖼️' },
  { id: 'burning-paper', name: 'Burning Paper', description: 'Transition style effect where frame burns outward from center.', icon: '📄' },
  { id: 'campfire-glow', name: 'Campfire Glow', description: 'Warm flickering light simulation casting soft orange shadows.', icon: '⛺' },
  { id: 'dragon-fire', name: 'Dragon Fire', description: 'Slow dense horizontal jets of fire breathing across frame.', icon: '🐉', isNew: true },
  { id: 'electric-flame', name: 'Electric Flame', description: 'Charged lightning sparks branching into glowing flame streaks.', icon: '⚡', isNew: true },
  { id: 'ember-glow', name: 'Ember Glow', description: 'Soft breathing red-orange background illumination.', icon: '💡' },
  { id: 'ember-storm', name: 'Ember Storm', description: 'Thick stream of wind-driven orange spark particles.', icon: '🌪️', isNew: true },
  { id: 'energy-flame', name: 'Energy Flame', description: 'Futuristic cyan/pink plasma flames pulsing.', icon: '⚡', isNew: true },
  { id: 'eternal-flame', name: 'Eternal Flame', description: 'Slow gentle looping flame burning centered at bottom coordinates.', icon: '🕯️', isNew: true },
  { id: 'explosion-fire', name: 'Explosion Fire', description: 'Intense rapid shockwave of orange flame and expansion smoke.', icon: '💥' },
  { id: 'fire-explosion-pro', name: 'Fire Explosion Pro', description: 'Premium explosion asset overlay with secondary shockwave sparks.', icon: '💥', isNew: true },
  { id: 'fire-flash', name: 'Fire Flash', description: 'Subtle high exposure burst of orange-yellow color shifts.', icon: '⚡' },
  { id: 'fire-overlay', name: 'Fire Overlay', description: 'General ambient overlay of rising fire particles and dust.', icon: '🔥' },
  { id: 'fire-portal', name: 'Fire Portal', description: 'Circular rings of flames swirling around center viewport.', icon: '⭕', isNew: true },
  { id: 'fire-pulse', name: 'Fire Pulse', description: 'Synchronized brightness and color saturation pulse with embers.', icon: '💓' },
  { id: 'fire-ring', name: 'Fire Ring', description: 'Circular boundary of fire flames framing the active subject.', icon: '⭕' },
  { id: 'fire-sparks', name: 'Fire Sparks', description: 'High frequency sparks bursting upward with wind drift.', icon: '✨' },
  { id: 'fire-spiral', name: 'Fire Spiral', description: 'Swirling vortex trail of sparks circling screen pivot.', icon: '🌀', isNew: true },
  { id: 'fire-tornado', name: 'Fire Tornado', description: 'Severe vertical vortex of orange fire flames spinning.', icon: '🌪️', isNew: true },
  { id: 'fire-trail', name: 'Fire Trail', description: 'Leaves a glowing flame trail behind fast moving subjects.', icon: '🏃' },
  { id: 'fire-vortex', name: 'Fire Vortex', description: 'Circular dynamic fire storm pulling particles inward.', icon: '🌀', isNew: true },
  { id: 'fire-whirlwind', name: 'Fire Whirlwind', description: 'Drifting vertical columns of flickering heat waves.', icon: '🌪️', isNew: true },
  { id: 'flame-burst', name: 'Flame Burst', description: 'Sudden vertical jet of fire flame rising from viewport bottom.', icon: '🌋' },
  { id: 'flame-crown', name: 'Flame Crown', description: 'Places a line of flames floating directly over subjects.', icon: '👑', isNew: true },
  { id: 'flame-shockwave', name: 'Flame Shockwave', description: 'Expanding horizontal ring of red-orange heat blast.', icon: '💥', isNew: true },
  { id: 'flame-wave', name: 'Flame Wave', description: 'Waves of fire scrolling horizontally across viewport bottom.', icon: '🌊', isNew: true },
  { id: 'green-flame', name: 'Green Flame', description: 'Spooky chemical lime-green flames crawling up borders.', icon: '💚', isNew: true },
  { id: 'heat-wave', name: 'Heat Wave', description: 'Wavy air distortion refracting background pixels due to temperature.', icon: '💨' },
  { id: 'hellfire', name: 'Hellfire', description: 'Ominous dark red and black flames covering borders.', icon: '💀', isNew: true },
  { id: 'inferno', name: 'Inferno', description: 'Heavy screen saturation of red-orange flame overlay on the frame.', icon: '👹' },
  { id: 'inferno-burst', name: 'Inferno Burst', description: 'Sudden explosive flashes of orange saturating overall frame.', icon: '💥', isNew: true },
  { id: 'lava-burst', name: 'Lava Burst', description: 'Volcanic dynamic burst spraying molten drops upward.', icon: '🌋', isNew: true },
  { id: 'lava-flow', name: 'Lava Flow', description: 'Slow viscous glowing orange fluid rivers scrolling upward.', icon: '🌊' },
  { id: 'molten-metal', name: 'Molten Metal', description: 'Liquid hot yellow-gold drops dripping down from borders.', icon: '🍯' },
  { id: 'molten-sparks', name: 'Molten Sparks', description: 'Thick heavy droplets of glowing metal bouncing down.', icon: 'spark', isNew: true },
  { id: 'nuclear-fire', name: 'Nuclear Fire', description: 'Blinding white-yellow flash shifting to dark green smoke.', icon: '☢️', isNew: true },
  { id: 'phoenix-fire', name: 'Phoenix Fire', description: 'Golden-orange wings of fire spreading across background.', icon: '🦅', isNew: true },
  { id: 'plasma-fire', name: 'Plasma Fire', description: 'Violet high energy fire discharge sparking rapidly.', icon: '🟣', isNew: true },
  { id: 'purple-flame', name: 'Purple Flame', description: 'Stylized amethyst-purple fire flames flickering.', icon: '💜', isNew: true },
  { id: 'smoke-fire', name: 'Smoke Fire', description: 'Dense dark carbon smoke with rising glowing embers.', icon: '🌫️' },
  { id: 'torch-light', name: 'Torch Light', description: 'Directional flickering cone spotlight mimicry.', icon: '🔦' },
  { id: 'wildfire', name: 'Wildfire', description: 'Uncontrolled flame walls spreading organically across viewport.', icon: '🌳' }
];
