import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'ai-vision',
    name: 'AI Vision',
    category: 'AI',
    description: 'Real-time intelligent machine vision scanning overlay.',
    cssFilter: 'contrast(1.1) saturate(1.2) brightness(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'ai-neural',
    name: 'Neural Network',
    category: 'AI',
    description: 'Dynamic neural network node paths connecting across frame boundaries.',
    cssFilter: 'contrast(1.15) saturate(1.1) brightness(1.03)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-ml',
    name: 'Machine Learning',
    category: 'AI',
    description: 'Stochastic learning algorithms and statistical data streams.',
    cssFilter: 'contrast(1.08) saturate(1.15) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-deep',
    name: 'Deep Learning',
    category: 'AI',
    description: 'Hierarchical layers simulating multi-level hidden node activation.',
    cssFilter: 'contrast(1.2) saturate(1.25) brightness(1.01)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-computervision',
    name: 'Computer Vision',
    category: 'AI',
    description: 'Visual edge tracing and contour identification matrices.',
    cssFilter: 'contrast(1.3) saturate(1.3) brightness(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'ai-facedetect',
    name: 'Face Detection',
    category: 'AI',
    description: 'Active bounding boxes tracking facial targets in real time.',
    cssFilter: 'contrast(1.12) saturate(1.2) brightness(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'ai-objectdetect',
    name: 'Object Detection',
    category: 'AI',
    description: 'Classified labeling vectors identifying surrounding environment.',
    cssFilter: 'contrast(1.15) saturate(1.22) brightness(1.03)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'ai-scanner',
    name: 'AI Scanner',
    category: 'AI',
    description: 'Horizontal neon laser scan beam processing pixel matrix grids.',
    cssFilter: 'contrast(1.2) saturate(1.35) brightness(1.06)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-cyber',
    name: 'Cyber Intelligence',
    category: 'AI',
    description: 'Advanced mainframe interface with rotating cryptographic blocks.',
    cssFilter: 'hue-rotate(120deg) contrast(1.18) saturate(1.25) brightness(1.02)',
    defaultIntensity: 70,
    defaultOpacity: 85,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-assistant',
    name: 'Smart Assistant',
    category: 'AI',
    description: 'Pulsing voice-frequency sphere visualizer and status indicators.',
    cssFilter: 'contrast(1.1) saturate(1.3) brightness(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-quantum',
    name: 'Quantum AI',
    category: 'AI',
    description: 'Probabilistic quantum bit superpositions flashing rapidly.',
    cssFilter: 'contrast(1.25) saturate(1.4) brightness(1.04)',
    defaultIntensity: 80,
    defaultOpacity: 95,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-holographic',
    name: 'Holographic AI',
    category: 'AI',
    description: 'Glowing volumetric holographic panels projecting cyber intelligence.',
    cssFilter: 'hue-rotate(180deg) contrast(1.1) saturate(1.3) brightness(1.05)',
    defaultIntensity: 65,
    defaultOpacity: 80,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-matrix',
    name: 'AI Matrix',
    category: 'AI',
    description: 'Falling binary stream layers processing data structures.',
    cssFilter: 'contrast(1.35) saturate(0.7) brightness(1.02)',
    defaultIntensity: 75,
    defaultOpacity: 85,
    defaultSpeed: 22,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-robot',
    name: 'Robot Vision',
    category: 'AI',
    description: 'Red tint heads-up telemetry display from mechanical optic sensors.',
    cssFilter: 'hue-rotate(300deg) contrast(1.22) saturate(1.4) brightness(1.03)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'ai-brain',
    name: 'Digital Brain',
    category: 'AI',
    description: 'Rotating vector model brain highlighting active cognitive hubs.',
    cssFilter: 'contrast(1.15) saturate(1.25) brightness(1.01)',
    defaultIntensity: 60,
    defaultOpacity: 80,
    defaultSpeed: 9,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-future',
    name: 'Future AI',
    category: 'AI',
    description: 'Next-generation neural AI interface simulation.',
    cssFilter: 'contrast(1.18) saturate(1.35) brightness(1.04)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-tech',
    name: 'Tech Interface',
    category: 'AI',
    description: 'High-tech telemetry readouts, compasses, and calibration crosshairs.',
    cssFilter: 'contrast(1.12) saturate(1.2) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-smarthud',
    name: 'Smart HUD',
    category: 'AI',
    description: 'Intelligent flight HUD tracking real-time position indicators.',
    cssFilter: 'contrast(1.2) saturate(1.3) brightness(1.03)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-premium',
    name: 'Premium AI',
    category: 'AI',
    description: 'Multi-threaded network paths tracking complex data arrays.',
    cssFilter: 'contrast(1.25) saturate(1.4) brightness(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 16,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'ai-custom',
    name: 'Custom AI',
    category: 'AI',
    description: 'Fully customizable neural networks, scanners, and HUD overlays.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];

// Generate remainder to have exactly 50 presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `ai-preset-${i}`,
    name: `AI Sub-system ${i}`,
    category: 'AI',
    description: `Intelligent cognitive sub-system matrix #${i}.`,
    cssFilter: `hue-rotate(${(i * 19) % 360}deg) brightness(${0.96 + (i % 3) * 0.03}) contrast(${1.08 + (i % 4) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 4) * 4,
    defaultSpeed: 10 + (i % 7) * 4,
    defaultAngle: (i * 37) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const AI_EFFECTS = list;
