import { EffectPreset } from './effectsPreset';

export const BASIC_EFFECTS: EffectPreset[] = [
  {
    id: 'basic-fade-in',
    name: 'Fade In',
    category: 'Basic',
    description: 'Gradually fade in clip opacity from 0% at the start.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-fade-out',
    name: 'Fade Out',
    category: 'Basic',
    description: 'Gradually fade out clip opacity to 0% at the end.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-zoom-in',
    name: 'Zoom In',
    category: 'Basic',
    description: 'Smoothly zoom into the center of the clip.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-zoom-out',
    name: 'Zoom Out',
    category: 'Basic',
    description: 'Smoothly zoom out from the clip focus.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-move-left',
    name: 'Move Left',
    category: 'Basic',
    description: 'Slide the clip elements towards the left boundary.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-move-right',
    name: 'Move Right',
    category: 'Basic',
    description: 'Slide the clip elements towards the right boundary.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-move-up',
    name: 'Move Up',
    category: 'Basic',
    description: 'Slide the clip elements upwards.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-move-down',
    name: 'Move Down',
    category: 'Basic',
    description: 'Slide the clip elements downwards.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-spin-cw',
    name: 'Spin Clockwise',
    category: 'Basic',
    description: 'Spin the clip clockwise continuously.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-spin-ccw',
    name: 'Spin Counter Clockwise',
    category: 'Basic',
    description: 'Spin the clip counter-clockwise continuously.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-flip-h',
    name: 'Flip Horizontal',
    category: 'Basic',
    description: 'Flip the clip horizontally (mirror look).',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-flip-v',
    name: 'Flip Vertical',
    category: 'Basic',
    description: 'Flip the clip vertically (upside down look).',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-scale-up',
    name: 'Scale Up',
    category: 'Basic',
    description: 'Enlarge the rendering scale parameters.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-scale-down',
    name: 'Scale Down',
    category: 'Basic',
    description: 'Decrease the rendering scale parameters.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-bounce',
    name: 'Bounce',
    category: 'Basic',
    description: 'Add an elastic vertical bounce motion.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-pulse',
    name: 'Pulse',
    category: 'Basic',
    description: 'Add a hardware-accelerated breathing pulse wave.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-shake',
    name: 'Shake',
    category: 'Basic',
    description: 'Add a standard camera shake and jitter.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-swing',
    name: 'Swing',
    category: 'Basic',
    description: 'Swing the rotation angle back and forth.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-elastic',
    name: 'Elastic',
    category: 'Basic',
    description: 'Add an elastic spring ease to scaling attributes.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-stretch',
    name: 'Stretch',
    category: 'Basic',
    description: 'Stretch the clip shape horizontally.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-compress',
    name: 'Compress',
    category: 'Basic',
    description: 'Compress the clip shape horizontally.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-grow',
    name: 'Grow',
    category: 'Basic',
    description: 'Smoothly increase render size over duration.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-shrink',
    name: 'Shrink',
    category: 'Basic',
    description: 'Smoothly decrease render size over duration.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-rotate-l',
    name: 'Rotate Left',
    category: 'Basic',
    description: 'Rotate target angle counter-clockwise.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-rotate-r',
    name: 'Rotate Right',
    category: 'Basic',
    description: 'Rotate target angle clockwise.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-float-up',
    name: 'Float Up',
    category: 'Basic',
    description: 'Slowly float upwards continuously.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-float-down',
    name: 'Float Down',
    category: 'Basic',
    description: 'Slowly float downwards continuously.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-pop-in',
    name: 'Pop In',
    category: 'Basic',
    description: 'Pop-in scale transition effect.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-pop-out',
    name: 'Pop Out',
    category: 'Basic',
    description: 'Pop-out scale transition effect.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-blink',
    name: 'Blink',
    category: 'Basic',
    description: 'Blink opacity rapidly.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-jelly',
    name: 'Jelly',
    category: 'Basic',
    description: 'Jelly-like wobbling stretch animation.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-rubber',
    name: 'Rubber',
    category: 'Basic',
    description: 'Rubber-like scale bounce stretching.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-swing-l',
    name: 'Swing Left',
    category: 'Basic',
    description: 'Swing leftward rotation offset.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-swing-r',
    name: 'Swing Right',
    category: 'Basic',
    description: 'Swing rightward rotation offset.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-heartbeat',
    name: 'Heartbeat',
    category: 'Basic',
    description: 'Simulate high-frequency double heartbeat scale pulse.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-quick-zoom',
    name: 'Quick Zoom',
    category: 'Basic',
    description: 'Zoom in very rapidly at start.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-slow-zoom',
    name: 'Slow Zoom',
    category: 'Basic',
    description: 'Zoom in slowly over duration.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-micro-shake',
    name: 'Micro Shake',
    category: 'Basic',
    description: 'Subtle high-frequency camera shake.',
    cssFilter: 'none',
    defaultIntensity: 30,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-macro-shake',
    name: 'Macro Shake',
    category: 'Basic',
    description: 'Strong low-frequency camera shake.',
    cssFilter: 'none',
    defaultIntensity: 90,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-drift-l',
    name: 'Drift Left',
    category: 'Basic',
    description: 'Slow drift motion to the left.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-drift-r',
    name: 'Drift Right',
    category: 'Basic',
    description: 'Slow drift motion to the right.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-drift-up',
    name: 'Drift Up',
    category: 'Basic',
    description: 'Slow drift motion upwards.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-drift-down',
    name: 'Drift Down',
    category: 'Basic',
    description: 'Slow drift motion downwards.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-rotate-zoom',
    name: 'Rotate & Zoom',
    category: 'Basic',
    description: 'Simultaneously rotate and zoom the clip.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-scale-rotate',
    name: 'Scale Rotate',
    category: 'Basic',
    description: 'Scale while rotating elements.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-center-focus',
    name: 'Center Focus',
    category: 'Basic',
    description: 'Vignette contrast centering visual focus.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-expand',
    name: 'Expand',
    category: 'Basic',
    description: 'Expand size from center.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-collapse',
    name: 'Collapse',
    category: 'Basic',
    description: 'Shrink scale to zero center.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-ease-in',
    name: 'Ease In',
    category: 'Basic',
    description: 'Smooth accelerated ease-in transition.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'basic-ease-out',
    name: 'Ease Out',
    category: 'Basic',
    description: 'Smooth decelerated ease-out transition.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
