import { EffectPreset } from './effectsPreset';

export const BLUR_EFFECTS: EffectPreset[] = [
  {
    id: 'blur-gaussian',
    name: 'Gaussian Blur',
    category: 'Blur',
    description: 'High-quality uniform Gaussian blur.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-motion',
    name: 'Motion Blur',
    category: 'Blur',
    description: 'Linear blur simulating camera motion speed.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-zoom',
    name: 'Zoom Blur',
    category: 'Blur',
    description: 'Radial focal blur spreading outward from center.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-radial',
    name: 'Radial Blur',
    category: 'Blur',
    description: 'Circular rotational blur centering subject.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-directional',
    name: 'Directional Blur',
    category: 'Blur',
    description: 'Direction-oriented linear blur.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-lens',
    name: 'Lens Blur',
    category: 'Blur',
    description: 'Camera lens aberration soft focus simulation.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-bokeh',
    name: 'Bokeh Blur',
    category: 'Blur',
    description: 'Simulates aesthetic out-of-focus background light circles.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-background',
    name: 'Background Blur',
    category: 'Blur',
    description: 'Blurs peripheral canvas background elements.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-foreground',
    name: 'Foreground Blur',
    category: 'Blur',
    description: 'Blurs center foreground elements.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-depth',
    name: 'Depth Blur',
    category: 'Blur',
    description: 'Simulates shallow depth-of-field field focus.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-tilt-shift',
    name: 'Tilt Shift',
    category: 'Blur',
    description: 'Simulates mini tilt-shift focus bands.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-soft-focus',
    name: 'Soft Focus',
    category: 'Blur',
    description: 'Cinematic dreamy soft highlight glow.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-dream',
    name: 'Dream Blur',
    category: 'Blur',
    description: 'Ethereal romantic halo blur look.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-glow',
    name: 'Glow Blur',
    category: 'Blur',
    description: 'Adds diffuse highlights glow bleed.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-fog',
    name: 'Fog Blur',
    category: 'Blur',
    description: 'Heavy ambient fog haze blur overlay.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-heat',
    name: 'Heat Blur',
    category: 'Blur',
    description: 'Distorted heat haze shimmering blur wave.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-ripple',
    name: 'Ripple Blur',
    category: 'Blur',
    description: 'Circular water ripple focal blur shifts.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-edge',
    name: 'Edge Blur',
    category: 'Blur',
    description: 'Blurs peripheral edges of video frames.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-center',
    name: 'Center Blur',
    category: 'Blur',
    description: 'Blurs center elements leaving edges sharp.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-focus',
    name: 'Focus Blur',
    category: 'Blur',
    description: 'Focal points blur shifting over playback.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-pulse',
    name: 'Blur Pulse',
    category: 'Blur',
    description: 'Pulsates blur radius periodically.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-fade',
    name: 'Blur Fade',
    category: 'Blur',
    description: 'Fades blur out gradually.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-sweep',
    name: 'Blur Sweep',
    category: 'Blur',
    description: 'Sweeps blur across video from edge to edge.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-horizontal',
    name: 'Horizontal Blur',
    category: 'Blur',
    description: 'Constrains blur strictly to horizontal plane.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-vertical',
    name: 'Vertical Blur',
    category: 'Blur',
    description: 'Constrains blur strictly to vertical plane.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-diagonal',
    name: 'Diagonal Blur',
    category: 'Blur',
    description: 'Constrains blur strictly to diagonal angle.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-spin',
    name: 'Spin Blur',
    category: 'Blur',
    description: 'Rotates blur elements clockwise.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-whirl',
    name: 'Whirl Blur',
    category: 'Blur',
    description: 'Whirlpool spiral blur shape distortion.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-wave',
    name: 'Wave Blur',
    category: 'Blur',
    description: 'Oscillating wave motion blur offsets.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-glass',
    name: 'Glass Blur',
    category: 'Blur',
    description: 'Frosty glass sheet blur simulation.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-crystal',
    name: 'Crystal Blur',
    category: 'Blur',
    description: 'Crystalline refracted block blur.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-pixel',
    name: 'Pixel Blur',
    category: 'Blur',
    description: 'Pixelated macro-block mosaic blur.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-smooth',
    name: 'Smooth Blur',
    category: 'Blur',
    description: 'Super-clean low-pass visual blur filter.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-portrait',
    name: 'Portrait Blur',
    category: 'Blur',
    description: 'Aesthetic depth grading blur for face portraits.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-cinema',
    name: 'Cinema Blur',
    category: 'Blur',
    description: 'High-end cinema lens defocus grade.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-night',
    name: 'Night Blur',
    category: 'Blur',
    description: 'Dark-graded high-contrast bokeh lens pull.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-ghost',
    name: 'Ghost Blur',
    category: 'Blur',
    description: 'Eerie low-opacity trail ghosting blur.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-trail',
    name: 'Trail Blur',
    category: 'Blur',
    description: 'Long frame delay buffer motion trails blur.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-echo',
    name: 'Echo Blur',
    category: 'Blur',
    description: 'Multi-frame feedback echo motion blur.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-light',
    name: 'Light Blur',
    category: 'Blur',
    description: 'Bright-graded light flare bloom bleed.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-bloom',
    name: 'Bloom Blur',
    category: 'Blur',
    description: 'Luminance-masked bright glow bloom.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-mirror',
    name: 'Mirror Blur',
    category: 'Blur',
    description: 'Symmetrical mirrored border blur reflections.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-liquid',
    name: 'Liquid Blur',
    category: 'Blur',
    description: 'Viscous fluid shifting warp blur elements.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-stretch',
    name: 'Stretch Blur',
    category: 'Blur',
    description: 'Horizontally stretched streak motion blur.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-speed',
    name: 'Speed Blur',
    category: 'Blur',
    description: 'Directional speed streak motion pan.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-action',
    name: 'Action Blur',
    category: 'Blur',
    description: 'Violent high-speed shake motion blur.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-velocity',
    name: 'Velocity Blur',
    category: 'Blur',
    description: 'Velocity-mapped stretch motion blur.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-extreme',
    name: 'Extreme Blur',
    category: 'Blur',
    description: 'Super-high radius heavy blur filter.',
    cssFilter: 'none',
    defaultIntensity: 90,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-smart',
    name: 'Smart Blur',
    category: 'Blur',
    description: 'Edge-preserving smart smoothing blur.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'blur-pro-lens',
    name: 'Pro Lens Blur',
    category: 'Blur',
    description: 'Aperture-accurate professional lens blur.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
