import { EffectPreset } from './effectsPreset';

export const CAMERA_EFFECTS: EffectPreset[] = [
  {
    id: 'camera-handheld',
    name: 'Handheld Camera',
    category: 'Camera',
    description: 'Realistic handheld camera pan wobble.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-shake',
    name: 'Camera Shake',
    category: 'Camera',
    description: 'Standard translation jitter camera shake.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-earthquake',
    name: 'Earthquake',
    category: 'Camera',
    description: 'High-amplitude violent ground shaking motion.',
    cssFilter: 'none',
    defaultIntensity: 90,
    defaultOpacity: 100,
    defaultSpeed: 75,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-crash-zoom',
    name: 'Crash Zoom',
    category: 'Camera',
    description: 'Extremely fast cinematic focal length zoom-in.',
    cssFilter: 'none',
    defaultIntensity: 85,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-whip-l',
    name: 'Whip Left',
    category: 'Camera',
    description: 'Fast pan whip motion blur to the left.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-whip-r',
    name: 'Whip Right',
    category: 'Camera',
    description: 'Fast pan whip motion blur to the right.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-whip-up',
    name: 'Whip Up',
    category: 'Camera',
    description: 'Fast tilt whip motion blur upwards.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-whip-down',
    name: 'Whip Down',
    category: 'Camera',
    description: 'Fast tilt whip motion blur downwards.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-dolly-in',
    name: 'Dolly In',
    category: 'Camera',
    description: 'Move camera physically closer to the focus area.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-dolly-out',
    name: 'Dolly Out',
    category: 'Camera',
    description: 'Move camera physically away from the focus area.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-truck-l',
    name: 'Truck Left',
    category: 'Camera',
    description: 'Translate camera horizontally to the left.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-truck-r',
    name: 'Truck Right',
    category: 'Camera',
    description: 'Translate camera horizontally to the right.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-pedestal-up',
    name: 'Pedestal Up',
    category: 'Camera',
    description: 'Translate camera vertically upwards.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-pedestal-down',
    name: 'Pedestal Down',
    category: 'Camera',
    description: 'Translate camera vertically downwards.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-orbit-l',
    name: 'Orbit Left',
    category: 'Camera',
    description: 'Simulate camera circling subject towards the left.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-orbit-r',
    name: 'Orbit Right',
    category: 'Camera',
    description: 'Simulate camera circling subject towards the right.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-roll-l',
    name: 'Roll Left',
    category: 'Camera',
    description: 'Rotate the camera sensor counter-clockwise.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-roll-r',
    name: 'Roll Right',
    category: 'Camera',
    description: 'Rotate the camera sensor clockwise.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-dutch-angle',
    name: 'Dutch Angle',
    category: 'Camera',
    description: 'Static cinematic Dutch tilt perspective.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-focus-pull',
    name: 'Focus Pull',
    category: 'Camera',
    description: 'Dynamic focus depth shifting from blurry to sharp.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-rack-focus',
    name: 'Rack Focus',
    category: 'Camera',
    description: 'Alternate focus pull shifting depth points.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-snap-zoom',
    name: 'Snap Zoom',
    category: 'Camera',
    description: 'Rapid punch zoom followed by quick reset.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 85,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-slow-push',
    name: 'Slow Push',
    category: 'Camera',
    description: 'Cinematic slow forward zoom zoom in.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-slow-pull',
    name: 'Slow Pull',
    category: 'Camera',
    description: 'Cinematic slow pull back zoom out.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-action-cam',
    name: 'Action Cam',
    category: 'Camera',
    description: 'Action camera dynamic high-frequency shake.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-drone-rise',
    name: 'Drone Rise',
    category: 'Camera',
    description: 'Simulate high-altitude crane or drone rising.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-drone-drop',
    name: 'Drone Drop',
    category: 'Camera',
    description: 'Simulate crane or drone dropping downwards.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-fpv-dive',
    name: 'FPV Dive',
    category: 'Camera',
    description: 'Thrilling FPV drone split rotation dive.',
    cssFilter: 'none',
    defaultIntensity: 85,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-fpv-fly',
    name: 'FPV Fly Through',
    category: 'Camera',
    description: 'FPV drone style low-altitude horizontal glide.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-steadicam',
    name: 'Steadicam',
    category: 'Camera',
    description: 'Super smooth gimbal-stabilized camera glide.',
    cssFilter: 'none',
    defaultIntensity: 30,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-walking-cam',
    name: 'Walking Camera',
    category: 'Camera',
    description: 'Simulate steady walking step vertical shifts.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-running-cam',
    name: 'Running Camera',
    category: 'Camera',
    description: 'Simulate fast high-amplitude running step shifts.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-pov-motion',
    name: 'POV Motion',
    category: 'Camera',
    description: 'First-person perspective dynamic head sway.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-lens-breathing',
    name: 'Lens Breathing',
    category: 'Camera',
    description: 'Micro focal adjustments breathing cycle.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-parallax',
    name: 'Parallax',
    category: 'Camera',
    description: 'Scale-shifting depth parallax illusion.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-360-orbit',
    name: '360 Orbit',
    category: 'Camera',
    description: 'Full continuous 360-degree rotation pan.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-arc-shot',
    name: 'Arc Shot',
    category: 'Camera',
    description: 'Cinematic arced camera rotation tracking.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-flash',
    name: 'Camera Flash',
    category: 'Camera',
    description: 'Simulated high-brightness shutter flash pulse.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 90,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-exposure-shift',
    name: 'Exposure Shift',
    category: 'Camera',
    description: 'Dynamic light shift flickering.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-focus-blur',
    name: 'Focus Blur',
    category: 'Camera',
    description: 'Dynamic focal blur changes.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-drift',
    name: 'Camera Drift',
    category: 'Camera',
    description: 'Slow continuous random frame drift.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-tilt-up',
    name: 'Tilt Up',
    category: 'Camera',
    description: 'Slow vertical tilt pan upwards.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-tilt-down',
    name: 'Tilt Down',
    category: 'Camera',
    description: 'Slow vertical tilt pan downwards.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-pan-l',
    name: 'Pan Left',
    category: 'Camera',
    description: 'Slow horizontal panning leftwards.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-pan-r',
    name: 'Pan Right',
    category: 'Camera',
    description: 'Slow horizontal panning rightwards.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-jitter-cam',
    name: 'Jitter Camera',
    category: 'Camera',
    description: 'High-frequency micro-scale sensor jitter.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-doc-cam',
    name: 'Documentary Camera',
    category: 'Camera',
    description: 'Informal handheld zooming focus adjustment.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-cinema-cam',
    name: 'Cinema Camera',
    category: 'Camera',
    description: 'Cinematic glide with slow stabilization.',
    cssFilter: 'none',
    defaultIntensity: 30,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-movie-push',
    name: 'Movie Push',
    category: 'Camera',
    description: 'Polished progressive push-in motion.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'camera-epic-zoom',
    name: 'Epic Zoom',
    category: 'Camera',
    description: 'Grand scale epic camera dolly push.',
    cssFilter: 'none',
    defaultIntensity: 90,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
