import { EffectPreset } from './effectsPreset';

export const CINEMATIC_EFFECTS: EffectPreset[] = [
  {
    id: 'cine-film-grain',
    name: 'Film Grain',
    category: 'Cinematic',
    description: 'Simulates analog film silver halide grain textures.',
    cssFilter: 'contrast(1.05) brightness(0.98)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay'
  },
  {
    id: 'cine-leak-gold',
    name: 'Light Leak Gold',
    category: 'Cinematic',
    description: 'Golden ambient vintage light leaks sweep.',
    cssFilter: 'contrast(1.05) brightness(1.05) sepia(0.2)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-leak-blue',
    name: 'Light Leak Blue',
    category: 'Cinematic',
    description: 'Cool blue ambient light leaks sweep.',
    cssFilter: 'contrast(1.05) brightness(1.02) hue-rotate(180deg)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-leak-rainbow',
    name: 'Rainbow Light Leak',
    category: 'Cinematic',
    description: 'Prism spectrum refraction color leak.',
    cssFilter: 'contrast(1.02) brightness(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-film-burn',
    name: 'Film Burn',
    category: 'Cinematic',
    description: 'Warm organic projection burn flashes.',
    cssFilter: 'saturate(1.2) brightness(1.1) sepia(0.1)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-dust-particles',
    name: 'Dust Particles',
    category: 'Cinematic',
    description: 'Floating organic projector dust specks.',
    cssFilter: 'contrast(1.02)',
    defaultIntensity: 35,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-film-scratches',
    name: 'Film Scratches',
    category: 'Cinematic',
    description: 'Vertical projector lines and scratch hairs.',
    cssFilter: 'contrast(1.08) brightness(0.95)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-vintage-film',
    name: 'Vintage Film',
    category: 'Cinematic',
    description: 'Complete vintage movie look with sepia tint.',
    cssFilter: 'sepia(0.35) contrast(0.95) brightness(0.92)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-cinema-bloom',
    name: 'Cinema Bloom',
    category: 'Cinematic',
    description: 'Elegant glow bleeding in bright highlights.',
    cssFilter: 'brightness(1.08) saturate(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-hdr-glow',
    name: 'HDR Glow',
    category: 'Cinematic',
    description: 'Dynamic range enhancement with bright glows.',
    cssFilter: 'contrast(1.15) saturate(1.1) brightness(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-soft-highlight',
    name: 'Soft Highlight',
    category: 'Cinematic',
    description: 'Rolls off highlight peaks smoothly.',
    cssFilter: 'brightness(1.05) contrast(0.95)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-lens-flare',
    name: 'Lens Flare',
    category: 'Cinematic',
    description: 'Cinematic warm circular lens glare overlay.',
    cssFilter: 'brightness(1.05) saturate(1.08)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-anamorphic-flare',
    name: 'Anamorphic Flare',
    category: 'Cinematic',
    description: 'Signature horizontal blue streak flare.',
    cssFilter: 'brightness(1.02) saturate(1.1) hue-rotate(180deg)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-sun-rays',
    name: 'Sun Rays',
    category: 'Cinematic',
    description: 'Golden volumetric god rays overlay.',
    cssFilter: 'brightness(1.08) contrast(1.05) sepia(0.1)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cine-moonlight',
    name: 'Moonlight Glow',
    category: 'Cinematic',
    description: 'Slightly blue night ambient moonlight look.',
    cssFilter: 'brightness(0.85) contrast(1.1) saturate(0.85) sepia(0.08) hue-rotate(190deg)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-golden-hour',
    name: 'Golden Hour',
    category: 'Cinematic',
    description: 'Warm gold afternoon sun wash.',
    cssFilter: 'sepia(0.2) saturate(1.15) brightness(1.04) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-blue-hour',
    name: 'Blue Hour',
    category: 'Cinematic',
    description: 'Dusk deep blue-indigo gradient look.',
    cssFilter: 'saturate(0.95) brightness(0.9) contrast(1.05) hue-rotate(200deg)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-teal-orange',
    name: 'Teal & Orange',
    category: 'Cinematic',
    description: 'Classic block-buster color grading.',
    cssFilter: 'contrast(1.12) saturate(1.15) brightness(0.98)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-warm',
    name: 'Warm Cinema',
    category: 'Cinematic',
    description: 'Comforting orange-red cinema tint.',
    cssFilter: 'sepia(0.15) brightness(1.02) saturate(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-cold',
    name: 'Cold Cinema',
    category: 'Cinematic',
    description: 'Moody blue-cyan steel grading.',
    cssFilter: 'brightness(0.98) saturate(0.95) contrast(1.04) hue-rotate(185deg)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-letterbox',
    name: 'Letterbox',
    category: 'Cinematic',
    description: 'Cinema scope 2.39:1 crop horizontal bars.',
    cssFilter: 'none',
    defaultIntensity: 100,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-vignette',
    name: 'Vignette',
    category: 'Cinematic',
    description: 'Elegant soft vignette dark corners.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-contrast',
    name: 'Cinema Contrast',
    category: 'Cinematic',
    description: 'Premium soft s-curve high contrast.',
    cssFilter: 'contrast(1.15) brightness(0.99)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-soft-diffusion',
    name: 'Soft Diffusion',
    category: 'Cinematic',
    description: 'Promist diffuse highlights reduction filter.',
    cssFilter: 'brightness(1.05) contrast(0.92)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-dream',
    name: 'Dream Cinema',
    category: 'Cinematic',
    description: 'Soft pastel dream glow filter.',
    cssFilter: 'brightness(1.1) saturate(1.1) contrast(0.92) sepia(0.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-epic-contrast',
    name: 'Epic Contrast',
    category: 'Cinematic',
    description: 'Bold high-contrast block-buster look.',
    cssFilter: 'contrast(1.25) brightness(0.96) saturate(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-noir',
    name: 'Noir Film',
    category: 'Cinematic',
    description: 'Classic moody high-contrast monochrome.',
    cssFilter: 'grayscale(1) contrast(1.25) brightness(0.95)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-silver-screen',
    name: 'Silver Screen',
    category: 'Cinematic',
    description: 'Rich low-contrast silver monochrome look.',
    cssFilter: 'grayscale(1) contrast(1.08) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-projector',
    name: 'Projector Flicker',
    category: 'Cinematic',
    description: 'Old bulb projector light flicker.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-film-gate',
    name: 'Film Gate',
    category: 'Cinematic',
    description: 'Simulates organic physical camera gate jitter.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-chromatic-glow',
    name: 'Chromatic Glow',
    category: 'Cinematic',
    description: 'Spectral aberration glow bleed.',
    cssFilter: 'brightness(1.05) saturate(1.1)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-soft-shadow',
    name: 'Soft Shadow',
    category: 'Cinematic',
    description: 'Softens shadow details and lift levels.',
    cssFilter: 'contrast(0.92) brightness(1.02)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-spotlight',
    name: 'Spotlight',
    category: 'Cinematic',
    description: 'Radial focus lighting center mask.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-edge-glow',
    name: 'Edge Glow',
    category: 'Cinematic',
    description: 'Diffuse highlights glow on borders.',
    cssFilter: 'brightness(1.02) contrast(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-ambient-glow',
    name: 'Ambient Glow',
    category: 'Cinematic',
    description: 'Washes frame with low-frequency glow.',
    cssFilter: 'brightness(1.06) saturate(1.04)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-fade',
    name: 'Fade Film',
    category: 'Cinematic',
    description: 'Mutes shadows to create flat indie film look.',
    cssFilter: 'contrast(0.85) brightness(1.05) sepia(0.05)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-color-lift',
    name: 'Color Lift',
    category: 'Cinematic',
    description: 'Lifts shadow chroma saturation levels.',
    cssFilter: 'saturate(1.25) contrast(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-black-lift',
    name: 'Black Lift',
    category: 'Cinematic',
    description: 'Crushes true blacks to warm grey nodes.',
    cssFilter: 'contrast(0.9) brightness(1.06)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-highlight-roll',
    name: 'Highlight Roll-Off',
    category: 'Cinematic',
    description: 'Restores over-exposed clipping highlights.',
    cssFilter: 'brightness(0.95) contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-shadow-recovery',
    name: 'Shadow Recovery',
    category: 'Cinematic',
    description: 'Delineates details from heavy dark regions.',
    cssFilter: 'brightness(1.08) contrast(0.96)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-softness',
    name: 'Cinema Softness',
    category: 'Cinematic',
    description: 'Adds cinematic slight optical blur.',
    cssFilter: 'none',
    defaultIntensity: 35,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-night',
    name: 'Night Cinema',
    category: 'Cinematic',
    description: 'High-contrast midnight dark blue-cyan grade.',
    cssFilter: 'brightness(0.85) contrast(1.12) saturate(0.9) hue-rotate(195deg)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-action',
    name: 'Action Movie',
    category: 'Cinematic',
    description: 'Aggressive high-contrast cold action wash.',
    cssFilter: 'contrast(1.2) brightness(0.96) saturate(1.1) hue-rotate(185deg)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-documentary',
    name: 'Documentary Look',
    category: 'Cinematic',
    description: 'Neutral authentic low-contrast realism grade.',
    cssFilter: 'contrast(0.96) brightness(1.01) saturate(0.96)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-indie',
    name: 'Indie Film',
    category: 'Cinematic',
    description: 'Pastel yellow-green warm retro grade.',
    cssFilter: 'sepia(0.12) contrast(0.95) saturate(1.08) brightness(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-festival',
    name: 'Festival Film',
    category: 'Cinematic',
    description: 'Vivid color-rich high dynamic grading.',
    cssFilter: 'saturate(1.22) contrast(1.1) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-premium',
    name: 'Premium Cinema',
    category: 'Cinematic',
    description: 'Well-balanced high-end commercial grade.',
    cssFilter: 'contrast(1.08) saturate(1.05) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-hollywood',
    name: 'Hollywood Look',
    category: 'Cinematic',
    description: 'Classic warm-shadow high contrast cinema look.',
    cssFilter: 'contrast(1.18) sepia(0.06) saturate(1.1) brightness(0.99)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-directors-cut',
    name: 'Director\'s Cut',
    category: 'Cinematic',
    description: 'Raw high-contrast expressive film grade.',
    cssFilter: 'contrast(1.22) brightness(0.95) saturate(0.98)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'cine-master',
    name: 'Cinema Master',
    category: 'Cinematic',
    description: 'Definitive professional film print grade emulation.',
    cssFilter: 'contrast(1.12) saturate(1.08) brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
