import { EffectPreset } from './effectsPreset';

export const CRT_EFFECTS: EffectPreset[] = [
  {
    id: 'crt-classic',
    name: 'CRT Classic',
    category: 'CRT',
    description: 'Nostalgic analog television screen look with scanlines.',
    cssFilter: 'contrast(1.02) saturate(1.08) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-curved-screen',
    name: 'CRT Curved Screen',
    category: 'CRT',
    description: 'Simulates the rounded spherical glass tube curvature.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-scanlines',
    name: 'CRT Scanlines',
    category: 'CRT',
    description: 'Horizontal phosphor scan lines with scanning sways.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-rgb-mask',
    name: 'CRT RGB Mask',
    category: 'CRT',
    description: 'Fine vertical aperture grille shadow mask grid.',
    cssFilter: 'contrast(0.96) saturate(1.15)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-phosphor-glow',
    name: 'CRT Phosphor Glow',
    category: 'CRT',
    description: 'Phosphor color halation highlights ambient glow.',
    cssFilter: 'brightness(1.08) saturate(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-bloom',
    name: 'CRT Bloom',
    category: 'CRT',
    description: 'Vintage high-voltage electron gun highlights bloom.',
    cssFilter: 'brightness(1.08) contrast(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-flicker',
    name: 'CRT Flicker',
    category: 'CRT',
    description: 'High-speed analog electron gun raster refresh flickers.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 75,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-barrel-dist',
    name: 'CRT Barrel Distortion',
    category: 'CRT',
    description: 'Fisheye tube expansion pincushion warp.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-screen-warp',
    name: 'CRT Screen Warp',
    category: 'CRT',
    description: 'Bends video borders to match rounded arcade cabinets.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-static',
    name: 'CRT Static',
    category: 'CRT',
    description: 'High frequency black & white snow static overlay.',
    cssFilter: 'contrast(1.04) brightness(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-noise',
    name: 'CRT Noise',
    category: 'CRT',
    description: 'Random colored signal static lines sways.',
    cssFilter: 'contrast(1.02) brightness(1.01)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-ghosting',
    name: 'CRT Ghosting',
    category: 'CRT',
    description: 'Echo phosphor trails decaying movement shadows.',
    cssFilter: 'contrast(0.96) saturate(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-signal-loss',
    name: 'CRT Signal Loss',
    category: 'CRT',
    description: 'Desynchronized sync roll and frame rolls.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-color-bleed',
    name: 'CRT Color Bleed',
    category: 'CRT',
    description: 'Phosphor color displacement outlines.',
    cssFilter: 'saturate(1.2) contrast(0.98)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-chromatic-shift',
    name: 'CRT Chromatic Shift',
    category: 'CRT',
    description: 'Misaligned red-blue electron beams.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-horiz-roll',
    name: 'CRT Horizontal Roll',
    category: 'CRT',
    description: 'Sweep shifts scan lines horizontally.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-vert-roll',
    name: 'CRT Vertical Roll',
    category: 'CRT',
    description: 'Continuous vertical screen hold rolls.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-sync-error',
    name: 'CRT Sync Error',
    category: 'CRT',
    description: 'Jagged horizontal sync tearing lines.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-screen-jitter',
    name: 'CRT Screen Jitter',
    category: 'CRT',
    description: 'High frequency frame position offsets.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-screen-flash',
    name: 'CRT Screen Flash',
    category: 'CRT',
    description: 'Phosphor decay highlight flashing bursts.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-tv-noise',
    name: 'CRT TV Noise',
    category: 'CRT',
    description: 'Raw analog broadcast television static.',
    cssFilter: 'contrast(1.03) brightness(0.98)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-analog-signal',
    name: 'CRT Analog Signal',
    category: 'CRT',
    description: 'Faded antenna signal sways and warps.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-tv-dist',
    name: 'CRT TV Distortion',
    category: 'CRT',
    description: 'Heavy composite tracking wave distortions.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-channel-switch',
    name: 'CRT Channel Switch',
    category: 'CRT',
    description: 'Flash rolling channel change simulation.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-power-on',
    name: 'CRT Power On',
    category: 'CRT',
    description: 'Electron beam expanding from central spot.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-power-off',
    name: 'CRT Power Off',
    category: 'CRT',
    description: 'Electron beam collapsing to a thin central line.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-pixel-glow',
    name: 'CRT Pixel Glow',
    category: 'CRT',
    description: 'High intensity individual subpixel bloom.',
    cssFilter: 'brightness(1.06) saturate(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-pixel-grid',
    name: 'CRT Pixel Grid',
    category: 'CRT',
    description: 'Phosphor subpixel color grid mask layout.',
    cssFilter: 'contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-retro-monitor',
    name: 'CRT Retro Monitor',
    category: 'CRT',
    description: '80s personal computer green phosphor display.',
    cssFilter: 'saturate(0.5) contrast(1.1) brightness(1.05) hue-rotate(90deg)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-arcade',
    name: 'CRT Arcade',
    category: 'CRT',
    description: 'Coarse RGB shadow mask and vibrant highlights.',
    cssFilter: 'saturate(1.25) contrast(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-broadcast',
    name: 'CRT Broadcast',
    category: 'CRT',
    description: 'High fidelity studio broadcast monitor look.',
    cssFilter: 'contrast(1.02) saturate(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-console',
    name: 'CRT Console',
    category: 'CRT',
    description: 'Retro game console RF signal color bleed look.',
    cssFilter: 'saturate(1.15) contrast(0.96)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-old-tv',
    name: 'CRT Old Television',
    category: 'CRT',
    description: 'Aged wood frame CRT television simulation.',
    cssFilter: 'sepia(0.08) contrast(0.96) saturate(0.92)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-vintage-display',
    name: 'CRT Vintage Display',
    category: 'CRT',
    description: 'Amber monochrome terminal screen emulation.',
    cssFilter: 'saturate(0.4) contrast(1.15) sepia(0.8) hue-rotate(5deg)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-tube-glow',
    name: 'CRT Tube Glow',
    category: 'CRT',
    description: 'Electron beam backlight screen glow.',
    cssFilter: 'brightness(1.05) saturate(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-reflection',
    name: 'CRT Reflection',
    category: 'CRT',
    description: 'Glass tube surface glare and highlight reflections.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-glass-screen',
    name: 'CRT Glass Screen',
    category: 'CRT',
    description: 'Rounded glass monitor reflections and vignette.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-dust',
    name: 'CRT Dust',
    category: 'CRT',
    description: 'Static dust fibers and hair specs.',
    cssFilter: 'contrast(1.02) brightness(0.99)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-dirty-screen',
    name: 'CRT Dirty Screen',
    category: 'CRT',
    description: 'Smudges and screen stains static layout.',
    cssFilter: 'contrast(1.03) brightness(0.97)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-broken-signal',
    name: 'CRT Broken Signal',
    category: 'CRT',
    description: 'Heavy static raster tears and tracking rolls.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-mag-distortion',
    name: 'CRT Magnetic Distortion',
    category: 'CRT',
    description: 'Warped wave color fringing and skews.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-electron-beam',
    name: 'CRT Electron Beam',
    category: 'CRT',
    description: 'Scanning dot beam focus sweeps.',
    cssFilter: 'brightness(1.06)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'crt-tube-flicker',
    name: 'CRT Tube Flicker',
    category: 'CRT',
    description: 'Coarse backlight electrical voltage flicker.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-monitor-shake',
    name: 'CRT Monitor Shake',
    category: 'CRT',
    description: 'High tension sync signal shaking.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-analog-blur',
    name: 'CRT Analog Blur',
    category: 'CRT',
    description: 'Soft glow outline horizontal scanning blur.',
    cssFilter: 'blur(1.5px) contrast(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-rgb-offset',
    name: 'CRT RGB Offset',
    category: 'CRT',
    description: 'Electron beam convergence shift offsets.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-display-noise',
    name: 'CRT Display Noise',
    category: 'CRT',
    description: 'Phosphor decay color noise specs.',
    cssFilter: 'contrast(1.02) brightness(0.99)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-studio',
    name: 'CRT Studio Monitor',
    category: 'CRT',
    description: 'Studio broadcast grading CRT layout.',
    cssFilter: 'contrast(1.03) saturate(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-premium',
    name: 'CRT Premium',
    category: 'CRT',
    description: 'Perfect convergence scanline retro grading look.',
    cssFilter: 'saturate(1.1) contrast(1.02) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'crt-master',
    name: 'CRT Master',
    category: 'CRT',
    description: 'Definitive professional television tube simulator.',
    cssFilter: 'contrast(1.02) saturate(1.06) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
