import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'horror-haunted',
    name: 'Haunted House',
    category: 'Horror',
    description: 'Eerie shadows and flickering cold lights.',
    cssFilter: 'contrast(1.2) brightness(0.7) saturate(0.6) hue-rotate(180deg)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-ghost',
    name: 'Ghost',
    category: 'Horror',
    description: 'Spectral translucent greenish-blue outline glow.',
    cssFilter: 'contrast(1.1) brightness(0.85) saturate(0.5) hue-rotate(140deg)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'horror-demon',
    name: 'Demon',
    category: 'Horror',
    description: 'Hellish dark red shadows and high contrast.',
    cssFilter: 'contrast(1.35) brightness(0.65) saturate(1.2) sepia(0.2) hue-rotate(-20deg)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-zombie',
    name: 'Zombie',
    category: 'Horror',
    description: 'Decayed toxic green/yellow cinematic grade.',
    cssFilter: 'contrast(1.15) brightness(0.75) saturate(0.7) hue-rotate(90deg)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-vampire',
    name: 'Vampire',
    category: 'Horror',
    description: 'Pale skin tones with high saturation crimson blood red accents.',
    cssFilter: 'contrast(1.25) brightness(0.7) saturate(1.1) sepia(0.15)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-possessed',
    name: 'Possessed',
    category: 'Horror',
    description: 'Twisted vignette outlines and aggressive light flickering.',
    cssFilter: 'contrast(1.3) brightness(0.6) saturate(0.5)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-asylum',
    name: 'Asylum',
    category: 'Horror',
    description: 'Cold dirty grey/cyan fluorescent hospital glow.',
    cssFilter: 'contrast(1.18) brightness(0.78) saturate(0.5) hue-rotate(170deg)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-hospital',
    name: 'Abandoned Hospital',
    category: 'Horror',
    description: 'Heavy grime grain and rapid light blinking.',
    cssFilter: 'contrast(1.15) brightness(0.68) saturate(0.4) hue-rotate(160deg)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-forest',
    name: 'Haunted Forest',
    category: 'Horror',
    description: 'Deep fog layers behind dead pine tree silhouettes.',
    cssFilter: 'contrast(1.05) brightness(0.7) saturate(0.6) hue-rotate(120deg)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-cemetery',
    name: 'Cemetery',
    category: 'Horror',
    description: 'Eerie gravestone cold blue moonlight glow.',
    cssFilter: 'hue-rotate(210deg) saturate(0.6) brightness(0.75) contrast(1.12)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-spirit',
    name: 'Evil Spirit',
    category: 'Horror',
    description: 'Shifting screen glitching overlays and high contrast shadow movements.',
    cssFilter: 'contrast(1.3) brightness(0.65) saturate(0.75)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-nightmare',
    name: 'Nightmare',
    category: 'Horror',
    description: 'Surreal dark violet/magenta nightmare space.',
    cssFilter: 'hue-rotate(270deg) saturate(1.2) brightness(0.6) contrast(1.25)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-cursed',
    name: 'Cursed Video',
    category: 'Horror',
    description: 'Damaged VCR static noise and heavy glitches.',
    cssFilter: 'contrast(1.2) brightness(0.7) saturate(0.5) blur(0.3px)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'horror-ritual',
    name: 'Dark Ritual',
    category: 'Horror',
    description: 'Occult blood-red candlelight glow and dark shadows.',
    cssFilter: 'sepia(0.3) saturate(1.4) brightness(0.65) contrast(1.3) hue-rotate(-30deg)',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-silenthill',
    name: 'Silent Hill',
    category: 'Horror',
    description: 'Dense screen ash fog and rusty metal colors.',
    cssFilter: 'sepia(0.2) contrast(0.95) brightness(0.75) saturate(0.7)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-fog',
    name: 'Fog Horror',
    category: 'Horror',
    description: 'Thick white/grey volumetric fog masking shadows.',
    cssFilter: 'blur(0.5px) contrast(0.9) brightness(0.78)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-bloodmoon',
    name: 'Blood Moon',
    category: 'Horror',
    description: 'Intense crimson red environmental night glow.',
    cssFilter: 'hue-rotate(345deg) saturate(1.5) brightness(0.65) contrast(1.2)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-movie',
    name: 'Horror Movie',
    category: 'Horror',
    description: 'Cinematic wide aspect ratio dark thriller filter.',
    cssFilter: 'contrast(1.1) brightness(0.72) saturate(0.8) sepia(0.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-paranormal',
    name: 'Paranormal Activity',
    category: 'Horror',
    description: 'Green CCTV night vision camera look with subtle grid line shadows.',
    cssFilter: 'hue-rotate(95deg) saturate(1.3) brightness(0.85) contrast(1.15)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-psychological',
    name: 'Psychological Horror',
    category: 'Horror',
    description: 'Distorted breathing perspective shift and cold shadows.',
    cssFilter: 'contrast(1.25) brightness(0.7) saturate(0.7)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'horror-custom',
    name: 'Custom Horror',
    category: 'Horror',
    description: 'Fully configurable cinematic horror scene.',
    cssFilter: 'brightness(0.7) contrast(1.2)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  }
];

// Generate remainder to have exactly 50 horror presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `horror-preset-${i}`,
    name: `Horror Element ${i}`,
    category: 'Horror',
    description: `Cinematic horror preset variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 12) % 360}deg) brightness(${0.6 + (i % 3) * 0.05}) contrast(${1.1 + (i % 4) * 0.05})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 15 + (i % 7) * 4,
    defaultAngle: (i * 18) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  });
}

export const HORROR_EFFECTS = list;
