import { EffectPreset } from './effectsPreset';

export const LENS_EFFECTS: EffectPreset[] = [
  {
    id: 'lens-distortion',
    name: 'Lens Distortion',
    category: 'Lens',
    description: 'Simulates camera lens radial distortion warp.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-fisheye',
    name: 'Fisheye',
    category: 'Lens',
    description: 'Extreme barrel distortion simulating fisheye lenses.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-wide-angle',
    name: 'Wide Angle',
    category: 'Lens',
    description: 'Slight wide-angle curvature perspective stretch.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-ultra-wide',
    name: 'Ultra Wide',
    category: 'Lens',
    description: 'High-intensity ultra-wide field of view expansion.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-telephoto',
    name: 'Telephoto',
    category: 'Lens',
    description: 'Flattens perspective zooming into center.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-macro-focus',
    name: 'Macro Focus',
    category: 'Lens',
    description: 'Extremely shallow depth blur focusing macro detail.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-breathing',
    name: 'Focus Breathing',
    category: 'Lens',
    description: 'Simulates focal length changes while focusing.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-rack-focus',
    name: 'Rack Focus Lens',
    category: 'Lens',
    description: 'Simulates focus pull transitions from blur to sharp.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-zoom',
    name: 'Lens Zoom',
    category: 'Lens',
    description: 'Standard optical focal zoom scaling.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-stretch',
    name: 'Lens Stretch',
    category: 'Lens',
    description: 'Anamorphic horizontal field stretch squeeze.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-compression',
    name: 'Lens Compression',
    category: 'Lens',
    description: 'Simulates optical focal perspective compression.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-warp',
    name: 'Lens Warp',
    category: 'Lens',
    description: 'Swirling glass refractive warp centers.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-twist',
    name: 'Lens Twist',
    category: 'Lens',
    description: 'Circular lens vortex rotational twist.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-barrel',
    name: 'Barrel Distortion',
    category: 'Lens',
    description: 'Outward bulging lens geometry curve.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-pincushion',
    name: 'Pincushion Distortion',
    category: 'Lens',
    description: 'Inward pinching lens geometry curve.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-chromatic',
    name: 'Chromatic Aberration',
    category: 'Lens',
    description: 'Splits red and blue outline refractions.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-prism',
    name: 'Prism Lens',
    category: 'Lens',
    description: 'Triangular multi-faceted prism glass split.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-crystal',
    name: 'Crystal Lens',
    category: 'Lens',
    description: 'Refracted crystalline glass block filters.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-glass-refract',
    name: 'Glass Refraction',
    category: 'Lens',
    description: 'Organic sheet glass light refractions.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-water-drop',
    name: 'Water Drop Lens',
    category: 'Lens',
    description: 'Simulates water condensation drops on lens glass.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-rain',
    name: 'Rain Lens',
    category: 'Lens',
    description: 'Rain splatters wash elements over lens screen.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-foggy',
    name: 'Foggy Lens',
    category: 'Lens',
    description: 'Misty humid condensation fogging screen.',
    cssFilter: 'blur(3px) contrast(0.92) brightness(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-frost',
    name: 'Frost Lens',
    category: 'Lens',
    description: 'Crystalline ice frost forming around edges.',
    cssFilter: 'contrast(1.05) saturate(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-dirt',
    name: 'Lens Dirt',
    category: 'Lens',
    description: 'Vintage optical element dirt overlay.',
    cssFilter: 'contrast(1.02) brightness(0.97)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-dust',
    name: 'Lens Dust',
    category: 'Lens',
    description: 'Faint circular dust particles inside glass barrels.',
    cssFilter: 'contrast(1.01)',
    defaultIntensity: 35,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-scratch',
    name: 'Lens Scratch',
    category: 'Lens',
    description: 'Hairlines and physical optical lens element scratches.',
    cssFilter: 'contrast(1.05) brightness(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-crack',
    name: 'Lens Crack',
    category: 'Lens',
    description: 'Simulates physical shattered glass cracks.',
    cssFilter: 'contrast(1.06)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-ghost',
    name: 'Ghost Reflection',
    category: 'Lens',
    description: 'Anamorphic light reflection ghosts sways.',
    cssFilter: 'brightness(1.02) saturate(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-reflection',
    name: 'Lens Reflection',
    category: 'Lens',
    description: 'Aperture blades optical light reflection.',
    cssFilter: 'brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-glow',
    name: 'Lens Glow',
    category: 'Lens',
    description: 'Soft halo optical highlight bloom glows.',
    cssFilter: 'brightness(1.08) saturate(1.04)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-circular',
    name: 'Circular Reflection',
    category: 'Lens',
    description: 'Halo circular lens ring flare reflections.',
    cssFilter: 'brightness(1.04) sepia(0.05)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-bokeh-hex',
    name: 'Hexagonal Bokeh',
    category: 'Lens',
    description: 'Simulates 6-blade aperture hexagonal light circles.',
    cssFilter: 'brightness(1.05) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-bokeh-round',
    name: 'Round Bokeh',
    category: 'Lens',
    description: 'Standard round aperture bokeh light pulls.',
    cssFilter: 'brightness(1.05) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-bokeh-oval',
    name: 'Oval Bokeh',
    category: 'Lens',
    description: 'Anamorphic oval aperture bokeh light pulls.',
    cssFilter: 'brightness(1.05) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-bokeh-cat',
    name: 'Cat Eye Bokeh',
    category: 'Lens',
    description: 'Swirling peripheral cat-eye bokeh distortions.',
    cssFilter: 'brightness(1.05) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'lens-vignette',
    name: 'Lens Vignette',
    category: 'Lens',
    description: 'Dark barrel-rimmed vignette border shadow.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-optical-blur',
    name: 'Optical Blur',
    category: 'Lens',
    description: 'Aperture-accurate visual out-of-focus blur.',
    cssFilter: 'blur(4px)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-cinema',
    name: 'Cinema Lens',
    category: 'Lens',
    description: 'Hollywood cinema anamorphic optical look.',
    cssFilter: 'contrast(1.06) saturate(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-vintage',
    name: 'Vintage Lens',
    category: 'Lens',
    description: 'Warm low-contrast vintage glass grade.',
    cssFilter: 'sepia(0.18) contrast(0.95) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-soft-glass',
    name: 'Soft Glass',
    category: 'Lens',
    description: 'Diffuses highlight peaks through soft glass overlays.',
    cssFilter: 'brightness(1.04) contrast(0.95)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-split-diopter',
    name: 'Split Diopter',
    category: 'Lens',
    description: 'Bifocal split diopter focus screen layout.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-tilt',
    name: 'Tilt Lens',
    category: 'Lens',
    description: 'Perspective tilting plane selective focus.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-focus-ring',
    name: 'Focus Ring',
    category: 'Lens',
    description: 'Visual circular focus search target ring.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-drift',
    name: 'Optical Drift',
    category: 'Lens',
    description: 'Simulates micro focal sways and sags.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-pulse',
    name: 'Lens Pulse',
    category: 'Lens',
    description: 'Pulsates the lens scale dynamically.',
    cssFilter: 'none',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-refract-wave',
    name: 'Refraction Wave',
    category: 'Lens',
    description: 'Watery moving refractive sways.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-mirage',
    name: 'Optical Mirage',
    category: 'Lens',
    description: 'Desert optical mirage double reflections.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-premium-glass',
    name: 'Premium Glass',
    category: 'Lens',
    description: 'Ultra-low chromatic aberration prime grade.',
    cssFilter: 'contrast(1.04) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-prime',
    name: 'Cinema Prime Lens',
    category: 'Lens',
    description: 'Signature cinema fixed prime glass emulation.',
    cssFilter: 'contrast(1.08) saturate(1.02) brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'lens-master',
    name: 'Lens Master',
    category: 'Lens',
    description: 'Definitive professional lens synthesis overlay.',
    cssFilter: 'contrast(1.06) saturate(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
