import { EffectPreset } from './effectsPreset';

export const LIGHT_EFFECTS: EffectPreset[] = [
  {
    id: 'light-sun-glow',
    name: 'Sun Glow',
    category: 'Light',
    description: 'Simulates a bright warm solar glow source.',
    cssFilter: 'brightness(1.1) saturate(1.1) sepia(0.08)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-golden-glow',
    name: 'Golden Glow',
    category: 'Light',
    description: 'Warm ambient golden light overlay.',
    cssFilter: 'brightness(1.08) saturate(1.15) sepia(0.18)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-blue-glow',
    name: 'Blue Glow',
    category: 'Light',
    description: 'Cool blue ambient sci-fi glow overlay.',
    cssFilter: 'brightness(1.05) saturate(1.08) hue-rotate(185deg)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-white-glow',
    name: 'White Glow',
    category: 'Light',
    description: 'Clean high-exposure white illumination wash.',
    cssFilter: 'brightness(1.15)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-neon-glow',
    name: 'Neon Glow',
    category: 'Light',
    description: 'Electric cyber neon highlights glow bleed.',
    cssFilter: 'brightness(1.1) saturate(1.25) contrast(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-edge-glow',
    name: 'Edge Glow',
    category: 'Light',
    description: 'Generates a soft glow on high-contrast edges.',
    cssFilter: 'brightness(1.03) contrast(1.04)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'light-soft-glow',
    name: 'Soft Glow',
    category: 'Light',
    description: 'Smooth low-frequency illumination wash.',
    cssFilter: 'brightness(1.06) saturate(1.02)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'light-bloom',
    name: 'Bloom',
    category: 'Light',
    description: 'Spreads bright pixels into neighboring areas.',
    cssFilter: 'brightness(1.1) contrast(1.08) saturate(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-soft-bloom',
    name: 'Soft Bloom',
    category: 'Light',
    description: 'Muted high-threshold highlight glow expansion.',
    cssFilter: 'brightness(1.05) contrast(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-hdr-bloom',
    name: 'HDR Bloom',
    category: 'Light',
    description: 'High dynamic range hyper-bright glow wash.',
    cssFilter: 'brightness(1.2) contrast(1.15) saturate(1.1)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-lens-glow',
    name: 'Lens Glow',
    category: 'Light',
    description: 'Highlights flare glow reflection.',
    cssFilter: 'brightness(1.08) saturate(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-rainbow-glow',
    name: 'Rainbow Glow',
    category: 'Light',
    description: 'Spectrally refracted chromatic light wash.',
    cssFilter: 'brightness(1.08) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-color-glow',
    name: 'Color Glow',
    category: 'Light',
    description: 'Adjustable solid tint ambient wash glow.',
    cssFilter: 'brightness(1.05) saturate(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-ambient-glow',
    name: 'Ambient Glow',
    category: 'Light',
    description: 'Fills the frame with soft environmental glow.',
    cssFilter: 'brightness(1.08) saturate(1.03)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'light-backlight',
    name: 'Backlight',
    category: 'Light',
    description: 'Luminous edge highlight simulation from behind.',
    cssFilter: 'brightness(1.06) contrast(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-rim-light',
    name: 'Rim Light',
    category: 'Light',
    description: 'Draws sharp bright highlights on subject borders.',
    cssFilter: 'contrast(1.08) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-spotlight',
    name: 'Spotlight',
    category: 'Light',
    description: 'Radial focus spotlight beam mask.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'light-stage-light',
    name: 'Stage Light',
    category: 'Light',
    description: 'Animated stage color spot beams.',
    cssFilter: 'brightness(1.05) saturate(1.08)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-flashlight',
    name: 'Flash Light',
    category: 'Light',
    description: 'Simulates center flash beam tracking.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'light-camera-flash',
    name: 'Camera Flash',
    category: 'Light',
    description: 'Triggers a bright exposure decay burst.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-sweep',
    name: 'Light Sweep',
    category: 'Light',
    description: 'Sweeps a sharp beam of light across frame.',
    cssFilter: 'brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 120,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-glow-sweep',
    name: 'Glow Sweep',
    category: 'Light',
    description: 'Sweeps a soft glow wash across frame.',
    cssFilter: 'brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 120,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-burst',
    name: 'Light Burst',
    category: 'Light',
    description: 'Extreme radial beam burst from center.',
    cssFilter: 'brightness(1.15) contrast(1.1) saturate(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-starburst',
    name: 'Star Burst',
    category: 'Light',
    description: 'Simulates camera lens diffraction spikes.',
    cssFilter: 'brightness(1.08) saturate(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-spark-glow',
    name: 'Spark Glow',
    category: 'Light',
    description: 'Luminous tiny spark dust highlights.',
    cssFilter: 'contrast(1.02) brightness(1.04)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-fire-glow',
    name: 'Fire Glow',
    category: 'Light',
    description: 'Flickering orange bonfire glow simulation.',
    cssFilter: 'brightness(1.08) saturate(1.15) sepia(0.2) contrast(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-candle',
    name: 'Candle Glow',
    category: 'Light',
    description: 'Low-frequency warm amber candle flicker.',
    cssFilter: 'brightness(1.03) saturate(1.08) sepia(0.12)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-moon-glow',
    name: 'Moon Glow',
    category: 'Light',
    description: 'Slightly blue night glow highlights.',
    cssFilter: 'brightness(0.9) contrast(1.05) saturate(0.85) sepia(0.05) hue-rotate(190deg)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-aurora',
    name: 'Aurora Glow',
    category: 'Light',
    description: 'Animated green-magenta northern lights glow.',
    cssFilter: 'brightness(1.06) saturate(1.1) hue-rotate(90deg)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-god-rays',
    name: 'God Rays',
    category: 'Light',
    description: 'Volumetric light rays stretching downwards.',
    cssFilter: 'brightness(1.1) contrast(1.08) sepia(0.08)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 60,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-volumetric',
    name: 'Volumetric Light',
    category: 'Light',
    description: 'Luminous light rays simulation through dusty air.',
    cssFilter: 'brightness(1.08) contrast(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-sunrays',
    name: 'Sun Rays',
    category: 'Light',
    description: 'Warm solar rays wash.',
    cssFilter: 'brightness(1.12) sepia(0.15) saturate(1.1)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-window',
    name: 'Window Light',
    category: 'Light',
    description: 'Projected window frame light beam overlays.',
    cssFilter: 'brightness(1.06) contrast(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-pulse',
    name: 'Glow Pulse',
    category: 'Light',
    description: 'Pulsates glow radius periodically.',
    cssFilter: 'brightness(1.08) saturate(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-flicker',
    name: 'Glow Flicker',
    category: 'Light',
    description: 'Organic flickering of active glow levels.',
    cssFilter: 'brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-glow-wave',
    name: 'Glow Wave',
    category: 'Light',
    description: 'Oscillating wave motion glow offsets.',
    cssFilter: 'brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-electric',
    name: 'Electric Glow',
    category: 'Light',
    description: 'High-frequency electric cyan discharges glow.',
    cssFilter: 'brightness(1.15) saturate(1.3) hue-rotate(180deg)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-energy',
    name: 'Energy Glow',
    category: 'Light',
    description: 'Glowing magical energy lines overlay.',
    cssFilter: 'brightness(1.1) saturate(1.2)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-magic',
    name: 'Magic Glow',
    category: 'Light',
    description: 'Dreamy soft pastel fantasy glow washes.',
    cssFilter: 'brightness(1.12) saturate(1.15) sepia(0.06)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-holographic',
    name: 'Holographic Glow',
    category: 'Light',
    description: 'Glowing blue-cyan cyber hologram sweeps.',
    cssFilter: 'brightness(1.08) saturate(1.18) hue-rotate(175deg)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-crystal',
    name: 'Crystal Glow',
    category: 'Light',
    description: 'Crystalline refracted glow highlights.',
    cssFilter: 'brightness(1.08) contrast(1.08)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-diamond-shine',
    name: 'Diamond Shine',
    category: 'Light',
    description: 'Spanning diamond reflection glares.',
    cssFilter: 'brightness(1.12) contrast(1.1)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-ripple',
    name: 'Light Ripple',
    category: 'Light',
    description: 'Expanding wave concentric light ripples.',
    cssFilter: 'brightness(1.05) contrast(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-soft-reflect',
    name: 'Soft Reflection',
    category: 'Light',
    description: 'Glossy glass layer reflection glows.',
    cssFilter: 'brightness(1.05) saturate(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-halo',
    name: 'Glow Halo',
    category: 'Light',
    description: 'Concentric halo ring flare overlays.',
    cssFilter: 'brightness(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-premium-bloom',
    name: 'Premium Bloom',
    category: 'Light',
    description: 'Hollywood bloom filter emulation.',
    cssFilter: 'brightness(1.12) contrast(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-cinema',
    name: 'Cinema Light',
    category: 'Light',
    description: 'Anamorphic blue lens flare lights.',
    cssFilter: 'brightness(1.04) saturate(1.06) hue-rotate(185deg)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-luxury',
    name: 'Luxury Glow',
    category: 'Light',
    description: 'Warm gold premium brand glow grade.',
    cssFilter: 'brightness(1.1) sepia(0.12) saturate(1.12) contrast(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-fusion',
    name: 'Light Fusion',
    category: 'Light',
    description: 'Emits volumetric blending rays sweeps.',
    cssFilter: 'brightness(1.08) saturate(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'light-master',
    name: 'Glow Master',
    category: 'Light',
    description: 'Definitive professional light glow synthesizing.',
    cssFilter: 'brightness(1.1) saturate(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  }
];
