import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'nature-forest',
    name: 'Forest',
    category: 'Nature',
    description: 'Deep green forest canopy shadows and light beams.',
    cssFilter: 'contrast(1.02) saturate(1.15) brightness(0.95) sepia(0.05)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-jungle',
    name: 'Jungle',
    category: 'Nature',
    description: 'Dense tropical jungle leaves and steam humidity.',
    cssFilter: 'contrast(1.05) saturate(1.25) brightness(0.92)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-rainforest',
    name: 'Rainforest',
    category: 'Nature',
    description: 'Drifting mist clouds and dark saturated mossy tones.',
    cssFilter: 'contrast(1.08) saturate(1.2) brightness(0.9)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-mountains',
    name: 'Mountains',
    category: 'Nature',
    description: 'Epic peaks silhouette outline shadows.',
    cssFilter: 'contrast(0.95) brightness(0.98) saturate(0.9)',
    defaultIntensity: 40,
    defaultOpacity: 80,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-waterfall',
    name: 'Waterfall',
    category: 'Nature',
    description: 'Vertical cascading white water splash and mist layers.',
    cssFilter: 'contrast(0.98) brightness(1.02) saturate(0.95)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 45,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-river',
    name: 'River',
    category: 'Nature',
    description: 'Shifting horizontal river surface glares.',
    cssFilter: 'contrast(1.03) brightness(1.01)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-lake',
    name: 'Lake',
    category: 'Nature',
    description: 'Calm water mirror reflection and blue tones.',
    cssFilter: 'hue-rotate(190deg) saturate(1.1) brightness(0.98)',
    defaultIntensity: 35,
    defaultOpacity: 75,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-ocean',
    name: 'Ocean',
    category: 'Nature',
    description: 'Deep marine turquoise depths water overlay.',
    cssFilter: 'hue-rotate(200deg) saturate(1.3) brightness(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-beach',
    name: 'Beach',
    category: 'Nature',
    description: 'Sunny warm sand tones and bright ocean sunbeams.',
    cssFilter: 'sepia(0.12) saturate(1.2) brightness(1.08) contrast(1.02)',
    defaultIntensity: 40,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-meadow',
    name: 'Meadow',
    category: 'Nature',
    description: 'Gently waving grass blades and wild flower spots.',
    cssFilter: 'saturate(1.2) brightness(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-greenfield',
    name: 'Green Field',
    category: 'Nature',
    description: 'Vibrant green lawn tones under warm sunshine.',
    cssFilter: 'saturate(1.3) brightness(1.05) contrast(1.03)',
    defaultIntensity: 40,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-cherry-blossom',
    name: 'Cherry Blossom',
    category: 'Nature',
    description: 'Drifting pink cherry blossom petals.',
    cssFilter: 'hue-rotate(330deg) saturate(1.2) brightness(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-autumn',
    name: 'Autumn Forest',
    category: 'Nature',
    description: 'Drifting orange, red, and yellow autumn leaves.',
    cssFilter: 'sepia(0.25) saturate(1.3) brightness(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 18,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-winter',
    name: 'Winter Forest',
    category: 'Nature',
    description: 'Cold frost border and falling winter snow flakes.',
    cssFilter: 'saturate(0.7) brightness(1.03) contrast(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-spring',
    name: 'Spring Garden',
    category: 'Nature',
    description: 'Light pastel flower petals drifting horizontally.',
    cssFilter: 'saturate(1.25) brightness(1.06)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-summer',
    name: 'Summer Landscape',
    category: 'Nature',
    description: 'High saturation and warm lens glare sun rays.',
    cssFilter: 'saturate(1.35) brightness(1.1) contrast(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 95,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-desert',
    name: 'Desert',
    category: 'Nature',
    description: 'Arid sepia sun heat waves and blowing sand grains.',
    cssFilter: 'sepia(0.4) saturate(1.15) brightness(0.95) contrast(0.92)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 35,
    defaultAngle: 15,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay'
  },
  {
    id: 'nature-canyon',
    name: 'Canyon',
    category: 'Nature',
    description: 'Red sandstone warm dust tones.',
    cssFilter: 'sepia(0.3) saturate(1.3) brightness(0.92) contrast(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-cave',
    name: 'Cave',
    category: 'Nature',
    description: 'Dark rocky shadows and cool blue water droplets.',
    cssFilter: 'brightness(0.7) contrast(1.15) saturate(0.8)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 12,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'nature-bamboo',
    name: 'Bamboo Forest',
    category: 'Nature',
    description: 'Tall bamboo green light ray paths.',
    cssFilter: 'hue-rotate(100deg) saturate(1.15) brightness(0.96)',
    defaultIntensity: 45,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-tropical',
    name: 'Tropical Island',
    category: 'Nature',
    description: 'Turquoise ocean water glares and bright palm shade.',
    cssFilter: 'hue-rotate(185deg) saturate(1.3) brightness(1.08)',
    defaultIntensity: 40,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-pine',
    name: 'Pine Forest',
    category: 'Nature',
    description: 'Deep evergreen trees outline mask and mist haze.',
    cssFilter: 'hue-rotate(110deg) saturate(0.9) brightness(0.9) contrast(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-sunset',
    name: 'Sunset Nature',
    category: 'Nature',
    description: 'Stunning warm red forest sunset glow.',
    cssFilter: 'sepia(0.2) hue-rotate(-20deg) saturate(1.3) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 95,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-sunrise',
    name: 'Sunrise Nature',
    category: 'Nature',
    description: 'Soft early morning mist and pink sunbeams.',
    cssFilter: 'sepia(0.15) hue-rotate(-10deg) saturate(1.2) brightness(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 90,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-aurora',
    name: 'Aurora Forest',
    category: 'Nature',
    description: 'Breathtaking green northern lights behind silhouettes of pine trees.',
    cssFilter: 'hue-rotate(120deg) saturate(1.4) brightness(1.1)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-moonlit',
    name: 'Moonlit Forest',
    category: 'Nature',
    description: 'Mysterious cool blue-grey night forest lighting.',
    cssFilter: 'hue-rotate(200deg) saturate(0.6) brightness(0.8) contrast(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-wildlife',
    name: 'Wildlife Trails',
    category: 'Nature',
    description: 'Drifting butterfly/firefly particles and natural depth.',
    cssFilter: 'saturate(1.1) brightness(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'nature-paradise',
    name: 'Paradise Garden',
    category: 'Nature',
    description: 'Dreamy soft blooms and glowing flower spots.',
    cssFilter: 'saturate(1.25) brightness(1.08) contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-fantasy',
    name: 'Fantasy Nature',
    category: 'Nature',
    description: 'Blowing magical purple/blue sparkles and glowing trees.',
    cssFilter: 'hue-rotate(260deg) saturate(1.35) brightness(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'nature-custom',
    name: 'Custom Nature',
    category: 'Nature',
    description: 'User-configurable ecosystems and elements.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];

// Generate remainder to have exactly 50 nature presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `nature-preset-${i}`,
    name: `Nature Element ${i}`,
    category: 'Nature',
    description: `Dynamic environmental preset variant #${i}.`,
    cssFilter: `hue-rotate(${i % 15}deg) saturate(${1.0 + (i % 4) * 0.05}) brightness(${0.95 + (i % 3) * 0.03})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 15 + (i % 7) * 4,
    defaultAngle: (i * 18) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  });
}

export const NATURE_EFFECTS = list;
