import { EffectPreset } from './effectsPreset';

export const VHS_EFFECTS: EffectPreset[] = [
  {
    id: 'vhs-classic',
    name: 'VHS Classic',
    category: 'VHS',
    description: 'Timeless classic VCR home video tape emulation.',
    cssFilter: 'contrast(0.96) saturate(0.98) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tracking',
    name: 'VHS Tracking',
    category: 'VHS',
    description: 'Analog tracking distortion bars and head ripples.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-noise',
    name: 'VHS Noise',
    category: 'VHS',
    description: 'Static screen tracking noise lines.',
    cssFilter: 'contrast(1.02) brightness(1.01)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-static',
    name: 'VHS Static',
    category: 'VHS',
    description: 'Simulates white noise signal static snow.',
    cssFilter: 'contrast(1.04) brightness(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-distortion',
    name: 'VHS Distortion',
    category: 'VHS',
    description: 'Skewed horizontal tracking head switching warp.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-color-bleed',
    name: 'VHS Color Bleed',
    category: 'VHS',
    description: 'Fuzzy red color bleeding chroma offsets.',
    cssFilter: 'saturate(1.2) contrast(0.98)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-scanlines',
    name: 'VHS Scanlines',
    category: 'VHS',
    description: 'Classic CRT scanning phosphor beams line layout.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-grain',
    name: 'VHS Tape Grain',
    category: 'VHS',
    description: 'Coarse magnetic oxide grain sways.',
    cssFilter: 'contrast(1.03)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-warp',
    name: 'VHS Tape Warp',
    category: 'VHS',
    description: 'Slowing wavy tracking phase distortions.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-head-switching',
    name: 'VHS Head Switching',
    category: 'VHS',
    description: 'Jittery bottom frame head switching bar noise.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-dropout',
    name: 'VHS Dropout',
    category: 'VHS',
    description: 'Simulates physical tape oxide drops glitches.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-signal-loss',
    name: 'VHS Signal Loss',
    category: 'VHS',
    description: 'Intermittent signal sync loss screen roll.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-color-shift',
    name: 'VHS Color Shift',
    category: 'VHS',
    description: 'Misaligned RGB outlines analog color phase.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-ghosting',
    name: 'VHS Ghosting',
    category: 'VHS',
    description: 'Simulates magnetic ghosting shadow reflections.',
    cssFilter: 'contrast(0.96) saturate(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-blur',
    name: 'VHS Blur',
    category: 'VHS',
    description: 'Slightly low resolution analog magnetic blur.',
    cssFilter: 'blur(1.2px) contrast(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-stretch',
    name: 'VHS Tape Stretch',
    category: 'VHS',
    description: 'Stretches tracking scan lines vertically.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-damage',
    name: 'VHS Tape Damage',
    category: 'VHS',
    description: 'Shattered composite oxide specs overlays.',
    cssFilter: 'contrast(1.05)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-fold',
    name: 'VHS Tape Fold',
    category: 'VHS',
    description: 'Simulates folded tape frame rolls.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 180,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-wrinkle',
    name: 'VHS Tape Wrinkle',
    category: 'VHS',
    description: 'Wavy tracking screen wrinkles.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-scratch',
    name: 'VHS Tape Scratch',
    category: 'VHS',
    description: 'Fine vertical magnetic tracking lines.',
    cssFilter: 'contrast(1.04) brightness(0.99)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tape-burn',
    name: 'VHS Tape Burn',
    category: 'VHS',
    description: 'Hot spot composite signal orange burns.',
    cssFilter: 'brightness(1.04)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'vhs-rewind',
    name: 'VHS Rewind',
    category: 'VHS',
    description: 'Simulates VCR fast rewinding horizontal noise.',
    cssFilter: 'contrast(1.08) brightness(1.05)',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-fast-forward',
    name: 'VHS Fast Forward',
    category: 'VHS',
    description: 'Simulates VCR fast forwarding horizontal noise.',
    cssFilter: 'contrast(1.08) brightness(1.05)',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-pause',
    name: 'VHS Pause',
    category: 'VHS',
    description: 'Simulates VCR static paused screen freeze.',
    cssFilter: 'contrast(1.04)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-play',
    name: 'VHS Play',
    category: 'VHS',
    description: 'Clean classic play graphics indicators.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-stop',
    name: 'VHS Stop',
    category: 'VHS',
    description: 'Blue screen stop graphics indicators.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-tracking-error',
    name: 'VHS Tracking Error',
    category: 'VHS',
    description: 'Unadjusted tracking head bar distortions.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-channel-change',
    name: 'VHS Channel Change',
    category: 'VHS',
    description: 'Static flicker screen rolls change simulation.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-analog-glow',
    name: 'VHS Analog Glow',
    category: 'VHS',
    description: 'CRT phosphor tube ambient glows.',
    cssFilter: 'brightness(1.08) saturate(1.06)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'vhs-analog-flicker',
    name: 'VHS Analog Flicker',
    category: 'VHS',
    description: 'Rapid phosphor decay scanning flicker.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-mag-distortion',
    name: 'VHS Magnetic Distortion',
    category: 'VHS',
    description: 'Skewed waves magnetic fringe displacement.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-wave',
    name: 'VHS Wave',
    category: 'VHS',
    description: 'Continuous slowing tracking wave warp.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-horiz-roll',
    name: 'VHS Horizontal Roll',
    category: 'VHS',
    description: 'Sweeps coordinate frames horizontally.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-vert-hold',
    name: 'VHS Vertical Hold',
    category: 'VHS',
    description: 'Continuous vertical rolling frame hold.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-rgb-offset',
    name: 'VHS RGB Offset',
    category: 'VHS',
    description: 'Chroma split offset tracking alignment.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-color-noise',
    name: 'VHS Color Noise',
    category: 'VHS',
    description: 'Analog composite signal colored noise.',
    cssFilter: 'contrast(1.02) brightness(0.99)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-compression',
    name: 'VHS Compression',
    category: 'VHS',
    description: 'Blocky early digital VCD conversion.',
    cssFilter: 'contrast(0.98) brightness(1.01)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-crt-sync',
    name: 'VHS CRT Sync',
    category: 'VHS',
    description: 'CRT TV screen sync bar scanline.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-dust',
    name: 'VHS Dust',
    category: 'VHS',
    description: 'Vintage tape head dust specs overlay.',
    cssFilter: 'contrast(1.02) brightness(0.99)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-dirty-tape',
    name: 'VHS Dirty Tape',
    category: 'VHS',
    description: 'Heavy composite signal noise and specs.',
    cssFilter: 'contrast(1.03) brightness(0.97)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-home-video',
    name: 'VHS Home Video',
    category: 'VHS',
    description: 'Warm polaroid home recording grade.',
    cssFilter: 'sepia(0.12) contrast(0.96) saturate(1.15)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-camcorder',
    name: 'VHS Camcorder',
    category: 'VHS',
    description: 'Simulates 80s handycam camcorder looks.',
    cssFilter: 'sepia(0.08) contrast(1.02) saturate(1.2)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-recording',
    name: 'VHS Recording',
    category: 'VHS',
    description: 'Camera recording indicators red dot overlay.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-analog-cam',
    name: 'VHS Analog Camera',
    category: 'VHS',
    description: 'Disposable color camcorder simulation.',
    cssFilter: 'sepia(0.14) contrast(0.98) saturate(1.12)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-timecode',
    name: 'VHS Timecode',
    category: 'VHS',
    description: 'VCR timecode character display layout overlay.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-retro-tv',
    name: 'VHS Retro TV',
    category: 'VHS',
    description: 'Simulates aged vintage CRT TV displays.',
    cssFilter: 'contrast(1.04) sepia(0.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-analog-signal',
    name: 'VHS Analog Signal',
    category: 'VHS',
    description: 'Raw composite signal sync roll sways.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-premium',
    name: 'VHS Premium',
    category: 'VHS',
    description: 'Warm premium brand video tape look.',
    cssFilter: 'sepia(0.08) contrast(1.02) saturate(1.1) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-studio',
    name: 'VHS Studio',
    category: 'VHS',
    description: 'Studio console VCR playback emulation.',
    cssFilter: 'contrast(1.04) saturate(1.05) brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'vhs-master',
    name: 'VHS Master',
    category: 'VHS',
    description: 'Definitive professional composite tape format synthesizers.',
    cssFilter: 'sepia(0.05) contrast(0.98) saturate(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
