import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'weather-sunny',
    name: 'Sunny',
    category: 'Weather',
    description: 'Bright sunbeams with high environment light.',
    cssFilter: 'brightness(1.15) saturate(1.1) contrast(1.05)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-cloudy',
    name: 'Cloudy',
    category: 'Weather',
    description: 'Soft cloud shadows and lower exposure.',
    cssFilter: 'contrast(0.95) brightness(0.95) saturate(0.9)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'weather-overcast',
    name: 'Overcast',
    category: 'Weather',
    description: 'Dull grey sky with flat lighting and soft shadows.',
    cssFilter: 'contrast(0.9) brightness(0.9) saturate(0.8) sepia(0.05)',
    defaultIntensity: 60,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'weather-rain',
    name: 'Rain',
    category: 'Weather',
    description: 'Moderate falling rain particles and wind sways.',
    cssFilter: 'contrast(0.93) brightness(0.92) saturate(0.85)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 45,
    defaultAngle: 75,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-heavy-rain',
    name: 'Heavy Rain',
    category: 'Weather',
    description: 'Dense sheets of torrential downpour.',
    cssFilter: 'contrast(0.9) brightness(0.88) saturate(0.8)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 60,
    defaultAngle: 80,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-thunderstorm',
    name: 'Thunderstorm',
    category: 'Weather',
    description: 'Dark storm with torrential rain and lightning flickers.',
    cssFilter: 'contrast(1.1) brightness(0.8) saturate(0.75)',
    defaultIntensity: 80,
    defaultOpacity: 95,
    defaultSpeed: 50,
    defaultAngle: 75,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-lightning',
    name: 'Lightning Storm',
    category: 'Weather',
    description: 'Intense flashing blue-white lightning bolts.',
    cssFilter: 'brightness(1.0) contrast(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-snow',
    name: 'Snow',
    category: 'Weather',
    description: 'Softly falling winter snow crystals.',
    cssFilter: 'brightness(1.02) contrast(0.98) saturate(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-blizzard',
    name: 'Blizzard',
    category: 'Weather',
    description: 'Heavy blowing snow storm with high wind velocity.',
    cssFilter: 'contrast(0.85) brightness(0.95) blur(0.5px)',
    defaultIntensity: 85,
    defaultOpacity: 95,
    defaultSpeed: 65,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-fog',
    name: 'Fog',
    category: 'Weather',
    description: 'Thick white ground fog obscuring distant objects.',
    cssFilter: 'blur(1px) contrast(0.85) brightness(1.02)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-mist',
    name: 'Mist',
    category: 'Weather',
    description: 'Thin transparent morning mist haze.',
    cssFilter: 'contrast(0.95) brightness(1.01)',
    defaultIntensity: 40,
    defaultOpacity: 70,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-haze',
    name: 'Haze',
    category: 'Weather',
    description: 'Atmospheric heat or dust suspension haze.',
    cssFilter: 'contrast(0.9) sepia(0.1) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 75,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-wind',
    name: 'Windy',
    category: 'Weather',
    description: 'Drifting dust lines showing high wind movement.',
    cssFilter: 'contrast(0.98) brightness(1.01)',
    defaultIntensity: 45,
    defaultOpacity: 70,
    defaultSpeed: 55,
    defaultAngle: 15,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-dust-storm',
    name: 'Dust Storm',
    category: 'Weather',
    description: 'Blowing red-brown dust suspended in air.',
    cssFilter: 'sepia(0.4) saturate(1.1) contrast(0.9) brightness(0.9)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 45,
    defaultAngle: 15,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay'
  },
  {
    id: 'weather-sand-storm',
    name: 'Sand Storm',
    category: 'Weather',
    description: 'Heavy desert sand storm winds.',
    cssFilter: 'sepia(0.5) saturate(1.2) contrast(0.85) brightness(0.88)',
    defaultIntensity: 80,
    defaultOpacity: 95,
    defaultSpeed: 55,
    defaultAngle: 25,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay'
  },
  {
    id: 'weather-ash',
    name: 'Volcanic Ash',
    category: 'Weather',
    description: 'Falling volcanic ash particulate flakes.',
    cssFilter: 'contrast(1.05) brightness(0.85) saturate(0.8)',
    defaultIntensity: 55,
    defaultOpacity: 80,
    defaultSpeed: 25,
    defaultAngle: 85,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'weather-smoke',
    name: 'Smoke',
    category: 'Weather',
    description: 'Drifting grey smoke layers from wildfire.',
    cssFilter: 'contrast(0.92) brightness(0.95)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 30,
    defaultAngle: 10,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-drizzle',
    name: 'Drizzle',
    category: 'Weather',
    description: 'Fine light mist rain spray.',
    cssFilter: 'contrast(0.96) brightness(0.97)',
    defaultIntensity: 35,
    defaultOpacity: 75,
    defaultSpeed: 30,
    defaultAngle: 80,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-hail',
    name: 'Hail Storm',
    category: 'Weather',
    description: 'Heavy falling icy hail pellets.',
    cssFilter: 'contrast(1.05) brightness(1.02)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 70,
    defaultAngle: 85,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-ice-storm',
    name: 'Ice Storm',
    category: 'Weather',
    description: 'Freezing rain coating edges in frosty glares.',
    cssFilter: 'saturate(0.8) brightness(1.05) contrast(1.08)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-aurora',
    name: 'Aurora Borealis',
    category: 'Weather',
    description: 'Ethereal moving green northern lights.',
    cssFilter: 'hue-rotate(120deg) saturate(1.4) brightness(1.1)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-rainbow',
    name: 'Rainbow',
    category: 'Weather',
    description: 'Stunning overhead atmospheric double rainbow.',
    cssFilter: 'saturate(1.2) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 0,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-sunrise',
    name: 'Sunrise',
    category: 'Weather',
    description: 'Soft pink and golden early morning sunlight.',
    cssFilter: 'sepia(0.15) hue-rotate(-15deg) saturate(1.2) brightness(1.08)',
    defaultIntensity: 45,
    defaultOpacity: 90,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-sunset',
    name: 'Sunset',
    category: 'Weather',
    description: 'Deep red, magenta and orange warm sunlight.',
    cssFilter: 'sepia(0.25) hue-rotate(-25deg) saturate(1.35) brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-golden-hour',
    name: 'Golden Hour',
    category: 'Weather',
    description: 'Premium soft warm glow of the late afternoon.',
    cssFilter: 'sepia(0.3) saturate(1.4) brightness(1.06) contrast(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-blue-hour',
    name: 'Blue Hour',
    category: 'Weather',
    description: 'Cool blue cinematic post-sunset grade.',
    cssFilter: 'hue-rotate(200deg) saturate(1.2) brightness(0.95) contrast(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 95,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'weather-moonlight',
    name: 'Moonlight',
    category: 'Weather',
    description: 'Eerie blue-grey night illumination.',
    cssFilter: 'hue-rotate(210deg) saturate(0.75) brightness(0.85) contrast(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-starry-night',
    name: 'Starry Night',
    category: 'Weather',
    description: 'Shining stars visual mask overlay.',
    cssFilter: 'brightness(0.95) contrast(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'weather-custom',
    name: 'Custom Weather',
    category: 'Weather',
    description: 'Fully customizable environmental particles.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 weather presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `weather-preset-${i}`,
    name: `Weather Condition ${i}`,
    category: 'Weather',
    description: `Environmental atmospheric preset variant #${i}.`,
    cssFilter: `hue-rotate(${i % 20}deg) brightness(${1.0 + (i % 4) * 0.03}) contrast(${1.0 + (i % 3) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 25 + (i % 7) * 5,
    defaultAngle: (i * 12) % 360,
    defaultDirection: i % 2 === 0 ? 'vertical' : 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const WEATHER_EFFECTS = list;
