import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'artistic-oilpainting',
    name: 'Oil Painting',
    category: 'Artistic',
    description: 'Thick, textured oil brush stroke styling with high contrast.',
    cssFilter: 'contrast(1.2) saturate(1.4) brightness(1.05)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-watercolor',
    name: 'Watercolor',
    category: 'Artistic',
    description: 'Soft canvas-bleed watercolor aesthetics with pastel tones.',
    cssFilter: 'contrast(0.95) saturate(1.25) brightness(1.06)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 4,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay'
  },
  {
    id: 'artistic-acrylic',
    name: 'Acrylic',
    category: 'Artistic',
    description: 'Saturated, heavy stroke acrylic color wash styling.',
    cssFilter: 'contrast(1.25) saturate(1.5) brightness(1.03)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-canvas',
    name: 'Canvas Painting',
    category: 'Artistic',
    description: 'Coarse woven paper canvas texture overlay.',
    cssFilter: 'contrast(1.05) saturate(1.1) brightness(1.01)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 2,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'multiply'
  },
  {
    id: 'artistic-pencil',
    name: 'Pencil Sketch',
    category: 'Artistic',
    description: 'Monochrome hand-drawn graphite outlines and crosshatch highlights.',
    cssFilter: 'grayscale(1) contrast(1.4) brightness(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-coloredpencil',
    name: 'Colored Pencil',
    category: 'Artistic',
    description: 'Slightly grainy colored pencil sketch outline shaders.',
    cssFilter: 'contrast(1.18) saturate(1.3) brightness(1.06)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-charcoal',
    name: 'Charcoal',
    category: 'Artistic',
    description: 'Dark, smoky carbon charcoal grain and smudges.',
    cssFilter: 'grayscale(1) contrast(1.6) brightness(0.85)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-ink',
    name: 'Ink Drawing',
    category: 'Artistic',
    description: 'Bold black gel ink outlines and stark brightness thresholds.',
    cssFilter: 'grayscale(1) contrast(1.9) brightness(1.1)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-marker',
    name: 'Marker Art',
    category: 'Artistic',
    description: 'Felt-tip marker saturation and bleeding stroke edges.',
    cssFilter: 'contrast(1.15) saturate(1.55) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 9,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-pastel',
    name: 'Pastel Art',
    category: 'Artistic',
    description: 'Chalky soft-focus pastel colors on gray card board.',
    cssFilter: 'saturate(1.2) contrast(0.9) brightness(1.08)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 4,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-popart',
    name: 'Pop Art',
    category: 'Artistic',
    description: 'Stark primary colors and retro halftone raster circles.',
    cssFilter: 'contrast(1.5) saturate(1.8) brightness(1.05)',
    defaultIntensity: 80,
    defaultOpacity: 95,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-comic',
    name: 'Comic Book',
    category: 'Artistic',
    description: 'Ink outline frames with high-contrast screen dot shading.',
    cssFilter: 'contrast(1.3) saturate(1.4) brightness(1.03)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-cartoon',
    name: 'Cartoon',
    category: 'Artistic',
    description: 'Flat vector coloring shading and bold dark borders.',
    cssFilter: 'contrast(1.2) saturate(1.45) brightness(1.02)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-anime',
    name: 'Anime Style',
    category: 'Artistic',
    description: 'Vibrant cell-shading outlines and soft fantasy highlights.',
    cssFilter: 'contrast(1.15) saturate(1.35) brightness(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-manga',
    name: 'Manga Style',
    category: 'Artistic',
    description: 'Monochrome screen tone textures and speedy motion strokes.',
    cssFilter: 'grayscale(1) contrast(1.5) brightness(1.05)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-lowpoly',
    name: 'Low Poly',
    category: 'Artistic',
    description: 'Triangular polygonal mosaic segmentation layers.',
    cssFilter: 'contrast(1.1) saturate(1.2) brightness(1.0)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-mosaic',
    name: 'Mosaic',
    category: 'Artistic',
    description: 'Clustered ceramic stone grids tile styling.',
    cssFilter: 'contrast(1.22) saturate(1.3) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-glass',
    name: 'Stained Glass',
    category: 'Artistic',
    description: 'Translucent glass segments bordered by black lead outlines.',
    cssFilter: 'contrast(1.28) saturate(1.5) brightness(1.05)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-abstract',
    name: 'Abstract Art',
    category: 'Artistic',
    description: 'Fluid organic neon color shapes floating dynamically.',
    cssFilter: 'hue-rotate(90deg) contrast(1.15) saturate(1.3) brightness(1.03)',
    defaultIntensity: 65,
    defaultOpacity: 80,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-impressionism',
    name: 'Impressionism',
    category: 'Artistic',
    description: 'Flickering dabs of pure color simulating outdoor sunlight.',
    cssFilter: 'contrast(1.1) saturate(1.3) brightness(1.06)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-cubism',
    name: 'Cubism',
    category: 'Artistic',
    description: 'Fragmented geometric facets perspective layering.',
    cssFilter: 'contrast(1.2) saturate(1.15) brightness(0.98)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-digital',
    name: 'Digital Painting',
    category: 'Artistic',
    description: 'Clean airbrush gradients and smooth vector shapes.',
    cssFilter: 'contrast(1.1) saturate(1.25) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 95,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-vintage',
    name: 'Vintage Illustration',
    category: 'Artistic',
    description: 'Aged newsprint colors with hand-etched crosshatch borders.',
    cssFilter: 'sepia(0.25) contrast(1.12) saturate(1.15) brightness(1.01)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 4,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-fineart',
    name: 'Fine Art',
    category: 'Artistic',
    description: 'Muted renaissance museum coloring and heavy canvas frames.',
    cssFilter: 'sepia(0.12) contrast(1.15) saturate(1.1) brightness(0.94)',
    defaultIntensity: 55,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-museum',
    name: 'Museum Style',
    category: 'Artistic',
    description: 'Dramatic lighting vignettes reminiscent of oil canvases.',
    cssFilter: 'contrast(1.25) saturate(1.2) brightness(0.9)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'artistic-custom',
    name: 'Custom Artistic',
    category: 'Artistic',
    description: 'Fully customizable painterly brush strokes and canvas texture.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];

// Generate remainder to have exactly 50 presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `artistic-preset-${i}`,
    name: `Art Look ${i}`,
    category: 'Artistic',
    description: `Creative artistic simulation variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 17) % 360}deg) brightness(${0.98 + (i % 3) * 0.02}) contrast(${1.07 + (i % 4) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 4) * 4,
    defaultSpeed: 10 + (i % 7) * 4,
    defaultAngle: (i * 31) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  });
}

export const ARTISTIC_EFFECTS = list;
