import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'cosmic-deepspace',
    name: 'Deep Space',
    category: 'Cosmic',
    description: 'Cold dark space color wash with faint remote starfields.',
    cssFilter: 'contrast(1.1) brightness(0.9) saturate(0.85)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-milkyway',
    name: 'Milky Way',
    category: 'Cosmic',
    description: 'Warm purple-orange stellar bands spanning across the screen.',
    cssFilter: 'contrast(1.15) saturate(1.25) brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 5,
    defaultAngle: 15,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-nebula',
    name: 'Nebula',
    category: 'Cosmic',
    description: 'Dense glowing ionized gas clouds in vibrant purple and magenta.',
    cssFilter: 'contrast(1.1) saturate(1.35) brightness(1.02)',
    defaultIntensity: 70,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-galaxycore',
    name: 'Galaxy Core',
    category: 'Cosmic',
    description: 'Intense central core glow fading into starry spiral arms.',
    cssFilter: 'brightness(1.15) contrast(1.2) saturate(1.3)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-blackhole',
    name: 'Black Hole',
    category: 'Cosmic',
    description: 'Bending space gravity well distortion at the screen center.',
    cssFilter: 'contrast(1.25) brightness(0.85) saturate(0.9)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-wormhole',
    name: 'Wormhole',
    category: 'Cosmic',
    description: 'Tunnel-like portal warping stars into concentric trails.',
    cssFilter: 'contrast(1.2) brightness(1.05) saturate(1.15)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-supernova',
    name: 'Supernova',
    category: 'Cosmic',
    description: 'Blinding white-blue star explosion with expanding energy waves.',
    cssFilter: 'brightness(1.25) contrast(1.15) saturate(1.4)',
    defaultIntensity: 80,
    defaultOpacity: 95,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-aurora',
    name: 'Aurora Galaxy',
    category: 'Cosmic',
    description: 'Dancing sheets of green and violet celestial polar lights.',
    cssFilter: 'contrast(1.1) saturate(1.4) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 14,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-storm',
    name: 'Cosmic Storm',
    category: 'Cosmic',
    description: 'Violent interstellar dust eddies and electric solar wind.',
    cssFilter: 'contrast(1.3) saturate(1.2) brightness(0.95)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 120,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-starfield',
    name: 'Starfield',
    category: 'Cosmic',
    description: 'Infinite layers of twinkling stellar dust particles.',
    cssFilter: 'contrast(1.05) saturate(1.1) brightness(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 90,
    defaultSpeed: 4,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-solar',
    name: 'Solar System',
    category: 'Cosmic',
    description: 'Orbiting planets with soft celestial backlighting.',
    cssFilter: 'contrast(1.12) saturate(1.2) brightness(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 80,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-lunar',
    name: 'Lunar Surface',
    category: 'Cosmic',
    description: 'Desaturated cold white moon glow and craters vignette.',
    cssFilter: 'saturate(0.4) contrast(1.2) brightness(0.9)',
    defaultIntensity: 50,
    defaultOpacity: 75,
    defaultSpeed: 2,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-orbit',
    name: 'Planet Orbit',
    category: 'Cosmic',
    description: 'Curved planetary horizon glow with atmospheric haze.',
    cssFilter: 'contrast(1.15) saturate(1.25) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-meteor',
    name: 'Meteor Shower',
    category: 'Cosmic',
    description: 'Streaks of fire raining down across deep space.',
    cssFilter: 'contrast(1.2) saturate(1.3) brightness(1.06)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 40,
    defaultAngle: 135,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-asteroid',
    name: 'Asteroid Field',
    category: 'Cosmic',
    description: 'Drifting space rocks layered with volumetric space dust.',
    cssFilter: 'contrast(1.18) saturate(0.9) brightness(0.88)',
    defaultIntensity: 60,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-portal',
    name: 'Space Portal',
    category: 'Cosmic',
    description: 'Vortex energy warp drawing the edges toward center.',
    cssFilter: 'contrast(1.25) saturate(1.4) brightness(1.08)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-infinity',
    name: 'Infinity Universe',
    category: 'Cosmic',
    description: 'Breathtaking layered multiverse bubbles and light flares.',
    cssFilter: 'contrast(1.1) saturate(1.3) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-energy',
    name: 'Cosmic Energy',
    category: 'Cosmic',
    description: 'Pulsing solar flare fields and active radiation belts.',
    cssFilter: 'contrast(1.2) saturate(1.5) brightness(1.1)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 22,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-heaven',
    name: 'Celestial Heaven',
    category: 'Cosmic',
    description: 'Divine golden volumetric light rays and nebulae.',
    cssFilter: 'sepia(0.15) contrast(1.1) saturate(1.3) brightness(1.12)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-interstellar',
    name: 'Interstellar',
    category: 'Cosmic',
    description: 'Warp-speed streak lines and dimensional shift filters.',
    cssFilter: 'contrast(1.22) saturate(1.25) brightness(1.02)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'cosmic-custom',
    name: 'Custom Cosmic',
    category: 'Cosmic',
    description: 'Fully customizable galaxy particle and nebula field.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 cosmic presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `cosmic-preset-${i}`,
    name: `Universe Variant ${i}`,
    category: 'Cosmic',
    description: `Cosmic space simulation variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 23) % 360}deg) brightness(${0.95 + (i % 3) * 0.03}) contrast(${1.08 + (i % 4) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 80 + (i % 4) * 4,
    defaultSpeed: 10 + (i % 7) * 4,
    defaultAngle: (i * 37) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const COSMIC_EFFECTS = list;
