import { EffectPreset } from './effectsPreset';

export const DISTORTION_EFFECTS: EffectPreset[] = [
  {
    id: 'dist-wave',
    name: 'Wave Distortion',
    category: 'Distortion',
    description: 'Simulates fluid wave motion offsets.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-ripple',
    name: 'Ripple',
    category: 'Distortion',
    description: 'Concentric water ripples expanding outwards.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-water',
    name: 'Water Distortion',
    category: 'Distortion',
    description: 'Organic underwater refraction distortion.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-heat',
    name: 'Heat Distortion',
    category: 'Distortion',
    description: 'Simulates rising hot air atmospheric sways.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-jelly',
    name: 'Jelly',
    category: 'Distortion',
    description: 'Bouncy organic gelatinous wobble movement.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-wobble',
    name: 'Wobble',
    category: 'Distortion',
    description: 'High-frequency wavy screen wobbling.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-stretch',
    name: 'Stretch Warp',
    category: 'Distortion',
    description: 'Perspective scale stretch deformation.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-twist',
    name: 'Twist',
    category: 'Distortion',
    description: 'Rotational vortex twist displacement.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-swirl',
    name: 'Swirl',
    category: 'Distortion',
    description: 'Circular fluid swirl displacement.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-spiral',
    name: 'Spiral',
    category: 'Distortion',
    description: 'Continuous spiral vortex displacement.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-liquify',
    name: 'Liquify',
    category: 'Distortion',
    description: 'Paints interactive fluid displacements.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-melt',
    name: 'Melt',
    category: 'Distortion',
    description: 'Simulates screen dripping melt down wards.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 180,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-pinch',
    name: 'Pinch',
    category: 'Distortion',
    description: 'Pinches pixels inwards to center.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-bulge',
    name: 'Bulge',
    category: 'Distortion',
    description: 'Bulges pixels outwards from center.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-warp',
    name: 'Warp',
    category: 'Distortion',
    description: 'Smooth directional UV coordinate warp.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-mesh',
    name: 'Mesh Warp',
    category: 'Distortion',
    description: 'Multi-grid coordinate mesh deformation.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-rubber',
    name: 'Rubber Warp',
    category: 'Distortion',
    description: 'Elastic rubber scale bounce motion.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-elastic',
    name: 'Elastic Warp',
    category: 'Distortion',
    description: 'Springy elastic grid bounce offset.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-mirror',
    name: 'Mirror Warp',
    category: 'Distortion',
    description: 'Symmetrical mirrored coordinate reflection.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-glass',
    name: 'Glass Warp',
    category: 'Distortion',
    description: 'Refracted bumpy glass pane deformation.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-liquid-glass',
    name: 'Liquid Glass',
    category: 'Distortion',
    description: 'Melting liquid glass coordinates flow.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-shockwave',
    name: 'Shockwave',
    category: 'Distortion',
    description: 'Explosive radial shock displacement sweep.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-vortex',
    name: 'Vortex',
    category: 'Distortion',
    description: 'High-speed center vortex spiral.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-kaleidoscope',
    name: 'Kaleidoscope',
    category: 'Distortion',
    description: 'Eight-way mirror kaleidoscope tiles.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-tunnel',
    name: 'Tunnel Vision',
    category: 'Distortion',
    description: 'Expanding radial visual tunnel zoom.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-blackhole',
    name: 'Black Hole',
    category: 'Distortion',
    description: 'Extreme gravitational warp swallowing pixels.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-gravity',
    name: 'Gravity Warp',
    category: 'Distortion',
    description: 'Downward gravitational pull stretch.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 180,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-time-warp',
    name: 'Time Warp',
    category: 'Distortion',
    description: 'Slit-scan rolling shutter distortion line.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-flow',
    name: 'Flow Warp',
    category: 'Distortion',
    description: 'Smooth directional flow coordinate drift.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-energy',
    name: 'Energy Distortion',
    category: 'Distortion',
    description: 'Procedural energy waves coords warp.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-refraction',
    name: 'Refraction Warp',
    category: 'Distortion',
    description: 'Index of refraction glass warp displacement.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-crystal',
    name: 'Crystal Warp',
    category: 'Distortion',
    description: 'Polygon crystal facet displacements.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-prism',
    name: 'Prism Distortion',
    category: 'Distortion',
    description: 'Spectrally separated prism edge offsets.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-pixel',
    name: 'Pixel Warp',
    category: 'Distortion',
    description: 'Blocky pixel block coordinate warper.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-wave-pulse',
    name: 'Wave Pulse',
    category: 'Distortion',
    description: 'Intermittent waves distortion pulses.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-ripple-pulse',
    name: 'Ripple Pulse',
    category: 'Distortion',
    description: 'Intermittent ripples distortion pulses.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-tornado',
    name: 'Tornado Warp',
    category: 'Distortion',
    description: 'Tornado shape center coordinate twist.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-space',
    name: 'Space Warp',
    category: 'Distortion',
    description: 'Simulates interstellar cosmic coordinate stretch.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-reality',
    name: 'Reality Bend',
    category: 'Distortion',
    description: 'Dreamlike reality bend scale stretches.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-dim-shift',
    name: 'Dimensional Shift',
    category: 'Distortion',
    description: 'Offset shifts across dimensional plane axes.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-elastic-bounce',
    name: 'Elastic Bounce',
    category: 'Distortion',
    description: 'Spring scale bounce grid displacement.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-dynamic',
    name: 'Dynamic Warp',
    category: 'Distortion',
    description: 'Active dynamic coordinate displacement mapping.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-organic',
    name: 'Organic Distortion',
    category: 'Distortion',
    description: 'Procedural noise organic blob sways.',
    cssFilter: 'none',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-fluid',
    name: 'Fluid Motion',
    category: 'Distortion',
    description: 'Simulates physics fluid motion coordinates flow.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-morph',
    name: 'Morph Distortion',
    category: 'Distortion',
    description: 'Slowing shifting morph layout warps.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-extreme',
    name: 'Extreme Warp',
    category: 'Distortion',
    description: 'High intensity coordinate grid bending.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-chaos',
    name: 'Chaos Distortion',
    category: 'Distortion',
    description: 'Erratic chaotic coordinates displacements.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-infinity',
    name: 'Infinity Warp',
    category: 'Distortion',
    description: 'Figure-eight coordinates infinity wraps.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-quantum',
    name: 'Quantum Distortion',
    category: 'Distortion',
    description: 'Sub-pixel coordinate grid quantum fluctuations.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'dist-master',
    name: 'Distortion Master',
    category: 'Distortion',
    description: 'Definitive professional coordinate deformation tool.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
