import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'dream-soft',
    name: 'Soft Dream',
    category: 'Dream',
    description: 'Subtle light glow and pastel color diffusion.',
    cssFilter: 'contrast(0.92) saturate(1.05) brightness(1.03)',
    defaultIntensity: 40,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-fairy-tale',
    name: 'Fairy Tale',
    category: 'Dream',
    description: 'Vibrant pink-gold dream glow and warm sparkles.',
    cssFilter: 'sepia(0.1) saturate(1.2) brightness(1.06) contrast(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-angelic',
    name: 'Angelic Glow',
    category: 'Dream',
    description: 'Intense heavenly soft white light rays and bloom.',
    cssFilter: 'contrast(0.88) brightness(1.08) saturate(0.9)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-heavenly',
    name: 'Heavenly Bloom',
    category: 'Dream',
    description: 'Ethereal high light diffusion and blue-tinted highlights.',
    cssFilter: 'contrast(0.9) brightness(1.05) saturate(0.95) hue-rotate(190deg)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-fantasy',
    name: 'Fantasy World',
    category: 'Dream',
    description: 'Surreal magenta and gold color tones.',
    cssFilter: 'hue-rotate(320deg) saturate(1.3) brightness(1.04) contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-moonlight',
    name: 'Moonlight Dream',
    category: 'Dream',
    description: 'Cool blue-grey glow with sparkling night stars.',
    cssFilter: 'hue-rotate(200deg) saturate(0.7) brightness(0.9) contrast(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 85,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-golden',
    name: 'Golden Dream',
    category: 'Dream',
    description: 'Premium warm sunset glow and gold lighting.',
    cssFilter: 'sepia(0.25) saturate(1.35) brightness(1.06) contrast(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-pink',
    name: 'Pink Dream',
    category: 'Dream',
    description: 'Romantic soft pink glow overlays.',
    cssFilter: 'hue-rotate(330deg) saturate(1.25) brightness(1.03)',
    defaultIntensity: 40,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-blue',
    name: 'Blue Dream',
    category: 'Dream',
    description: 'Atmospheric soft cyan-blue light haze.',
    cssFilter: 'hue-rotate(185deg) saturate(1.2) brightness(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-lavender',
    name: 'Lavender Dream',
    category: 'Dream',
    description: 'Soothing violet haze grading.',
    cssFilter: 'hue-rotate(270deg) saturate(1.3) brightness(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-cotton-candy',
    name: 'Cotton Candy',
    category: 'Dream',
    description: 'Dreamy pink, magenta, and cyan split tint.',
    cssFilter: 'saturate(1.4) brightness(1.08) contrast(0.97)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-cloud-nine',
    name: 'Cloud Nine',
    category: 'Dream',
    description: 'Deep fog layers and high highlight diffusion.',
    cssFilter: 'blur(0.5px) contrast(0.85) brightness(1.06)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-magical-forest',
    name: 'Magical Forest',
    category: 'Dream',
    description: 'Floating fairy sparkles in dark green lighting.',
    cssFilter: 'hue-rotate(100deg) saturate(1.15) brightness(0.92) contrast(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-mystic',
    name: 'Mystic Dream',
    category: 'Dream',
    description: 'Surreal purple sparkles and soft focus.',
    cssFilter: 'hue-rotate(280deg) saturate(1.25) brightness(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 80,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-romantic',
    name: 'Romantic Dream',
    category: 'Dream',
    description: 'Soft rose glow and warm side light rays.',
    cssFilter: 'sepia(0.15) hue-rotate(345deg) saturate(1.2) brightness(1.04)',
    defaultIntensity: 45,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-vintage',
    name: 'Vintage Dream',
    category: 'Dream',
    description: 'Retro faded colors with warm glow overlay.',
    cssFilter: 'sepia(0.2) contrast(0.9) brightness(1.02) saturate(0.95)',
    defaultIntensity: 40,
    defaultOpacity: 80,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-cinematic',
    name: 'Cinematic Dream',
    category: 'Dream',
    description: 'Mood-enhancing atmospheric volume bloom.',
    cssFilter: 'contrast(0.95) brightness(1.01) saturate(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-glow',
    name: 'Glow Dream',
    category: 'Dream',
    description: 'Intense blur focus overlay and high highlights.',
    cssFilter: 'brightness(1.06) contrast(0.95)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-celestial',
    name: 'Celestial Dream',
    category: 'Dream',
    description: 'Drifting space dust and cosmic light spots.',
    cssFilter: 'hue-rotate(240deg) saturate(1.25) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-dreamscape',
    name: 'Dreamscape',
    category: 'Dream',
    description: 'Slow changing dreamy color gradients.',
    cssFilter: 'saturate(1.2) brightness(1.04) contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'dream-custom',
    name: 'Custom Dream',
    category: 'Dream',
    description: 'Fully customizable surreal dream space.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 dream presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `dream-preset-${i}`,
    name: `Dream Haze ${i}`,
    category: 'Dream',
    description: `Surreal dream haze preset variant #${i}.`,
    cssFilter: `hue-rotate(${i % 25}deg) brightness(${1.0 + (i % 4) * 0.02}) contrast(${0.95 + (i % 3) * 0.02})`,
    defaultIntensity: 45 + (i % 6) * 5,
    defaultOpacity: 80 + (i % 3) * 5,
    defaultSpeed: 10 + (i % 7) * 3,
    defaultAngle: (i * 15) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const DREAM_EFFECTS = list;
