import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'gaming-fps',
    name: 'FPS Shooter',
    category: 'Gaming',
    description: 'Immersive shooter HUD with central targeting crosshair.',
    cssFilter: 'contrast(1.2) brightness(1.05) saturate(1.25)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-battleroyale',
    name: 'Battle Royale',
    category: 'Gaming',
    description: 'Vibrant highlight styling with map reticles.',
    cssFilter: 'contrast(1.15) saturate(1.3) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-esports',
    name: 'Esports',
    category: 'Gaming',
    description: 'High contrast tournament color grading and statistics feed.',
    cssFilter: 'contrast(1.25) saturate(1.35) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-rpg',
    name: 'RPG',
    category: 'Gaming',
    description: 'Warm fantasy coloring with level-up stat bars.',
    cssFilter: 'sepia(0.15) saturate(1.2) brightness(1.05) contrast(1.1)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-mmorpg',
    name: 'MMORPG',
    category: 'Gaming',
    description: 'Magical status frames and spell hotkey HUD overlays.',
    cssFilter: 'saturate(1.25) brightness(1.04) contrast(1.15)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 14,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-racing',
    name: 'Racing',
    category: 'Gaming',
    description: 'Fast horizontal speed streaks and tachometers.',
    cssFilter: 'contrast(1.18) saturate(1.3) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-drift',
    name: 'Drift',
    category: 'Gaming',
    description: 'High speed radial motion blur paths.',
    cssFilter: 'contrast(1.22) saturate(1.2) brightness(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 75,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-openworld',
    name: 'Open World',
    category: 'Gaming',
    description: 'Wide expansive nature grading with quest mini-maps.',
    cssFilter: 'contrast(1.1) saturate(1.25) brightness(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 80,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-survival',
    name: 'Survival',
    category: 'Gaming',
    description: 'Low-health blood vignetting and cold shadows.',
    cssFilter: 'contrast(1.25) brightness(0.85) saturate(0.8)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-zombie',
    name: 'Zombie Mode',
    category: 'Gaming',
    description: 'Dirty green survival HUD and dark blood vignettes.',
    cssFilter: 'contrast(1.3) brightness(0.75) saturate(0.8) hue-rotate(85deg)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-scifishooter',
    name: 'Sci-Fi Shooter',
    category: 'Gaming',
    description: 'High-tech neon ammunition bars and laser targeting.',
    cssFilter: 'hue-rotate(185deg) contrast(1.15) saturate(1.3) brightness(1.03)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-cyberpunk',
    name: 'Cyberpunk Arena',
    category: 'Gaming',
    description: 'Glow neon cyan/magenta cyber city indicators.',
    cssFilter: 'contrast(1.28) saturate(1.45) brightness(1.06) hue-rotate(315deg)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-arcade',
    name: 'Retro Arcade',
    category: 'Gaming',
    description: 'Old school scanlines and glowing vector text overlays.',
    cssFilter: 'contrast(1.35) saturate(1.5) brightness(1.08) hue-rotate(340deg)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-pixel',
    name: 'Pixel Gaming',
    category: 'Gaming',
    description: 'Glitchy retro 8-bit color map filter.',
    cssFilter: 'contrast(1.4) saturate(1.6) brightness(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-neon',
    name: 'Neon Arena',
    category: 'Gaming',
    description: 'Intense glowing neon borders and edge washes.',
    cssFilter: 'brightness(1.1) contrast(1.2) saturate(1.4)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-streamer',
    name: 'Streamer Mode',
    category: 'Gaming',
    description: 'Interactive chat feed and facecam neon borders.',
    cssFilter: 'contrast(1.1) saturate(1.2) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-bossfight',
    name: 'Boss Fight',
    category: 'Gaming',
    description: 'Giant red boss health indicator overlay.',
    cssFilter: 'contrast(1.3) saturate(1.3) brightness(0.85)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 22,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-victory',
    name: 'Victory Screen',
    category: 'Gaming',
    description: 'Immense gold light rays and clean Victory HUD letters.',
    cssFilter: 'sepia(0.2) saturate(1.45) brightness(1.15) contrast(1.1)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-highlight',
    name: 'Highlight Reel',
    category: 'Gaming',
    description: 'Cinematic saturated esports gameplay grade.',
    cssFilter: 'contrast(1.18) saturate(1.4) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 95,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-montage',
    name: 'Gaming Montage',
    category: 'Gaming',
    description: 'Dynamic beat-synced edge vignettes.',
    cssFilter: 'contrast(1.22) saturate(1.32) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'gaming-custom',
    name: 'Custom Gaming',
    category: 'Gaming',
    description: 'Fully customizable gaming HUD and speed system.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 gaming presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `gaming-preset-${i}`,
    name: `Montage Look ${i}`,
    category: 'Gaming',
    description: `Gaming montage preset variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 19) % 360}deg) brightness(${1.0 + (i % 3) * 0.02}) contrast(${1.08 + (i % 4) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 15 + (i % 7) * 4,
    defaultAngle: (i * 26) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const GAMING_EFFECTS = list;
