import { EffectPreset } from './effectsPreset';

export const GLITCH_EFFECTS: EffectPreset[] = [
  {
    id: 'glitch-rgb-split',
    name: 'RGB Split',
    category: 'Glitch',
    description: 'Separates red, green, and blue color channels.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-rgb-shift',
    name: 'RGB Shift',
    category: 'Glitch',
    description: 'Oscillating shift of red/blue color nodes.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-digital',
    name: 'Digital Glitch',
    category: 'Glitch',
    description: 'Simulates blocky digital signal distortions.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-pixel',
    name: 'Pixel Glitch',
    category: 'Glitch',
    description: 'Scatters horizontal lines of pixel cells.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-corruption',
    name: 'Data Corruption',
    category: 'Glitch',
    description: 'Heavy macroblock codec image corruption.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-tv-static',
    name: 'TV Static',
    category: 'Glitch',
    description: 'Analog snowy CRT signal television noise.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'overlay',
    overlayClass: 'animate-pulse bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.15)_50%)] bg-[size:100%_4px]'
  },
  {
    id: 'glitch-signal-loss',
    name: 'Signal Loss',
    category: 'Glitch',
    description: 'Flickering horizontal sync signal loss.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-scanlines',
    name: 'Scan Lines',
    category: 'Glitch',
    description: 'Aesthetic vintage cathode screen scanlines.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal',
    overlayStyle: {
      backgroundImage: 'linear-gradient(rgba(18,16,16,0) 50%, rgba(0,0,0,0.2) 50%)',
      backgroundSize: '100% 6px'
    }
  },
  {
    id: 'glitch-crt-flicker',
    name: 'CRT Flicker',
    category: 'Glitch',
    description: 'Phosphor screen cathode ray vertical flicker.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 75,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-screen-tear',
    name: 'Screen Tear',
    category: 'Glitch',
    description: 'Simulates unsynced vertical refresh tear line.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-frame-skip',
    name: 'Frame Skip',
    category: 'Glitch',
    description: 'Drop frames to create jittery playback.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-frame-freeze',
    name: 'Frame Freeze',
    category: 'Glitch',
    description: 'Freezes frames periodically.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-digital-noise',
    name: 'Digital Noise',
    category: 'Glitch',
    description: 'Speckled RGB digital noise patterns.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-compression',
    name: 'Compression Artifact',
    category: 'Glitch',
    description: 'Low-bitrate blocky compression rendering.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-codec-error',
    name: 'Codec Error',
    category: 'Glitch',
    description: 'Decoded video packet color bleed errors.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-broken-signal',
    name: 'Broken Signal',
    category: 'Glitch',
    description: 'Repeated signal interruption flickering.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-bitcrush',
    name: 'Bit Crush Video',
    category: 'Glitch',
    description: 'Reduces color depth to 4-bit web look.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-color-corruption',
    name: 'Color Corruption',
    category: 'Glitch',
    description: 'Extreme saturation color swap aberrations.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-color-offset',
    name: 'Color Offset',
    category: 'Glitch',
    description: 'Horizontal split offset of color buffers.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-hologram',
    name: 'Hologram Glitch',
    category: 'Glitch',
    description: 'Glowing blue cybernetic hologram lines.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen',
    overlayStyle: {
      background: 'linear-gradient(rgba(14,165,233,0.15) 50%, transparent 50%)',
      backgroundSize: '100% 8px'
    }
  },
  {
    id: 'glitch-matrix',
    name: 'Matrix Error',
    category: 'Glitch',
    description: 'Rainlike cascading green binary code bars.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen',
    overlayStyle: {
      background: 'linear-gradient(rgba(34,197,94,0.1) 50%, transparent 50%)',
      backgroundSize: '100% 12px'
    }
  },
  {
    id: 'glitch-cyber',
    name: 'Cyber Distortion',
    category: 'Glitch',
    description: 'High-frequency digital signal warps.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-datastream',
    name: 'Data Stream',
    category: 'Glitch',
    description: 'Binary data packet sways.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-signal-wave',
    name: 'Signal Wave',
    category: 'Glitch',
    description: 'Wavy frequency RF signal interference.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-static-flash',
    name: 'Static Flash',
    category: 'Glitch',
    description: 'White television noise flashing.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 85,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-interference',
    name: 'Electronic Interference',
    category: 'Glitch',
    description: 'Diagonal sweep static waves.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-broken-lcd',
    name: 'Broken LCD',
    category: 'Glitch',
    description: 'Simulates dead pixels and scan splits.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-pixel-drift',
    name: 'Pixel Drift',
    category: 'Glitch',
    description: 'Horizontal drift of pixel arrays.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-rgb-flicker',
    name: 'RGB Flicker',
    category: 'Glitch',
    description: 'Rapid flickering of color channels.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-color-flash',
    name: 'Color Flash',
    category: 'Glitch',
    description: 'Flickering solid color wash overlays.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-horiz-shift',
    name: 'Horizontal Shift',
    category: 'Glitch',
    description: 'Random horizontal line shifts.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-vert-shift',
    name: 'Vertical Shift',
    category: 'Glitch',
    description: 'Random vertical line shifts.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-slice',
    name: 'Slice Glitch',
    category: 'Glitch',
    description: 'Slices frames horizontally into shifted bars.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-block-shift',
    name: 'Block Shift',
    category: 'Glitch',
    description: 'Scatters rectangle block positions.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-fragment',
    name: 'Fragment Glitch',
    category: 'Glitch',
    description: 'Displaces sub-fragments of clips.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-mirror',
    name: 'Mirror Glitch',
    category: 'Glitch',
    description: 'Glitchy mirrored offset splits.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-wave',
    name: 'Wave Glitch',
    category: 'Glitch',
    description: 'Horizontal sine wave sync warp.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-neon',
    name: 'Neon Glitch',
    category: 'Glitch',
    description: 'Electric neon glowing color separations.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-cyber-flash',
    name: 'Cyber Flash',
    category: 'Glitch',
    description: 'Cyan-magenta cyber strobe flashing.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 80,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'glitch-frequency-err',
    name: 'Frequency Error',
    category: 'Glitch',
    description: 'Flickering sound wave video displacements.',
    cssFilter: 'none',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-digital-warp',
    name: 'Digital Warp',
    category: 'Glitch',
    description: 'Displaces pixels in grid cells.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-noise-pulse',
    name: 'Noise Pulse',
    category: 'Glitch',
    description: 'Rhythmic bursts of full-screen static noise.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-broken-frame',
    name: 'Broken Frame',
    category: 'Glitch',
    description: 'Unbalanced frame vertical rolls.',
    cssFilter: 'none',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-quantum',
    name: 'Quantum Glitch',
    category: 'Glitch',
    description: 'Sub-atomic quantum offset sways.',
    cssFilter: 'none',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-ai-error',
    name: 'AI Error',
    category: 'Glitch',
    description: 'Generative dreaming feedback warp loops.',
    cssFilter: 'none',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-system-crash',
    name: 'System Crash',
    category: 'Glitch',
    description: 'Simulates blue-screen memory dumps.',
    cssFilter: 'none',
    defaultIntensity: 85,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-memory-leak',
    name: 'Memory Leak',
    category: 'Glitch',
    description: 'Cumulative frames trails bleeding.',
    cssFilter: 'none',
    defaultIntensity: 75,
    defaultOpacity: 100,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-data-explosion',
    name: 'Data Explosion',
    category: 'Glitch',
    description: 'Violent color and block displacements.',
    cssFilter: 'none',
    defaultIntensity: 90,
    defaultOpacity: 100,
    defaultSpeed: 70,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-ultra',
    name: 'Ultra Glitch',
    category: 'Glitch',
    description: 'Heavy stacked glitch aberrations.',
    cssFilter: 'none',
    defaultIntensity: 85,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'glitch-master',
    name: 'Glitch Master',
    category: 'Glitch',
    description: 'Complete expert glitch synthesis.',
    cssFilter: 'none',
    defaultIntensity: 80,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
