import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'particles-dust',
    name: 'Floating Dust',
    category: 'Particles',
    description: 'Subtle cinematic floating dust specs.',
    cssFilter: 'brightness(1.02) contrast(1.01)',
    defaultIntensity: 40,
    defaultOpacity: 70,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-magic-dust',
    name: 'Magic Dust',
    category: 'Particles',
    description: 'Sparkling magical fairy dust particles.',
    cssFilter: 'saturate(1.2) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-fairy-dust',
    name: 'Fairy Dust',
    category: 'Particles',
    description: 'Shimmering pastel fairy dust trails.',
    cssFilter: 'saturate(1.3) brightness(1.06)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-golden',
    name: 'Golden Particles',
    category: 'Particles',
    description: 'Cinematic floating golden particles and bokeh.',
    cssFilter: 'sepia(0.2) saturate(1.3) brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-silver',
    name: 'Silver Particles',
    category: 'Particles',
    description: 'Elegant floating silver metallic flakes.',
    cssFilter: 'saturate(0.9) brightness(1.04) contrast(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-glitter',
    name: 'Glitter',
    category: 'Particles',
    description: 'High-intensity colorful sparkling glitter.',
    cssFilter: 'saturate(1.4) brightness(1.1) contrast(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-confetti',
    name: 'Confetti',
    category: 'Particles',
    description: 'Festive falling multi-color paper confetti.',
    cssFilter: 'saturate(1.3) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 35,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'particles-sparks',
    name: 'Fire Sparks',
    category: 'Particles',
    description: 'Flickering glowing fire sparks.',
    cssFilter: 'saturate(1.4) brightness(1.1) contrast(1.08)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-embers',
    name: 'Embers',
    category: 'Particles',
    description: 'Rising warm fireplace embers.',
    cssFilter: 'saturate(1.35) brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-snowflakes',
    name: 'Snowflakes',
    category: 'Particles',
    description: 'Falling winter snow flake crystals.',
    cssFilter: 'brightness(1.02) contrast(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-raindrops',
    name: 'Rain Drops',
    category: 'Particles',
    description: 'Falling linear rain drops.',
    cssFilter: 'contrast(0.95) brightness(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 60,
    defaultAngle: 75,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-splash',
    name: 'Water Splash',
    category: 'Particles',
    description: 'Splashing water drop particles.',
    cssFilter: 'contrast(0.96) brightness(1.02)',
    defaultIntensity: 40,
    defaultOpacity: 75,
    defaultSpeed: 45,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-bubble',
    name: 'Bubble Particles',
    category: 'Particles',
    description: 'Rising transparent soap bubbles.',
    cssFilter: 'saturate(1.1) brightness(1.03)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 22,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-smoke',
    name: 'Smoke Particles',
    category: 'Particles',
    description: 'Soft puffy smoke particle cloud puffs.',
    cssFilter: 'contrast(0.9) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 80,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-ash',
    name: 'Ash Particles',
    category: 'Particles',
    description: 'Particulate ash flakes falling slowly.',
    cssFilter: 'contrast(1.05) brightness(0.85)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 20,
    defaultAngle: 85,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'particles-leaves',
    name: 'Leaves',
    category: 'Particles',
    description: 'Drifting green and orange autumn leaves.',
    cssFilter: 'hue-rotate(20deg) saturate(1.2) brightness(1.02)',
    defaultIntensity: 45,
    defaultOpacity: 90,
    defaultSpeed: 24,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'particles-petals',
    name: 'Flower Petals',
    category: 'Particles',
    description: 'Drifting pink cherry blossom petals.',
    cssFilter: 'hue-rotate(330deg) saturate(1.3) brightness(1.05)',
    defaultIntensity: 45,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 45,
    defaultDirection: 'diagonal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'particles-stars',
    name: 'Stars',
    category: 'Particles',
    description: 'Glowing night sky star particles.',
    cssFilter: 'brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-galaxy',
    name: 'Galaxy Particles',
    category: 'Particles',
    description: 'Cosmic swirling galaxy orbs.',
    cssFilter: 'hue-rotate(240deg) saturate(1.4) brightness(1.1)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-cosmic-dust',
    name: 'Cosmic Dust',
    category: 'Particles',
    description: 'Atmospheric space dust and nebula fog.',
    cssFilter: 'hue-rotate(280deg) saturate(1.25) brightness(1.08)',
    defaultIntensity: 55,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-orbs',
    name: 'Energy Orbs',
    category: 'Particles',
    description: 'Volumetric floating plasma energy orbs.',
    cssFilter: 'hue-rotate(180deg) saturate(1.4) brightness(1.15)',
    defaultIntensity: 65,
    defaultOpacity: 90,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-light',
    name: 'Light Particles',
    category: 'Particles',
    description: 'Glimmering white light sparks.',
    cssFilter: 'brightness(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-neon',
    name: 'Neon Particles',
    category: 'Particles',
    description: 'Vibrant neon color particle drops.',
    cssFilter: 'saturate(1.5) brightness(1.1)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 28,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-crystal',
    name: 'Crystal Particles',
    category: 'Particles',
    description: 'Reflective crystalline glass pieces.',
    cssFilter: 'contrast(1.05) brightness(1.02)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-diamond',
    name: 'Diamond Sparkles',
    category: 'Particles',
    description: 'Luxury shining diamond lens flares.',
    cssFilter: 'brightness(1.15) contrast(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-bokeh',
    name: 'Bokeh Particles',
    category: 'Particles',
    description: 'Soft out-of-focus camera lens bokeh orbs.',
    cssFilter: 'blur(0.5px) brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-fireflies',
    name: 'Fireflies',
    category: 'Weather',
    description: 'Drifting yellow-green bio-luminescent fireflies.',
    cssFilter: 'hue-rotate(60deg) saturate(1.3) brightness(1.08)',
    defaultIntensity: 45,
    defaultOpacity: 80,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-hearts',
    name: 'Floating Hearts',
    category: 'Particles',
    description: 'Charming romantic floating heart emojis.',
    cssFilter: 'hue-rotate(340deg) saturate(1.4) brightness(1.05)',
    defaultIntensity: 40,
    defaultOpacity: 85,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'normal'
  },
  {
    id: 'particles-pixel',
    name: 'Pixel Particles',
    category: 'Particles',
    description: 'Retro game 8-bit block pixel square rain.',
    cssFilter: 'contrast(1.1) brightness(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 40,
    defaultAngle: 90,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  },
  {
    id: 'particles-custom',
    name: 'Custom Particles',
    category: 'Particles',
    description: 'User-configurable physical custom particle fields.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 particles presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `particles-preset-${i}`,
    name: `Particle Field ${i}`,
    category: 'Particles',
    description: `Animated particulate field preset variant #${i}.`,
    cssFilter: `brightness(${1.0 + (i % 4) * 0.02}) contrast(${1.0 + (i % 3) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 20 + (i % 7) * 4,
    defaultAngle: (i * 15) % 360,
    defaultDirection: 'vertical',
    defaultBlendMode: 'screen'
  });
}

export const PARTICLES_EFFECTS = list;
