import { EffectPreset } from './effectsPreset';

export const RETRO_EFFECTS: EffectPreset[] = [
  {
    id: 'retro-vintage-fade',
    name: 'Vintage Fade',
    category: 'Retro',
    description: 'Soft washed-out shadows for a vintage nostalgic look.',
    cssFilter: 'contrast(0.85) brightness(1.05) saturate(0.9)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-color',
    name: 'Retro Color',
    category: 'Retro',
    description: 'Analog warm saturated retro color grade.',
    cssFilter: 'saturate(1.25) sepia(0.12) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-classic-film',
    name: 'Classic Film',
    category: 'Retro',
    description: 'Simulates timeless 35mm physical cellulose look.',
    cssFilter: 'contrast(1.06) saturate(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-super8',
    name: 'Super 8 Film',
    category: 'Retro',
    description: 'Simulates vintage home movie Super 8 cameras.',
    cssFilter: 'sepia(0.2) contrast(0.95) saturate(1.1) brightness(1.04)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-8mm',
    name: '8mm Film',
    category: 'Retro',
    description: 'Authentic warm yellow-ish 8mm movie reel grade.',
    cssFilter: 'sepia(0.25) contrast(0.92) saturate(1.05)',
    defaultIntensity: 60,
    defaultOpacity: 100,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-16mm',
    name: '16mm Film',
    category: 'Retro',
    description: 'Gritty classic documentary film texture.',
    cssFilter: 'contrast(1.08) saturate(0.98) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-projector',
    name: 'Film Projector',
    category: 'Retro',
    description: 'Adds light flicker and dust of a mechanical film projector.',
    cssFilter: 'brightness(1.0) contrast(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-old-camera',
    name: 'Old Camera',
    category: 'Retro',
    description: 'Low-fidelity early snapshot digital camera grade.',
    cssFilter: 'contrast(0.9) brightness(1.03) saturate(0.88) blur(0.5px)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-analog-cam',
    name: 'Analog Camera',
    category: 'Retro',
    description: 'Warm nostalgic disposable film camera simulation.',
    cssFilter: 'sepia(0.1) contrast(1.02) saturate(1.15)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-vintage-lens',
    name: 'Vintage Lens',
    category: 'Retro',
    description: 'Chromatic outline softness and vignette wash.',
    cssFilter: 'blur(0.8px) contrast(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-warm-vin',
    name: 'Warm Vintage',
    category: 'Retro',
    description: 'Cozy solarized retro warm grade.',
    cssFilter: 'sepia(0.22) brightness(1.04) saturate(1.1)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-cold-vin',
    name: 'Cold Vintage',
    category: 'Retro',
    description: 'Nostalgic faded blue-cyan vintage color grade.',
    cssFilter: 'contrast(0.96) saturate(0.9) hue-rotate(185deg)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-sepia',
    name: 'Sepia Classic',
    category: 'Retro',
    description: 'Authentic 19th-century sepia monochrome look.',
    cssFilter: 'sepia(1.0) contrast(0.95) brightness(0.98)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-faded-mem',
    name: 'Faded Memory',
    category: 'Retro',
    description: 'Pastel desaturated low-contrast retro grade.',
    cssFilter: 'contrast(0.8) saturate(0.7) brightness(1.06)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-glow',
    name: 'Retro Glow',
    category: 'Retro',
    description: 'Soft halation highlights bloom wash.',
    cssFilter: 'brightness(1.06) saturate(1.08)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-contrast',
    name: 'Retro Contrast',
    category: 'Retro',
    description: 'Harsh deep shadows vintage look.',
    cssFilter: 'contrast(1.18) saturate(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-dust',
    name: 'Dust & Scratches',
    category: 'Retro',
    description: 'Procedural dust spots and scratches elements overlay.',
    cssFilter: 'contrast(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-dirt',
    name: 'Film Dirt',
    category: 'Retro',
    description: 'Authentic analog film gate dust specs.',
    cssFilter: 'contrast(1.02) brightness(0.98)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-burned-edge',
    name: 'Burned Edge',
    category: 'Retro',
    description: 'Light leak frame borders hot spots.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-paper',
    name: 'Paper Texture',
    category: 'Retro',
    description: 'Old paper grain fiber matte wash.',
    cssFilter: 'contrast(0.96) sepia(0.08)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-photograph',
    name: 'Old Photograph',
    category: 'Retro',
    description: 'Aged faded silver halide photo emulation.',
    cssFilter: 'sepia(0.15) contrast(0.94) saturate(0.9)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-antique',
    name: 'Antique Print',
    category: 'Retro',
    description: 'Dark warm antique print sepia grade.',
    cssFilter: 'sepia(0.4) contrast(0.9) brightness(0.95)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-frame',
    name: 'Vintage Frame',
    category: 'Retro',
    description: 'Film strip round border sprocket mask.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-blur',
    name: 'Retro Blur',
    category: 'Retro',
    description: 'Analog lens out-of-focus edge softness.',
    cssFilter: 'blur(2px)',
    defaultIntensity: 40,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-soft',
    name: 'Soft Vintage',
    category: 'Retro',
    description: 'Dreamy low contrast bloom glow.',
    cssFilter: 'brightness(1.04) contrast(0.9) blur(0.5px)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-washed-colors',
    name: 'Washed Colors',
    category: 'Retro',
    description: 'Low-saturation washed out vintage grade.',
    cssFilter: 'saturate(0.65) contrast(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-color-fade',
    name: 'Color Fade',
    category: 'Retro',
    description: 'Faded tint memory wash.',
    cssFilter: 'contrast(0.88) saturate(0.85) sepia(0.08)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-leak',
    name: 'Light Leak Vintage',
    category: 'Retro',
    description: 'Orange warm dynamic light leaks sweeping.',
    cssFilter: 'brightness(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-rainbow-leak',
    name: 'Rainbow Leak',
    category: 'Retro',
    description: 'Prismatic rainbow leak sweep overlay.',
    cssFilter: 'brightness(1.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-golden-film',
    name: 'Golden Film',
    category: 'Retro',
    description: 'Rich warm golden hour vintage look.',
    cssFilter: 'sepia(0.18) saturate(1.2) brightness(1.05) contrast(1.04)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-bloom',
    name: 'Retro Bloom',
    category: 'Retro',
    description: 'Diffusion filter halation highlights glow.',
    cssFilter: 'brightness(1.06) saturate(1.04) contrast(0.98)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-grain',
    name: 'Analog Grain',
    category: 'Retro',
    description: 'High-frequency photographic film grain texture.',
    cssFilter: 'contrast(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 55,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-flicker',
    name: 'Film Flicker',
    category: 'Retro',
    description: 'Simulates shutter bulb exposure flickers.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-flash',
    name: 'Vintage Flash',
    category: 'Retro',
    description: 'Analog flash bulb exposure burst wash.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-cam-flash',
    name: 'Camera Flash Retro',
    category: 'Retro',
    description: 'Decaying retro snapshot exposure flash.',
    cssFilter: 'brightness(1.0)',
    defaultIntensity: 70,
    defaultOpacity: 100,
    defaultSpeed: 65,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'retro-noise',
    name: 'Retro Noise',
    category: 'Retro',
    description: 'Analog composite signal noise sways.',
    cssFilter: 'contrast(1.04) brightness(0.99)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 45,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-color-shift',
    name: 'Color Shift Retro',
    category: 'Retro',
    description: 'Red-blue print misalignment fringe.',
    cssFilter: 'none',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-shadow',
    name: 'Analog Shadow',
    category: 'Retro',
    description: 'Faded lift offset shadow vintage look.',
    cssFilter: 'contrast(0.85) brightness(1.04)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 0,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-warm-film',
    name: 'Warm Film',
    category: 'Retro',
    description: 'Cozy sepia-amber vintage film look.',
    cssFilter: 'sepia(0.15) contrast(1.03) saturate(1.1)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-cinema',
    name: 'Retro Cinema',
    category: 'Retro',
    description: 'Hollywood mid-century analog cinema look.',
    cssFilter: 'contrast(1.06) saturate(1.02) sepia(0.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-documentary',
    name: 'Vintage Documentary',
    category: 'Retro',
    description: 'Low-contrast archive film strip look.',
    cssFilter: 'contrast(0.92) saturate(0.85) sepia(0.1)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-time-capsule',
    name: 'Time Capsule',
    category: 'Retro',
    description: 'Severe aged vintage look.',
    cssFilter: 'sepia(0.35) contrast(0.85) brightness(0.98) saturate(0.8)',
    defaultIntensity: 65,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-nostalgia',
    name: 'Nostalgia',
    category: 'Retro',
    description: 'Soft pastel memory color grade.',
    cssFilter: 'contrast(0.92) saturate(0.9) brightness(1.02) sepia(0.06)',
    defaultIntensity: 45,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-tv-movie',
    name: 'Old TV Movie',
    category: 'Retro',
    description: 'Aged screen gate lines and warm color lut.',
    cssFilter: 'contrast(1.04) sepia(0.12)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-memories',
    name: 'Retro Memories',
    category: 'Retro',
    description: 'Cozy warm home polaroid look.',
    cssFilter: 'sepia(0.14) contrast(0.95) saturate(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-heritage',
    name: 'Heritage Film',
    category: 'Retro',
    description: 'Archive color grade film simulation.',
    cssFilter: 'contrast(1.02) saturate(0.88) sepia(0.08)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-vintage-master',
    name: 'Vintage Master',
    category: 'Retro',
    description: 'Signature archive composite vintage synthesizer.',
    cssFilter: 'contrast(1.05) saturate(0.92) sepia(0.08)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-analog-master',
    name: 'Analog Master',
    category: 'Retro',
    description: 'Timeless camera analog format synthesizers.',
    cssFilter: 'sepia(0.15) contrast(0.98) saturate(1.05)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-classic-cinema',
    name: 'Classic Cinema',
    category: 'Retro',
    description: 'Vintage movie format lut color wash.',
    cssFilter: 'contrast(1.08) saturate(0.95) sepia(0.05)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'retro-master',
    name: 'Retro Master',
    category: 'Retro',
    description: 'Definitive professional nostalgic format emulator.',
    cssFilter: 'sepia(0.12) contrast(0.96) saturate(0.95)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];
