import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'scifi-cyberpunk',
    name: 'Cyberpunk',
    category: 'Sci-Fi',
    description: 'Electric pink-cyan neon colors and futuristic grid lights.',
    cssFilter: 'contrast(1.25) saturate(1.4) brightness(1.05) hue-rotate(320deg)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-spacestation',
    name: 'Space Station',
    category: 'Sci-Fi',
    description: 'Sterile fluorescent white/cyan capsule cabin lights.',
    cssFilter: 'contrast(1.1) brightness(0.95) saturate(0.85) hue-rotate(180deg)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-spaceship',
    name: 'Spaceship',
    category: 'Sci-Fi',
    description: 'Deep navy lighting with warning red indicator blinks.',
    cssFilter: 'contrast(1.2) brightness(0.8) saturate(1.1) sepia(0.1)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-galaxy',
    name: 'Galaxy',
    category: 'Sci-Fi',
    description: 'Cosmic purple/magenta star fields and deep space glow.',
    cssFilter: 'hue-rotate(265deg) saturate(1.35) brightness(1.02) contrast(1.15)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-deepspace',
    name: 'Deep Space',
    category: 'Sci-Fi',
    description: 'Dark blue-black gradient vignetting and starlight sparkles.',
    cssFilter: 'contrast(1.3) brightness(0.7) saturate(0.7) hue-rotate(200deg)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-alienplanet',
    name: 'Alien Planet',
    category: 'Sci-Fi',
    description: 'Surreal dual-sun green and orange ambient coloring.',
    cssFilter: 'hue-rotate(75deg) saturate(1.2) brightness(0.9) contrast(1.1)',
    defaultIntensity: 50,
    defaultOpacity: 80,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-hologram',
    name: 'Hologram',
    category: 'Sci-Fi',
    description: 'Flickering horizontal neon-blue interface lines.',
    cssFilter: 'hue-rotate(190deg) saturate(0.9) brightness(1.1) contrast(0.9)',
    defaultIntensity: 70,
    defaultOpacity: 75,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-ai',
    name: 'AI Interface',
    category: 'Sci-Fi',
    description: 'Clean cyan heads-up data scanner indicators.',
    cssFilter: 'hue-rotate(180deg) saturate(1.1) brightness(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 80,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-robotvision',
    name: 'Robot Vision',
    category: 'Sci-Fi',
    description: 'Pixelated high-contrast red thermal camera vision.',
    cssFilter: 'contrast(1.4) brightness(1.05) saturate(1.5) sepia(0.3) hue-rotate(-40deg)',
    defaultIntensity: 75,
    defaultOpacity: 90,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-android',
    name: 'Android',
    category: 'Sci-Fi',
    description: 'Cold metallic grey tones with high-tech outlines.',
    cssFilter: 'saturate(0.4) brightness(0.95) contrast(1.18)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-quantum',
    name: 'Quantum Energy',
    category: 'Sci-Fi',
    description: 'Drifting subatomic golden light loops.',
    cssFilter: 'sepia(0.2) saturate(1.4) brightness(1.08) contrast(1.03)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-plasmacore',
    name: 'Plasma Core',
    category: 'Sci-Fi',
    description: 'Rotating energetic electric magenta fields.',
    cssFilter: 'hue-rotate(295deg) saturate(1.5) brightness(1.1) contrast(1.1)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 30,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-warpdrive',
    name: 'Warp Drive',
    category: 'Sci-Fi',
    description: 'Fast zooming radial light ray trails.',
    cssFilter: 'brightness(1.15) contrast(1.05)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 50,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-timeportal',
    name: 'Time Portal',
    category: 'Sci-Fi',
    description: 'Distorted swirling gravity tunnel ring fields.',
    cssFilter: 'hue-rotate(240deg) saturate(1.25) brightness(1.04) contrast(0.95)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-hyperdrive',
    name: 'Hyperdrive',
    category: 'Sci-Fi',
    description: 'Intense linear space speed streaks.',
    cssFilter: 'brightness(1.1) contrast(1.02) saturate(0.9)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 60,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-digitalfuture',
    name: 'Digital Future',
    category: 'Sci-Fi',
    description: 'Green matrix code streams and cyber grids.',
    cssFilter: 'hue-rotate(110deg) saturate(1.3) brightness(0.9) contrast(1.2)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 35,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-neoncity',
    name: 'Neon City',
    category: 'Sci-Fi',
    description: 'Vibrant neon billboards color reflection filter.',
    cssFilter: 'contrast(1.22) saturate(1.45) brightness(1.03)',
    defaultIntensity: 55,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-laserworld',
    name: 'Laser World',
    category: 'Sci-Fi',
    description: 'Crisscrossing vector neon-green lasers.',
    cssFilter: 'hue-rotate(120deg) saturate(1.5) brightness(1.1) contrast(1.25)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 40,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-tron',
    name: 'Tron Style',
    category: 'Sci-Fi',
    description: 'Pitch black background high-contrast bright cyan edges.',
    cssFilter: 'contrast(1.5) brightness(0.9) saturate(1.3) hue-rotate(190deg)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-lab',
    name: 'Futuristic Lab',
    category: 'Sci-Fi',
    description: 'Clean medical laser scans and hologram readouts.',
    cssFilter: 'contrast(1.12) brightness(0.98) saturate(0.9) hue-rotate(185deg)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'scifi-custom',
    name: 'Custom Sci-Fi',
    category: 'Sci-Fi',
    description: 'Fully configurable futuristic energy environment.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  }
];

// Generate remainder to have exactly 50 sci-fi presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `scifi-preset-${i}`,
    name: `Cyber Grid ${i}`,
    category: 'Sci-Fi',
    description: `Futuristic grid visual preset variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 17) % 360}deg) brightness(${1.0 + (i % 3) * 0.03}) contrast(${1.05 + (i % 4) * 0.03})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 3) * 4,
    defaultSpeed: 15 + (i % 7) * 4,
    defaultAngle: (i * 24) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  });
}

export const SCIFI_EFFECTS = list;
