import { EffectPreset } from './effectsPreset';

const list: EffectPreset[] = [
  {
    id: 'threed-cinematic',
    name: 'Cinematic 3D',
    category: '3D',
    description: 'Immersive cinematic depth simulation with subtle tilt.',
    cssFilter: 'contrast(1.1) saturate(1.15) brightness(1.02)',
    defaultIntensity: 60,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-popout',
    name: 'Pop-Out',
    category: '3D',
    description: 'Brings subjects to the foreground with an active zoom scale.',
    cssFilter: 'contrast(1.15) saturate(1.2) brightness(1.05)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-floating',
    name: 'Floating Object',
    category: '3D',
    description: 'Simulates floating layers with dynamic ambient occlusion shadows.',
    cssFilter: 'contrast(1.08) saturate(1.1) brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 85,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-card',
    name: '3D Card',
    category: '3D',
    description: 'Flattens clip into a card rotating on 3D perspective space.',
    cssFilter: 'contrast(1.1) saturate(1.15)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-cube',
    name: '3D Cube',
    category: '3D',
    description: 'Simulated 3D cubic volumetric projection horizons.',
    cssFilter: 'contrast(1.2) saturate(1.25) brightness(1.03)',
    defaultIntensity: 65,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-flip',
    name: '3D Flip',
    category: '3D',
    description: 'Continuous vertical flip rotation over the Y axis.',
    cssFilter: 'contrast(1.1) saturate(1.2)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 20,
    defaultAngle: 90,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-rotation',
    name: '3D Rotation',
    category: '3D',
    description: 'Rotates clip across X, Y, and Z axes simultaneously.',
    cssFilter: 'contrast(1.15) saturate(1.15) brightness(1.01)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 14,
    defaultAngle: 45,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-room',
    name: '3D Room',
    category: '3D',
    description: 'Simulates a deep virtual room box with receding walls.',
    cssFilter: 'contrast(1.25) saturate(1.1) brightness(0.95)',
    defaultIntensity: 75,
    defaultOpacity: 85,
    defaultSpeed: 6,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-holographic',
    name: 'Holographic 3D',
    category: '3D',
    description: 'Futuristic glowing holographic projection lines and scan layers.',
    cssFilter: 'hue-rotate(180deg) saturate(1.4) contrast(1.1) brightness(1.08)',
    defaultIntensity: 60,
    defaultOpacity: 80,
    defaultSpeed: 25,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'threed-glass',
    name: 'Glass 3D',
    category: '3D',
    description: 'Refractive glass lens borders simulating deep thickness.',
    cssFilter: 'contrast(1.12) saturate(1.05) brightness(1.03)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 5,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-crystal',
    name: 'Crystal 3D',
    category: '3D',
    description: 'Prismatic crystal refraction splitting colors on edges.',
    cssFilter: 'contrast(1.18) saturate(1.3) brightness(1.04)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 8,
    defaultAngle: 30,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-metallic',
    name: 'Metallic 3D',
    category: '3D',
    description: 'Chrome reflections with high-contrast metallic specular levels.',
    cssFilter: 'contrast(1.35) saturate(0.85) brightness(1.02)',
    defaultIntensity: 70,
    defaultOpacity: 95,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-neon',
    name: 'Neon 3D',
    category: '3D',
    description: 'Volumetric neon tubes extending out from boundaries.',
    cssFilter: 'brightness(1.1) contrast(1.2) saturate(1.4)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 18,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'threed-gaming',
    name: 'Gaming 3D',
    category: '3D',
    description: 'Action-packed esports isometric HUD projections.',
    cssFilter: 'contrast(1.2) saturate(1.35) brightness(1.04)',
    defaultIntensity: 60,
    defaultOpacity: 85,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-scifi',
    name: 'Sci-Fi 3D',
    category: '3D',
    description: 'Futuristic dashboard HUD panel rotating in deep space.',
    cssFilter: 'hue-rotate(190deg) contrast(1.15) saturate(1.25) brightness(1.02)',
    defaultIntensity: 65,
    defaultOpacity: 85,
    defaultSpeed: 22,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'screen'
  },
  {
    id: 'threed-layers',
    name: 'Floating Layers',
    category: '3D',
    description: 'Simulates multiple layer steps sliding horizontally at different speeds.',
    cssFilter: 'contrast(1.08) saturate(1.15) brightness(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 90,
    defaultSpeed: 8,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-multidepth',
    name: 'Multi-Depth',
    category: '3D',
    description: 'Parallax movement splitting background and foreground layers.',
    cssFilter: 'contrast(1.12) saturate(1.2) brightness(1.02)',
    defaultIntensity: 55,
    defaultOpacity: 90,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-perspective',
    name: 'Hyper Perspective',
    category: '3D',
    description: 'Extreme dynamic vanishing point coordinates projection.',
    cssFilter: 'contrast(1.22) saturate(1.28) brightness(1.05)',
    defaultIntensity: 75,
    defaultOpacity: 95,
    defaultSpeed: 12,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-imax',
    name: 'IMAX 3D',
    category: '3D',
    description: 'Curved cinematic projection screens simulating grand theater space.',
    cssFilter: 'contrast(1.15) saturate(1.22) brightness(1.04)',
    defaultIntensity: 60,
    defaultOpacity: 95,
    defaultSpeed: 4,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-premium',
    name: 'Premium 3D',
    category: '3D',
    description: 'High-end volumetric lighting shading and ambient occlusion.',
    cssFilter: 'contrast(1.18) saturate(1.25) brightness(1.03)',
    defaultIntensity: 70,
    defaultOpacity: 90,
    defaultSpeed: 15,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  },
  {
    id: 'threed-custom',
    name: 'Custom 3D',
    category: '3D',
    description: 'Fully customizable 3D coordinate space and perspective transformation.',
    cssFilter: 'brightness(1.0) contrast(1.0)',
    defaultIntensity: 50,
    defaultOpacity: 100,
    defaultSpeed: 10,
    defaultAngle: 0,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  }
];

// Generate remainder to have exactly 50 3D presets
for (let i = list.length + 1; i <= 50; i++) {
  list.push({
    id: `threed-preset-${i}`,
    name: `Perspective variant ${i}`,
    category: '3D',
    description: `3D perspective coordinate simulation variant #${i}.`,
    cssFilter: `hue-rotate(${(i * 13) % 360}deg) brightness(${0.96 + (i % 3) * 0.03}) contrast(${1.05 + (i % 4) * 0.02})`,
    defaultIntensity: 50 + (i % 6) * 5,
    defaultOpacity: 85 + (i % 4) * 4,
    defaultSpeed: 10 + (i % 7) * 4,
    defaultAngle: (i * 29) % 360,
    defaultDirection: 'horizontal',
    defaultBlendMode: 'normal'
  });
}

export const THREED_EFFECTS = list;
