import { EffectItem } from '../components/EffectGrid';

export const GLITCH_EFFECTS: EffectItem[] = [
  { id: 'ai-breakdown', name: 'AI Breakdown', description: 'Fractured rendering shapes representing neural models crashing.', icon: '🧠', isNew: true },
  { id: 'ai-corruption', name: 'AI Corruption', description: 'Abstract visual feedback loops mimicking deepdream errors.', icon: '🦾', isNew: true },
  { id: 'analog-glitch', name: 'Analog Glitch', description: 'Continuous wavy lines representing antenna sync errors.', icon: '📻' },
  { id: 'broken-pixels', name: 'Broken Pixels', description: 'Static colored block grids locked at specific coordinates.', icon: '🟩', isNew: true },
  { id: 'chromatic-shift', name: 'Chromatic Shift', description: 'Continuous color channel shifts on motion sweeps.', icon: '💫' },
  { id: 'code-collapse', name: 'Code Collapse', description: 'Overlay scroll of vertical programming warnings and code drops.', icon: '💻', isNew: true },
  { id: 'cyber-error', name: 'Cyber Error', description: 'High brightness red flash alerts overlaid on terminal windows.', icon: '🚨', isNew: true },
  { id: 'cyber-flash', name: 'Cyber Flash', description: 'RGB offset visual spikes flashing on high contrast borders.', icon: '⚡', isNew: true },
  { id: 'data-corruption', name: 'Data Corruption', description: 'Raw byte blocks overlaid as random glitch art colors.', icon: '💾' },
  { id: 'data-storm', name: 'Data Storm', description: 'Heavy horizontal streams of randomized character codes.', icon: '🌪️', isNew: true },
  { id: 'digital-echo', name: 'Digital Echo', description: 'Lagging outline buffers replicating past motion trails.', icon: '🕯️', isNew: true },
  { id: 'digital-distortion', name: 'Digital Distortion', description: 'Warped vector lines bending subjects out of shape.', icon: '🌀' },
  { id: 'digital-ghost', name: 'Digital Ghost', description: 'Desaturated duplicate frames displaced by position offsets.', icon: '👻', isNew: true },
  { id: 'digital-glitch', name: 'Digital Glitch', description: 'Blocky digital compression artifacts and rendering errors.', icon: '🖥️' },
  { id: 'error-screen', name: 'Error Screen', description: 'Flashes system warning dialogue cards or code screens.', icon: '⚠️' },
  { id: 'error-wave', name: 'Error Wave', description: 'Horizontal coordinate displacement ripple moving down screen.', icon: '🌊', isNew: true },
  { id: 'frame-corrupt', name: 'Frame Corrupt', description: 'Intermittent interlaced horizontal slice displacements.', icon: '✂️', isNew: true },
  { id: 'frame-skip', name: 'Frame Skip', description: 'Simulates dropped rendering frames and stuttering actions.', icon: '⏳' },
  { id: 'future-glitch', name: 'Future Glitch', description: 'Sci-fi vector grid scans with blue offset shadows.', icon: '🤖', isNew: true },
  { id: 'glitch-pulse', name: 'Glitch Pulse', description: 'Rhythmic flash offsets synced with audio bass hum.', icon: '💓', isNew: true },
  { id: 'gpu-crash', name: 'GPU Crash', description: 'Severe vector distortions and color channel flips.', icon: '🔌', isNew: true },
  { id: 'hologram-glitch', name: 'Hologram Glitch', description: 'Sci-fi grid scans and blue flickering glow lines.', icon: '🤖' },
  { id: 'holographic-error', name: 'Holographic Error', description: 'Flickering grid displacement lines over cyan wash filters.', icon: '🤖', isNew: true },
  { id: 'matrix-glitch', name: 'Matrix Glitch', description: 'Falling green code streams overlaying digital details.', icon: '🎛️' },
  { id: 'memory-error', name: 'Memory Error', description: 'Temporary memory leak buffer frame overlaying current clip.', icon: '💾', isNew: true },
  { id: 'neon-glitch', name: 'Neon Glitch', description: 'High brightness color sparks discharging from edges.', icon: '🚨' },
  { id: 'neural-glitch', name: 'Neural Glitch', description: 'Stylized dream hallucination style pattern overlays.', icon: '🧠', isNew: true },
  { id: 'neural-scan', name: 'Neural Scan', description: 'Laser grid sweeps scrolling vertically over active subjects.', icon: '📊', isNew: true },
  { id: 'pixel-glitch', name: 'Pixel Glitch', description: 'Scattered rectangular pixel blocks shuffling positions.', icon: '🟩' },
  { id: 'pixel-storm', name: 'Pixel Storm', description: 'Heavy screen noise of small moving coordinate squares.', icon: '👾', isNew: true },
  { id: 'quantum-glitch', name: 'Quantum Glitch', description: 'Sub-atomic level noise splits shifting green/purple colors.', icon: '⚛️', isNew: true },
  { id: 'rgb-glitch', name: 'RGB Glitch', description: 'Splits red, green, and blue color channels with dynamic shakes.', icon: '👾' },
  { id: 'rgb-split', name: 'RGB Split', description: 'Fixed offset chromatic aberration on high contrast edges.', icon: '🌈' },
  { id: 'rgb-storm', name: 'RGB Storm', description: 'Heavy colored chromatic splits shifting directions rapidly.', icon: '⛈️', isNew: true },
  { id: 'scan-lines', name: 'Scan Lines', description: 'Standard horizontal grid overlay mimicking interlace monitors.', icon: '📊' },
  { id: 'screen-tear', name: 'Screen Tear', description: 'Splits frame lines horizontally with buffer delay mismatch.', icon: '✂️' },
  { id: 'signal-crash', name: 'Signal Crash', description: 'Simulates complete signal drop to color bar grids.', icon: '📴', isNew: true },
  { id: 'signal-loss', name: 'Signal Loss', description: 'Flickering color bars indicating connection failures.', icon: '📳' },
  { id: 'static-noise', name: 'Static Noise', description: 'Salt-and-pepper grain static overlay mimicking dead air.', icon: '🌫️' },
  { id: 'static-storm', name: 'Static Storm', description: 'Dense analog static overlay blocking out primary details.', icon: '🌫️', isNew: true },
  { id: 'system-failure', name: 'System Failure', description: 'Flashes system blue screens of death alerts.', icon: '⚠️', isNew: true },
  { id: 'tv-glitch', name: 'TV Glitch', description: 'Cathode-ray tube screen flicker and analog signal drift.', icon: '📺' },
  { id: 'tv-noise', name: 'TV Noise', description: 'Snow storm static grain balancing luminance values.', icon: '❄️' },
  { id: 'vhs-glitch', name: 'VHS Glitch', description: 'Tape distortion tracking bars, noise lines, and sync glitches.', icon: '📼' },
  { id: 'vhs-warp', name: 'VHS Warp', description: 'Organic tape edge bend distortion curving borders.', icon: '📼', isNew: true }
];
