/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as FeatureFlagsRouteImport } from './routes/feature-flags'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsRoute = FeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backups': typeof BackupsRoute
  '/credits': typeof CreditsRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/tickets': typeof TicketsRoute
  '/transactions': typeof TransactionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backups': typeof BackupsRoute
  '/credits': typeof CreditsRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/tickets': typeof TicketsRoute
  '/transactions': typeof TransactionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backups': typeof BackupsRoute
  '/credits': typeof CreditsRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/tickets': typeof TicketsRoute
  '/transactions': typeof TransactionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/announcements'
    | '/audit-logs'
    | '/backups'
    | '/credits'
    | '/feature-flags'
    | '/feedback'
    | '/jobs'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/permissions'
    | '/plans'
    | '/roles'
    | '/sessions'
    | '/settings'
    | '/system-health'
    | '/tickets'
    | '/transactions'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/announcements'
    | '/audit-logs'
    | '/backups'
    | '/credits'
    | '/feature-flags'
    | '/feedback'
    | '/jobs'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/permissions'
    | '/plans'
    | '/roles'
    | '/sessions'
    | '/settings'
    | '/system-health'
    | '/tickets'
    | '/transactions'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/announcements'
    | '/audit-logs'
    | '/backups'
    | '/credits'
    | '/feature-flags'
    | '/feedback'
    | '/jobs'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/permissions'
    | '/plans'
    | '/roles'
    | '/sessions'
    | '/settings'
    | '/system-health'
    | '/tickets'
    | '/transactions'
    | '/users/$userId'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BackupsRoute: typeof BackupsRoute
  CreditsRoute: typeof CreditsRoute
  FeatureFlagsRoute: typeof FeatureFlagsRoute
  FeedbackRoute: typeof FeedbackRoute
  JobsRoute: typeof JobsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  MonitoringRoute: typeof MonitoringRoute
  PermissionsRoute: typeof PermissionsRoute
  PlansRoute: typeof PlansRoute
  RolesRoute: typeof RolesRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  TicketsRoute: typeof TicketsRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags': {
      id: '/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof FeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BackupsRoute: BackupsRoute,
  CreditsRoute: CreditsRoute,
  FeatureFlagsRoute: FeatureFlagsRoute,
  FeedbackRoute: FeedbackRoute,
  JobsRoute: JobsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  MonitoringRoute: MonitoringRoute,
  PermissionsRoute: PermissionsRoute,
  PlansRoute: PlansRoute,
  RolesRoute: RolesRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SystemHealthRoute: SystemHealthRoute,
  TicketsRoute: TicketsRoute,
  TransactionsRoute: TransactionsRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
