import { EffectItem } from '../components/EffectGrid';

export const CINEMATIC_EFFECTS: EffectItem[] = [
  { id: 'arctic-cinema', name: 'Arctic Cinema', description: 'Cold clinical grade with muted warm colors and frozen cyan shades.', icon: '❄️', colorGrading: 'hue-rotate(180deg) saturate(0.8) contrast(1.05) brightness(0.95)', isNew: true },
  { id: 'blockbuster', name: 'Blockbuster', description: 'High contrast action film look with cold shadow balances.', icon: '💥', colorGrading: 'contrast(1.25) saturate(1.15) brightness(0.95)' },
  { id: 'bronze-film', name: 'Bronze Film', description: 'Warm amber tones and rich brown shadows reminiscent of retro cinema.', icon: '🪵', colorGrading: 'sepia(0.3) saturate(1.1) hue-rotate(-5deg) contrast(1.15)', isNew: true },
  { id: 'cinema-infinity', name: 'Cinema Infinity', description: 'High dynamic range profile with rich details and vibrant saturations.', icon: '🌌', colorGrading: 'contrast(1.2) saturate(1.25) brightness(1.02)', isNew: true },
  { id: 'cinemascope-pro', name: 'CinemaScope Pro', description: 'Slightly muted tones and wide dynamic scope mapping.', icon: '🎞️', colorGrading: 'contrast(1.1) saturate(1.1) brightness(0.98)', isNew: true },
  { id: 'cinematic-lut', name: 'Cinematic LUT', description: 'Standard high-fidelity lookup table color profile.', icon: '🎬', colorGrading: 'contrast(1.1) saturate(1.1)' },
  { id: 'cool-cinema', name: 'Cool Cinema', description: 'Cold and clinical styling for dystopian drama scenes.', icon: '❄️', colorGrading: 'hue-rotate(180deg) saturate(0.85) contrast(1.05)' },
  { id: 'crimson-film', name: 'Crimson Film', description: 'Deep red saturation enhancements and hot skin tones.', icon: '🔴', colorGrading: 'hue-rotate(-15deg) saturate(1.2) contrast(1.1)', isNew: true },
  { id: 'dark-cinema', name: 'Dark Cinema', description: 'Low exposure with high shadow preservation details.', icon: '⬛', colorGrading: 'brightness(0.85) contrast(1.1) saturate(0.95)' },
  { id: 'desert-cinema', name: 'Desert Cinema', description: 'Warm sepia highlights and dusty dry air saturation.', icon: '🏜️', colorGrading: 'sepia(0.25) hue-rotate(-10deg) saturate(1.1) brightness(1.05)', isNew: true },
  { id: 'directors-vision', name: 'Director\'s Vision', description: 'Uncompromised cinematic grade balancing high contrast and rich details.', icon: '🕶️', colorGrading: 'contrast(1.15) saturate(1.1) brightness(1.0)', isNew: true },
  { id: 'documentary-look', name: 'Documentary Look', description: 'Organic desaturated profile prioritizing natural tones.', icon: '📹', colorGrading: 'contrast(1.05) saturate(0.95) brightness(1.02)', isNew: true },
  { id: 'dolby-vision-look', name: 'Dolby Vision Look', description: 'Ultra vibrant colors and high-end mastering contrast.', icon: '📺', colorGrading: 'contrast(1.3) saturate(1.3) brightness(1.05)', isNew: true },
  { id: 'drama-film', name: 'Drama Film', description: 'Moody color profile with deep shadows and highlighted midtones.', icon: '🎭', colorGrading: 'contrast(1.2) saturate(0.9) brightness(0.98)' },
  { id: 'dream-cinema', name: 'Dream Cinema', description: 'Soft glow color values with high brightness limits.', icon: '💭', colorGrading: 'brightness(1.1) saturate(1.15) contrast(0.95)' },
  { id: 'emerald-film', name: 'Emerald Film', description: 'Deep green shadows and cold mint highlights for indie horror.', icon: '🟢', colorGrading: 'hue-rotate(10deg) saturate(1.05) contrast(1.15)', isNew: true },
  { id: 'emotional-film', name: 'Emotional Film', description: 'Low contrast washed look with soft light levels.', icon: '🕯️', colorGrading: 'contrast(1.05) saturate(0.85) brightness(1.03)', isNew: true },
  { id: 'epic-film', name: 'Epic Film', description: 'High saturation dynamic range cinematic filter.', icon: '🏆', colorGrading: 'contrast(1.1) saturate(1.3) brightness(1.02)' },
  { id: 'festival-film', name: 'Festival Film', description: 'Artistic grade with warm green tones and high saturation.', icon: '🎬', colorGrading: 'contrast(1.2) saturate(1.15) hue-rotate(5deg)', isNew: true },
  { id: 'film-fade', name: 'Film Fade', description: 'Lifted black coordinates for a vintage faded look.', icon: '🌫️', colorGrading: 'brightness(1.05) contrast(0.85) sepia(0.1)' },
  { id: 'golden-hour', name: 'Golden Hour', description: 'Enriched orange sunlight gradients for sunsets.', icon: '🌇', colorGrading: 'sepia(0.35) saturate(1.25) hue-rotate(-15deg)' },
  { id: 'hdr-cinema', name: 'HDR Cinema', description: 'Balanced contrast ranges to maximize exposure details.', icon: '📺', colorGrading: 'contrast(1.05) saturate(1.2) brightness(1.05)' },
  { id: 'high-contrast-cinema', name: 'High Contrast Cinema', description: 'Strong black-and-white points for intense action scenes.', icon: '⚡', colorGrading: 'contrast(1.3) saturate(1.1)' },
  { id: 'hollywood-look', name: 'Hollywood Look', description: 'Warm skin tones and cyan shadow grading.', icon: '🌟', colorGrading: 'contrast(1.15) hue-rotate(-5deg) saturate(1.05)' },
  { id: 'indie-film', name: 'Indie Film', description: 'Green-tinted cold look inspired by independent cinema.', icon: '🍀', colorGrading: 'hue-rotate(15deg) saturate(0.95) contrast(1.1)' },
  { id: 'low-contrast-film', name: 'Low Contrast Film', description: 'Soft desaturated style mimicking raw analog footage.', icon: '🎞️', colorGrading: 'contrast(0.8) saturate(0.9)' },
  { id: 'luxury-cinema', name: 'Luxury Cinema', description: 'Elegant gold-graded highlights and rich dark levels.', icon: '👑', colorGrading: 'contrast(1.15) saturate(1.2) brightness(1.01)', isNew: true },
  { id: 'midnight-cinema', name: 'Midnight Cinema', description: 'Dark blue tones with sharp contrast matching nighttime action.', icon: '🌙', colorGrading: 'brightness(0.9) contrast(1.25) hue-rotate(170deg) saturate(0.9)', isNew: true },
  { id: 'moody-cinema', name: 'Moody Cinema', description: 'Desaturated tones with strong dark contrast values.', icon: '🌙', colorGrading: 'contrast(1.25) saturate(0.7) brightness(0.9)' },
  { id: 'neon-cinema', name: 'Neon Cinema', description: 'Stylized cyberpunk grade pushing high cyan/purple tones.', icon: '🔮', colorGrading: 'saturate(1.5) contrast(1.2) hue-rotate(25deg)', isNew: true },
  { id: 'noir', name: 'Noir', description: 'Classic high contrast monochrome silver screen layout.', icon: '🕶️', colorGrading: 'grayscale(1) contrast(1.5) brightness(0.9)' },
  { id: 'oscar-grade', name: 'Oscar Grade', description: 'Standard Academy look with perfect skin tone balances.', icon: '🏆', colorGrading: 'contrast(1.2) saturate(1.12) brightness(0.99)', isNew: true },
  { id: 'platinum-film', name: 'Platinum Film', description: 'Desaturated high brightness look with metallic silver tones.', icon: '💿', colorGrading: 'grayscale(0.3) contrast(1.2) saturate(0.9) brightness(1.02)', isNew: true },
  { id: 'premium-lut', name: 'Premium LUT', description: 'Premium generic color look updating overall dynamics.', icon: '🎨', colorGrading: 'contrast(1.12) saturate(1.15)', isNew: true },
  { id: 'silent-drama', name: 'Silent Drama', description: 'Grayscale base with slight sepia dirt overlay.', icon: '📽️', colorGrading: 'grayscale(1) contrast(1.25) brightness(0.95) sepia(0.15)', isNew: true },
  { id: 'soft-cinema', name: 'Soft Cinema', description: 'Low contrast clean film look for romantic narratives.', icon: '🌸', colorGrading: 'contrast(0.9) saturate(1.05) brightness(1.02)' },
  { id: 'storm-cinema', name: 'Storm Cinema', description: 'Moody dark skies tint with heavy desaturated blues.', icon: '⛈️', colorGrading: 'hue-rotate(190deg) saturate(0.75) contrast(1.2) brightness(0.92)', isNew: true },
  { id: 'studio-look', name: 'Studio Look', description: 'Clean studio grade boosting overall lighting levels.', icon: '💡', colorGrading: 'contrast(1.08) saturate(1.12) brightness(1.03)', isNew: true },
  { id: 'sunset-cinema-pro', name: 'Sunset Cinema Pro', description: 'Deep red/orange sky grade representing warm sunset settings.', icon: '🌇', colorGrading: 'sepia(0.3) saturate(1.25) hue-rotate(-12deg) contrast(1.1)', isNew: true },
  { id: 'teal-orange', name: 'Teal & Orange', description: 'Perfect cinematic teal shadows and orange highlight balance.', icon: '🍊', colorGrading: 'contrast(1.2) hue-rotate(-10deg) saturate(1.2)' },
  { id: 'thriller-grade', name: 'Thriller Grade', description: 'High contrast green shadows and low overall brightness values.', icon: '🔪', colorGrading: 'contrast(1.3) saturate(0.8) hue-rotate(160deg) brightness(0.95)', isNew: true },
  { id: 'ultra-film', name: 'Ultra Film', description: 'Vivid color saturation balance mimicking modern blockbusters.', icon: '🎞️', colorGrading: 'contrast(1.18) saturate(1.22)', isNew: true },
  { id: 'velvet-shadows', name: 'Velvet Shadows', description: 'Rich dark level detail with warm midtones.', icon: '🐈', colorGrading: 'contrast(1.25) saturate(1.05) brightness(0.97)', isNew: true },
  { id: 'vintage-cinema', name: 'Vintage Cinema', description: 'Retro 8mm format with sepia textures and low saturation.', icon: '📹', colorGrading: 'sepia(0.4) saturate(0.8) contrast(0.9)' },
  { id: 'warm-cinema', name: 'Warm Cinema', description: 'Golden film filters for soft daylight sequences.', icon: '🔥', colorGrading: 'sepia(0.2) saturate(1.1) brightness(1.05)' }
];
