"""Render Definition domain models for Asset Rendering Layer."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from app.models.enums import AssetType, PlanType


class RenderKind(str, Enum):
    """Category kind of render definition."""

    EFFECT = "EFFECT"
    FILTER = "FILTER"
    TRANSITION = "TRANSITION"
    OVERLAY = "OVERLAY"
    COMPOSITE = "COMPOSITE"


class RenderDefinition(BaseModel):
    """Abstract metadata-driven render definition payload generated by AssetResolver."""

    id: str = Field(..., description="Asset or catalog item identifier")
    name: str = Field(..., description="Human readable asset name")
    kind: RenderKind = Field(..., description="Category kind of rendering definition")
    asset_type: AssetType = Field(..., description="Asset type classification")
    engine_key: str = Field(..., description="Unique engine key for rendering pipeline execution")
    category: str = Field(..., description="Asset category")
    version: int = Field(default=1, description="Asset definition version")
    required_plan: PlanType = Field(default=PlanType.FREE, description="Minimum subscription plan required")
    enabled: bool = Field(default=True, description="Whether asset is active for rendering")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Resolved parameters for rendering")
    filter_chain: List[str] = Field(default_factory=list, description="Abstract filter specifications")
    layer_priority: int = Field(default=0, description="Z-order rendering stack priority")
    user_has_access: bool = Field(default=True, description="Whether requesting user has access permission")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional resolved metadata")


class StackedRenderDefinition(BaseModel):
    """Container payload for multiple stacked render definitions (effects, filters, transitions)."""

    clip_id: str = Field(..., description="Target clip ID")
    track_id: str = Field(..., description="Parent track ID")
    effects: List[RenderDefinition] = Field(default_factory=list, description="Ordered list of effect render definitions")
    filters: List[RenderDefinition] = Field(default_factory=list, description="Ordered list of filter render definitions")
    transition: Optional[RenderDefinition] = Field(None, description="Optional transition render definition")
    combined_filter_chain: List[str] = Field(default_factory=list, description="Flattened execution filter chain")
