import { EffectItem } from '../components/EffectGrid';

export const PARTICLES_EFFECTS: EffectItem[] = [
  { id: 'aurora-dust', name: 'Aurora Dust', description: 'Glow green and pink volumetric particles moving slowly.', icon: '🌌', isNew: true },
  { id: 'aurora-sparks', name: 'Aurora Sparks', description: 'Flickering color sparks drifting over aurora clouds.', icon: '✨', isNew: true },
  { id: 'bubble-particles', name: 'Bubble Particles', description: 'Translucent soap bubbles rising and popping on impact.', icon: '🫧' },
  { id: 'confetti', name: 'Confetti', description: 'Vibrant colored paper fragments falling down in rotation.', icon: '🎉' },
  { id: 'cosmic-dust', name: 'Cosmic Dust', description: 'Glow nebula gas clouds with fine starry dots.', icon: '🌌' },
  { id: 'cosmic-sparks', name: 'Cosmic Sparks', description: 'Energetic white sparkles drifting diagonally.', icon: '⭐', isNew: true },
  { id: 'crystal-dust', name: 'Crystal Dust', description: 'Fine prismatic reflections floating in ambient space.', icon: '💎', isNew: true },
  { id: 'diamond-rain', name: 'Diamond Rain', description: 'Densely falling crystal specs glittering on motion.', icon: '🌧️', isNew: true },
  { id: 'diamond-sparkles', name: 'Diamond Sparkles', description: 'Prismatic crystal shines radiating brief high-contrast light.', icon: '💎' },
  { id: 'dream-particles', name: 'Dream Particles', description: 'Soft slow breathing glow circles adding ambient depth.', icon: '💭', isNew: true },
  { id: 'electric-dust', name: 'Electric Dust', description: 'High frequency tiny spark particles discharging from subjects.', icon: '⚡', isNew: true },
  { id: 'ember-rain', name: 'Ember Rain', description: 'Falling hot glowing coal sparks drifting down from borders.', icon: '🔥', isNew: true },
  { id: 'energy-particles', name: 'Energy Particles', description: 'Electric arc sparks buzzing across random edges.', icon: '⚡' },
  { id: 'energy-sphere', name: 'Energy Sphere', description: 'Glowing plasma spheres orbiting around central screen coordinates.', icon: '🔮', isNew: true },
  { id: 'fairy-dust-pro', name: 'Fairy Dust Pro', description: 'Magical trail of high-brightness gold sparkles.', icon: '🪄', isNew: true },
  { id: 'fire-dust', name: 'Fire Dust', description: 'Warm orange ambient sparks rising up.', icon: '🔥', isNew: true },
  { id: 'fireflies', name: 'Fireflies', description: 'Soft yellow-green bioluminescent bugs floating slowly.', icon: '🪰' },
  { id: 'floating-diamonds', name: 'Floating Diamonds', description: 'Glinting glass diamond geometries rotating slowly.', icon: '💎', isNew: true },
  { id: 'floating-orbs', name: 'Floating Orbs', description: 'Soft white and blue light spheres hovering in place.', icon: '🔵', isNew: true },
  { id: 'floating-shapes', name: 'Floating Shapes', description: 'Retro vector geometric shapes scaling and drifting.', icon: '📐' },
  { id: 'galaxy-spark', name: 'Galaxy Spark', description: 'Rotating cluster of fine spiral galaxy stars.', icon: '🌌', isNew: true },
  { id: 'glitter', name: 'Glitter', description: 'Multitude of fine sparkly reflections reacting to ambient light.', icon: '✨' },
  { id: 'gold-particles', name: 'Gold Particles', description: 'Rich luxury golden dust specs rising upwards.', icon: '🪙' },
  { id: 'gold-spark-shower', name: 'Gold Spark Shower', description: 'Dense waterfall of bright golden spark trails.', icon: '🪙', isNew: true },
  { id: 'hearts', name: 'Hearts', description: 'Floating red heart icons rising from bottom coordinates.', icon: '❤️' },
  { id: 'ice-crystals', name: 'Ice Crystals', description: 'Falling hexagonal frost shapes glittering cold.', icon: '❄️', isNew: true },
  { id: 'infinity-particles', name: 'Infinity Particles', description: 'Rising cosmic particles looping in an infinity loop trail.', icon: '♾️', isNew: true },
  { id: 'laser-particles', name: 'Laser Particles', description: 'Straight bright neon light streaks crossing background viewport.', icon: '🚨', isNew: true },
  { id: 'light-mist', name: 'Light Mist', description: 'Fine particles of glowing moisture catch ambient lighting.', icon: '🌫️', isNew: true },
  { id: 'light-particles', name: 'Light Particles', description: 'Ambient volumetric white dust specs catching light rays.', icon: '💡' },
  { id: 'magic-dust', name: 'Magic Dust', description: 'Sparkly purple trails following hand sweeps.', icon: '🪄' },
  { id: 'magic-trails', name: 'Magic Trails', description: 'Stylized glowing trails following moving targets.', icon: '🪄', isNew: true },
  { id: 'neon-dust', name: 'Neon Dust', description: 'Vibrant neon cyan/magenta sparks floating around borders.', icon: '🚨', isNew: true },
  { id: 'neon-particles', name: 'Neon Particles', description: 'Electric cyan and magenta glow lines drifting.', icon: '🚨' },
  { id: 'particle-explosion', name: 'Particle Explosion', description: 'Central burst of glowing dots expanding outward.', icon: '💥' },
  { id: 'pixel-particles', name: 'Pixel Particles', description: 'Square blocks rising like a retro computing system.', icon: '👾' },
  { id: 'plasma-particles', name: 'Plasma Particles', description: 'Highly charged energy sparks branching out.', icon: '⚡', isNew: true },
  { id: 'rain-particles', name: 'Rain Particles', description: 'Splash drop shapes appearing dynamically at bottom viewport.', icon: '🌧️' },
  { id: 'rainbow-particles', name: 'Rainbow Particles', description: 'Multi-colored glow dots drifting vertically.', icon: '🌈', isNew: true },
  { id: 'silver-particles', name: 'Silver Particles', description: 'Cool metallic silver specs floating vertically.', icon: '🥈' },
  { id: 'silver-spark-shower', name: 'Silver Spark Shower', description: 'Dense waterfall of bright silver spark trails.', icon: '🥈', isNew: true },
  { id: 'snow-particles', name: 'Snow Particles', description: 'Fine crystalline star shapes drifting slowly.', icon: '❄️' },
  { id: 'sparkles', name: 'Sparkles', description: 'Classic four-point star glints appearing on highlights.', icon: '✨' },
  { id: 'stardust-flow', name: 'Stardust Flow', description: 'Wave of fine gold dust drifting horizontally.', icon: '✨', isNew: true },
  { id: 'stars', name: 'Stars', description: 'Five-point yellow star shapes floating and rotating.', icon: '⭐' }
];
